### ISSUE TITLE
Delight Sprint: Sep 22, 2021 - Oct 6, 2021

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#1]
RC 21st | Release 28th 

**Sprint Goal**
- Build: Spaces defects from backlog
- Build: Spaces enhancements from backlog
- Build: Spaces IA prototypes in Framer (80% design)
- Discovery: Subspaces exploration, definition, and plan. What is needed to bring them out of Beta/Experimental?

---
 ✅  for this Sprint
 ☢️  maybe for this Sprint
 ⛔️  not for this Sprint

**Comment by daniellekirkwood** [comment]
### Spaces defects from Backlog

**11 Minor issues in [Web](https://github.com/vector-im/element-web/issues?q=is%3Aissue+is%3Aopen+label%3AA-spaces+label%3AT-Defect+label%3AS-Minor+sort%3Acomments-desc)**
- [ ] #18754 : Responsive rendering, should be addressed needs a little design work. ✅  for this Sprint
- [ ] #17283 : Absolute-positioning. ✅
- [ ] #19066 : Kicking from Space doesn't act as expected ✅
- [ ] #18975 : Notification Badge not acting as expected ✅
- [ ] #19102 : Leaving Space warning incorrect  ✅
- [ ] #19093 : Appearance bug ✅
- [ ] #18296 : Subspace related content change. ☢️  maybe for this Sprint
- [ ] #19026 : Needs design, might be a quick fix but also could be wrapped into IA work ☢️ 
- [ ] #19010 : Consistent invite to Space experience. ☢️   needs design
- [ ] #18527 : Notification: Badge related. ⛔️  not for this Sprint
- [ ] #5227 : Notifications ⛔️ 

**3 Minor issues on [Android](https://github.com/vector-im/element-android/issues?q=is%3Aissue+is%3Aopen+label%3AA-spaces+label%3AT-Defect+label%3AS-Minor+sort%3Acomments-desc+)**
- [ ] 3933 : Clicking on Invite URL from DM should take user to Space (but doesn't) ✅
- [ ] 3934 : Space name validation on form field, not creation ✅
- [ ] 3935 : Have sticky Save button when adding rooms ✅

**4 Minor issues on [iOS](https://github.com/vector-im/element-ios/issues?q=is%3Aissue+is%3Aopen+label%3AA-spaces+label%3AT-Defect+label%3AS-Minor+sort%3Acomments-desc+)**
- [ ] 4844 : Time taken to join Suggested Room ✅
- [ ] 4851 : Tab name updating ✅
- [ ] 4849 : Refreshing Suggested Room list when suggestion removed ✅
- [ ] 4852 : Resetting Search/Filter when switching Space

**Comment by daniellekirkwood** [comment]
### Build: Spaces enhancements from backlog

*88 Enhancements on [web](https://github.com/vector-im/element-web/issues?q=is%3Aissue+is%3Aopen+label%3AA-spaces+label%3AT-Enhancement+sort%3Acomments-desc+)*
- [ ] ...

*13 Enhancements on [Android](https://github.com/vector-im/element-android/issues?q=is%3Aissue+is%3Aopen+label%3AA-spaces+label%3AT-Enhancement+sort%3Acomments-desc+)*

- [ ] 

*1 Enhancement on [iOS](https://github.com/vector-im/element-ios/issues?q=is%3Aissue+is%3Aopen+label%3AA-spaces+label%3AT-Enhancement+sort%3Acomments-desc+)*
- [ ] #4848 : Go to Space when joining Space ✅

**Comment by daniellekirkwood** [comment]
### Build: Spaces IA prototypes in Framer

[Spaces IA Brief (WIP)](https://docs.google.com/spreadsheets/d/18qa5yzNQVYRr_Zyt3FdZ7rOXO6vwJ82tbvtQmurYfhY/edit?usp=sharing)

**[IA Issues](https://github.com/issues?q=is%3Aopen+label%3Az-ia)**
- [ ]

**Comment by daniellekirkwood** [comment]
### Discovery: Subspaces exploration, definition, and plan

**[Subspaces issues](https://github.com/issues?q=is%3Aopen+label%3Aa-subspaces)**
