### ISSUE TITLE
Implement Posthog analytics

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-meta#10]
- [ ] Prompt all users to opt-in to new tracking scheme
  - Web
  - Android
  - iOS
- [ ] Enable Posthog analytics in production
- [ ] Create dashboards for a subset of high level metrics
- [ ] Document a process for creating a new event
