### ISSUE TITLE
Search a user to start a chat 

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-meta#1013]
As a user I want to be able to search a user before I start a 1:1 chat.

**Designs**
[Start a chat](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=229%3A26514&t=ckPVhCOmBY0ntGkf-1)
[No results](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=479%3A76114&t=Z0DjJWkTXqj6gcpT-1)

**Matrix APIs**
- [User Directory - Search](https://spec.matrix.org/v1.6/client-server-api/#user-directory)

**ACs**
- The search feature is part of [this screen](https://github.com/vector-im/element-meta/issues/1012).
- Search starts as soon as the user writes at least 3 characters
- Ask **5** results to the home server 
- If the users delete text, we don't show results if there are less than 3 characters
- The list updates live whenever the user changes the search text
- Cells in the list shows:
    - The avatar image
    - The user's display name
    - The user's matrix identifier
- No other functionality is meant to be implemented as a part of this ticket (eg. taps on any result)
- Suggestions and recents fetching logics will be implemented [here](https://github.com/vector-im/element-meta/issues/1015).
- Clients should "debounce" calls while the user is typing (0,5 sec of delay)
- Show the "No results" when the server returns zero results (see the related design)

**Questions**
- Should "debounce" be implemented in the rust layer?
- How many results should we ask to the home server? @amshakal 

```[tasklist]
### Tasks
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1569
- [ ] https://github.com/vector-im/element-x-android/issues/95
- [ ] https://github.com/vector-im/element-x-ios/issues/593
- [ ] https://github.com/vector-im/element-x-ios/issues/767
```

**Dependencies**

- https://github.com/matrix-org/matrix-rust-sdk/issues/1569
