### ISSUE TITLE
Show or create direct message room

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-meta#1014]
As a user I want to create a new 1:1 chat with an other user.
- The users can use the matrix-id of an other user to create a new chat
- A new timeline view is shown

**Designs**
[Start a chat](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=229%3A26514&t=ckPVhCOmBY0ntGkf-1)

**Note**
- The creation of the room on the first message has been moved here: https://github.com/vector-im/element-meta/issues/1160. @Florian14 is leading the conversation for the implementation [here](https://docs.google.com/document/d/11qSz8Gk2Be6tW9hcDLgVSQgW05o8qYXBJs9w9wYr_34/edit).

**ACs**
- The user can type a matrix identifier in the search field
- Exactly one user with the typed identifier will be shown under the search field
- The real search isn't part of this ticket we just want to navigate to a DM room with the matrix identifier the user is typing
- Tap on the user opens a timeline with the user's avatar and display name
- The search screen should be dismissed before the navigation to the timeline
- The room is created after the user taps on a person he found
    - A fullscreen loader should be shown during the creation
    - Show a fullscreen alert in case of errors
          - Title: "Server error"
          - Description: "An error occurred when trying to start a chat"
          - "Cancel" button: dismiss the alert
          - "Retry"  button: retries the room creation 
- ⚠️ When creating new chat the room preset should be: preset: **trusted_private_chat**
- If a user has already a pending chat with another user, the existing timeline should be shown instead
    - The `account_data.m.direct` must be used to check the pending DM chats with a given user (more details [here](https://spec.matrix.org/v1.6/client-server-api/#direct-messaging))
    -  Show the first room with the target user in the `account_data.m.direct` where the current user has the **join membership** (if any).

**APIs**
- [Create room](https://spec.matrix.org/v1.6/client-server-api/#creation)
- [Users' profiles](https://spec.matrix.org/v1.6/client-server-api/#profiles)

**Out of scope**
- ~Creating a 1:1 with an email will add the email to the `m.direct` dictionary of the account data. This email is then replaced with the `matrixId` when the user creates an account. This is currently done client side. -> should we keep this behaviour and will this be done in the rust sdk?~
- ~After creating a 1:1 with an email, when the user creates an account, there are then 3 members in the room (myUserId, the email address, the otherUserId) -> how to manage this?~
- ~When creating a DM (1:1 or group) including an email, the DM is **not** encrypted because the second user will not be able to decrypt messages sent before joining the room with the account. This should be solved by setting the history visibility to `shared` (currently, this is not supported on mobile clients)~
- ~Should we also support MSISDN invites?~

```[tasklist]
### Tasks
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1615
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1673
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1674
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1698
- [ ] https://github.com/vector-im/element-x-android/issues/96
- [ ] https://github.com/vector-im/element-x-ios/issues/595
```
