### ISSUE TITLE
MLS trial implementation in real client - WP2

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#1025]
## Work Package 2

This is an epic issue. List of individual issues is below:

Using the first dMLS core fork, we want to integrate it in a real client in order to demonstrate the functionality

**GOAL**: Have a sandbox to test out things, it will stay as a POC no UX development.

depends on WP1: https://github.com/vector-im/element-meta/issues/1022

```[tasklist]
## Linked Issues
- [ ] https://github.com/vector-im/element-meta/issues/1179
- [ ] https://github.com/vector-im/element-meta/issues/1180
- [ ] https://github.com/vector-im/element-meta/issues/1181
- [ ] https://github.com/vector-im/element-meta/issues/1182
- [ ] https://github.com/vector-im/element-meta/issues/1183
- [ ] https://github.com/vector-im/element-meta/issues/1184
```

## Deliverable

- Deployed web POC on some URL to test
