### ISSUE TITLE
[Story] Show read receipts

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1041]
As a user that has send a message I want to get an info if the message has been read to know my information has reached the receiver.

Userflow
Receiver
- When the receiver opens a room with unread messages mark all unread messages in the main timeline as "read".
- Mark all unread messages in Threads as read when the user has opened the Thread.
- If a receiver marks a room as "unread" don't mark messages as unread if they have been marked as read before.

Sender
- When the sender is looking at the messages he has send and they are marked as "read" on the receiver side - mark them as "read" on sender side, too.

Spec
https://spec.matrix.org/v1.6/client-server-api/#receipts

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/110
- [ ] https://github.com/vector-im/element-x-ios/issues/1052
- [ ] https://github.com/vector-im/element-x-ios/issues/1053
- [ ] https://github.com/vector-im/element-x-ios/issues/1381
- [ ] https://github.com/vector-im/element-x-ios/issues/2000
```

- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1808
```

- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion

##  Stretch goals
None at this time

## Out of scope
- Known issue: https://github.com/matrix-org/matrix-rust-sdk/issues/2889

**Comment by erkinalp** [comment]
>    When the receiver opens a room with unread messages mark all unread messages in the main timeline as "read".

Alternative: when the receiver moves the room timeline view to a point no earlier than event #Y in room #X for the first time, the room #X's fully read marker moves to event #Y. As the fully read marker cannot be ahead of the public read receipt by spec, the public mark shall move implicitly.
