### ISSUE TITLE
Accept or decline an invite from invitations' list

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-meta#1054]
As a user that has been invited to a new conversation I want to join a room to read messages & chat w. other users.
- I can accept / decline an invite

**Designs**
- [Invite list](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=700%3A77011&t=HQZi40ZlDTj6yUHA-1)

**ACs**
- When the user taps on "Accept" the client join the room calling one of the join API
    - After accepting (aka joining) the user should navigate to the new room opening the timeline
        - The timeline is pushed on top of the "Invites" screen
- When a user declines an invitation the client should call the "Leave" API instead
    - A full screen alert will ask for a confirmation before the user declines the invite
- An invite shouldn't be rendered in the "invites list" anymore after accepting/declining it
- In case of errors show a full screen alert
    - Title: "Error" (key `common_error`)
    - Message: "Sorry, an error occurred" (key `error_unknown`)
    - Button: "OK" (key `action_ok`) 

**Matrix APIs**

**Join** ([Rust PR](https://github.com/matrix-org/matrix-rust-sdk/pull/1776))
- [POST /_matrix/client/v3/join/{roomIdOrAlias}](https://spec.matrix.org/v1.6/client-server-api/#joining-rooms)
- [POST /_matrix/client/v3/rooms/{roomId}/join](https://spec.matrix.org/v1.6/client-server-api/#joining-rooms)

**Leave** ([Rust PR](https://github.com/matrix-org/matrix-rust-sdk/pull/1639))
- [POST /_matrix/client/v3/rooms/{roomId}/leave](https://spec.matrix.org/v1.6/client-server-api/#leaving-rooms)

```[tasklist]
### Tasks
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1676
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1653
- [ ] https://github.com/vector-im/element-x-android/issues/106
- [ ] https://github.com/vector-im/element-x-ios/issues/621
```
