### ISSUE TITLE
MLS Support | Milestone 3 Implement Matrix-flavor MLS

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#1060]
## Highlevel Overview

Matrix has some unique e2ee features that allows users to safely access encrypted history as well as recovery methods.
This piece of work consists of finding ways to provide similar functionalities with MLS.
The resulting “encryption stack” plus the decentralised nature of the group state results in a system different than MLS, a MLS matrix flavour, that would need to be specified and its crypto properties evaluated.

```[tasklist]
### Linked Epics
- [ ] https://github.com/vector-im/element-meta/issues/1451
- [ ] https://github.com/vector-im/element-meta/issues/1452
- [ ] https://github.com/vector-im/element-meta/issues/1809
```
