### ISSUE TITLE
[Epic] Offline mode: Caching & Queuing

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1101]
This Epic covers
- Caching data in the app
- Message resending (Queuing)

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*
```[tasklist]
### Tasklist
- [ ] Task 1
- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion
- [ ] https://github.com/vector-im/element-meta/issues/1414
- [ ] https://github.com/vector-im/element-meta/issues/1415
- [ ] https://github.com/vector-im/element-meta/issues/1415
```

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by manuroe** [comment]
The data optimisation logic is super interesting. We should apply it in other places. But can we start with a simple, skateboard, approach where we cache all rooms timelines as a first iteration and iterate from it?

I am scared by the complexity and its implementation. It will be useful for power users but for others, there will be more conditions to check than the actual number of rooms.

Note 1: We already cache the room list data. We need to consider the timeline now
Note 2: Media cache uses much more disk space

**Comment by VolkerJunginger** [comment]
I agree that we should start simple & iterate on that. Just wanted to leave this here up for discussion & inspiration.
