### ISSUE TITLE
Create a DM chat after the first message is sent

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-meta#1160]
DM rooms are created after the user send his first message.

**Designs**
- [Start a chat](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=636%3A76710&t=A81vpV4EtRiP1yDh-1)
- [Error](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1110%3A82068&t=A81vpV4EtRiP1yDh-1)
- [Retry](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1110-82228&t=A81vpV4EtRiP1yDh-0)

**ACs**
- The user doesn't start creating a room after he taps on a person he found during the process of creating a new DM chat
- The room is created after the user sends the first message
    - If the creation of the room fails, a message should be shown in the "timeline" under the message itself
        - Copy "Message failed to send" 
- Tapping on a failure CTA user can:
    - Send again the message (which retries the creation of the room)
    - Delete the message (which brings the room into the initial state) 
    - Dismiss the sheet

```[tasklist]
### Tasks
- [ ] https://github.com/vector-im/element-x-android/issues/237
- [ ] https://github.com/vector-im/element-x-ios/issues/713
```

- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion

**Questions**
- What if the scene is in the error state? Can the user send more messages?
- What we need to do after the creation of the room succeeded? I think it would be better to present the real timeline and send the first message there.

**Suggested implementation**
@Florian14

**Comment by Johennes** [comment]
Here is @Florian14's document outlining the problems to solve around deferred room creation: https://docs.google.com/document/d/11qSz8Gk2Be6tW9hcDLgVSQgW05o8qYXBJs9w9wYr_34/edit

There's currently still disagreement about what side to handle draft rooms / fake timelines on.
