### ISSUE TITLE
Update room's avatar/name/topic from room's detail

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-meta#1165]
As a user having the appropriate permissions (aka. power level) in the room I want to be able to change the room's avatar so that I can personalize it.

**Designs**
- [Change avatar](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1056-77958&t=I58RGk3eFIobEKPz-0)

**Matrix APIs**
- [State event](https://spec.matrix.org/v1.6/client-server-api/#put_matrixclientv3roomsroomidstateeventtypestatekey) (Rust [upload_avatar](https://github.com/matrix-org/matrix-rust-sdk/pull/1654/files#diff-4c791c6fb6203dbacab7e174f7ce093321d963891881abc33fcc06bd4a033cd6R562), [remove_avatar](https://github.com/matrix-org/matrix-rust-sdk/pull/1654/files#diff-4c791c6fb6203dbacab7e174f7ce093321d963891881abc33fcc06bd4a033cd6R577))
- [Power levels](https://spec.matrix.org/v1.6/client-server-api/#mroompower_levels) ([Rust implementation](https://github.com/matrix-org/matrix-rust-sdk/blob/9ee2d04a41fe17e38d93b6a61d9644acc89570d7/crates/matrix-sdk-base/src/rooms/members.rs#L110))

**ACs**

- On the room details screen:
  - A tap on the edit button opens a modal screen where the user can edit room's info.
      - The edit button should be visible only when the user can change **at least one** of following: name, topic, avatar 
    - If there is no topic set and the user can change the topic, an "Add topic" button is shown
      - Clicking on the "Add topic" opens the edit modal screen, the same as the edit button
- Users with the required power levels can change room's name or topic, otherwise they are read only.
- Users with the required power levels can tap on the avatar to change it
    - Users not having the permission do **not** see the camera icon on top of the room's avatar
- Tapping on the room's avatar open a system sheet
    - Taps do nothing for user without the required power levels  
- The sheet has four options:
    - Take a photo with camera (integration of the flow we already have when "creating a room") 
    - Choose a photo from camera roll (integration of the flow we already have when "creating a room") 
    - Remove the current avatar photo
    - Cancel: just dismisses the sheet
- After the process of selecting a photo from camera or camera roll ends, the photo shows on the UI
- The save button is enabled just when something changed in the edit screen (name or topic or avatar)
- A tap on the save button actually triggers the update of the avatar/name/topic on the home server.
    - Only what has changed must be saved 
- A full screen loader shown during the update of room's settings:
   - Copy during the update: "Updating room..."   
- Error handling: if either the upload or the set of the avatar fail a full screen alert should appear.
    - [Design](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=4431%3A182618&t=HwfbC7ELQx3fvJf1-1)
- The edit screen is automatically dismissed after a successful save.

**iOS Only**
- Consider to use the `MediaPickerCoordinator` introduced [here](https://github.com/vector-im/element-x-ios/pull/749).

```[tasklist]
### Tasks
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1693
- [ ] https://github.com/vector-im/element-x-android/issues/242
- [ ] https://github.com/vector-im/element-x-ios/issues/720
```

**Comment by Florian14** [comment]
@alfogrillo We should reconsider the ACs:
- The avatar update is now in a dedicated room details edition screen
- There are also the room name and topic on that screen
- We should consider the power level for each property (or for the entire screen access)
- The loading and error wordings should be changed in consideration: 
    - `Updating room...` for the global update
    - I suggest `An error occurred when updating the room details` for the error
- We should manage the case where some properties have been updated but not the others (do not trigger again the update of those which have succeeded)
