### ISSUE TITLE
Invite people from room's detail

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-meta#1166]
As a user having the appropriate permissions (aka. power level) in the room I want to be able to invite more people in the room

**Designs**
- [Invite more people](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=2042%3A102560&t=UJcDriNeWKKat3rI-1)
- [Error](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=2042-104144&t=EmSjfIylqSJ0R2Mt-0)

**Matrix APIs**
- [Invite](https://spec.matrix.org/v1.6/client-server-api/#post_matrixclientv3roomsroomidinvite)
- [Power levels](https://spec.matrix.org/v1.6/client-server-api/#mroompower_levels) ([Rust implementation](https://github.com/matrix-org/matrix-rust-sdk/blob/9ee2d04a41fe17e38d93b6a61d9644acc89570d7/crates/matrix-sdk-base/src/rooms/members.rs#L110))

**ACs**
- User can start the selection of new people from two places
    - In the room's detail there is a new row "Invite people"
    - In the people list there is a new button in the navigation bar to "Invite" new people
- The two new CTAs are visible just for user having enough power level (they should be hidden otherwise)
- Both the CTAs bring the user to a flow to select member to invite (similarly to the one we have when creating a new room)
- If a profile showed in the list is already invited or is a room member:
     - It shows with a full checkmark and is **not** selectable
     - The subtitle shows "Already a member" or "Already invited" instead of the user's id
- Tapping on the "Send" button triggers the send of invitations.
    - The modal is immediately dismissed without showing any loader
- In case of errors the user sees an alert wherever he's when the invite process errored (see copies in the design)

```[tasklist]
### Tasks
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1693
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1623
- [ ] https://github.com/vector-im/element-x-android/issues/245
- [ ] https://github.com/vector-im/element-x-ios/issues/724
```
