### ISSUE TITLE
Improve user search results calling the "profile" API

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-meta#1172]
As a user I want to see the display name and avatar of user whenever they are available.

**Designs**
- [Search user](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=1141%3A80001&t=RdTQaPvVqGm6HoVw-1)

**Problem**
Sometimes the "search user" API may not return back a user's profile even when providing an existing matrix id. 
This often happens when the searcher doesn't share any room with the searched user yet. In these cases calling the [profile](https://spec.matrix.org/v1.6/client-server-api/#get_matrixclientv3profileuserid) API helps since it may return back user's profile info.

**Matrix API**
- [Get profile](https://spec.matrix.org/v1.6/client-server-api/#profiles)

**ACs**
When the search query is a **matrix id**:
- the client always shows it as a **local** search result (local means not returned explicitly by the home server).
- the client also calls the profile api to get the display name / avatar for the search query
    - if any result is available, the client shows the avatar / display name for the local search result
    - otherwise an exclamation mark button shows on the right of the display name (see the design)
    - A tap on the above button will show an informational bubble (system platform popovers should be preferred to show this info)
- if the [search user](https://spec.matrix.org/v1.6/client-server-api/#post_matrixclientv3user_directorysearch) API returns results, they are show below the local result in the same section (as if they were all coming from the server)
- filter out the local result from the list coming from the server (if any)
    -  Example: if I searched `@a:b.com` clients should show it as a local in the first position and should filter out the same occurrence of `@a:b.com` from the server

```[tasklist]
### Tasks
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/1700
- [ ] https://github.com/vector-im/element-x-android/issues/254
- [ ] https://github.com/vector-im/element-x-ios/issues/729
- [ ] https://github.com/vector-im/element-x-android/issues/424
```
