### ISSUE TITLE
Mobile FTUE: Email collect & Verify (meta)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#129]
- [x] https://github.com/vector-im/element-android/issues/5278
- [x] https://github.com/vector-im/element-ios/issues/5649

The collect and verify email screens need updating. This is to bring them inline with our new design voice but also to give personality and flair to the onboarding flow as many users (in UserTesting) noted how dry the flow is.... As providing email is something easy to grok for all users, it's an area we can inject some colour and feedback (by way of confirmation screen).

<img width="536" alt="Screenshot 2022-02-16 at 15 23 29" src="https://user-images.githubusercontent.com/89144281/154297028-fca7d217-7eb0-402b-b572-929b1cb45e6e.png">

We also need to address the emails sent by the server as we have had negative feedback about those. These are handled by the backend team and that issue can be found here: 
- [ ] https://github.com/matrix-org/synapse/issues/9234

**Comment by daniellekirkwood** [comment]
@amshakal assigning to you as we need some input on the emails sent out by the server. I think another member of the design team is looking at emails so maybe we loop some others in to help?

**Comment by daniellekirkwood** [comment]
https://github.com/vector-im/element-android/issues/5278	
https://github.com/vector-im/element-ios/issues/5649

**Comment by daniellekirkwood** [comment]
The Synapse issue to fix the emails is a V2 issue and therefore this meta issue can be closed.
