### ISSUE TITLE
[Epic] Message Reactions

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#1357]
## Scope

```[tasklist]
### User Stories
- [ ] https://github.com/vector-im/element-meta/issues/1067
- [ ] https://github.com/vector-im/element-meta/issues/1163
- [ ] https://github.com/vector-im/element-meta/issues/1299
```

## Out of scope

- Nothing at the moment

## Tasks 

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/2125
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/2126
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2132
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2123
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2166
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2153
```

```[tasklist]
### Android
- [ ] Design sign-off on completion
- [x] QA sign-off on completion
- [ ] Product sign-off on completion
```

```[tasklist]
### iOS
- [ ] Design sign-off on completion
- [x] QA sign-off on completion
- [ ] Product sign-off on completion
- [ ] https://github.com/vector-im/element-x-ios/issues/1146
```

## Internal references

[Technical lead](https://gitlab.matrix.org/new-vector/internal/-/wikis/Departments/Engineering/Engineering-Roles#project-technical-lead): TBD

Time sheeting project: Element X

**Comment by kittykat** [comment]
Closing as all components have had design and product signoff
