### ISSUE TITLE
MLS external commits support. WP3

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-meta#1451]
## Work Package 3

This is an epic issue. List of individual issues is below:

WP2 only allows device to send a message after an existing member has added it to the group.  External commits allow a device to add themselves to the group (using the publicly-available group information) so that they can send a message without waiting to be added.

GOAL: Video demo, update PR

depends on WP2: #1025

```[tasklist]
## Linked Issues
- [ ] https://github.com/vector-im/element-meta/issues/1456
- [ ] https://github.com/vector-im/element-meta/issues/1457
- [ ] https://github.com/vector-im/element-meta/issues/1458
- [ ] https://github.com/vector-im/element-meta/issues/1459
```

## Deliverable

- video demo

**Comment by uhoreg** [comment]
video demo: https://drive.google.com/file/d/1uAuj7j9Dw4SoyPG9lmKzbtiATX1exeZc/view?usp=sharing
https://element-mls-proof-of-concept.netlify.app/ has been updated

**Comment by uhoreg** [comment]
video demo has been updated to a version with sound
