### ISSUE TITLE
MLS Chat History support (Backup, ~~gossip~~, re-decryption?) WPD: Demo

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-meta#1452]
## Work Package 4

This is an epic issue.  List the individual issues below:

MLS does not have any support for decrypting historical messages, either on newly-logged-in devices, or re-decrypting messages, and in fact, tries to prevent it, for security reasons.  However, users expect to be able to decrypt historical messages.  This work package is about enabling this capability.

Goal: Video demo, update PR

```[tasklist]
## Linked Issues
- [ ] https://github.com/vector-im/element-meta/issues/1686
- [ ] https://github.com/vector-im/element-meta/issues/1687
- [ ] https://github.com/vector-im/element-meta/issues/1692
- [ ] https://github.com/vector-im/element-meta/issues/1787
- [ ] https://github.com/vector-im/element-meta/issues/1788
- [ ] https://github.com/vector-im/element-meta/issues/1789
- [ ] https://github.com/vector-im/element-meta/issues/1790
- [ ] https://github.com/vector-im/element-meta/issues/1791
- [ ] support backfilling epochs from gappy sync in js-sdk?
- [ ] https://github.com/vector-im/element-meta/issues/1793
```

## Deliverable

- video demo
