### ISSUE TITLE
Meta-issue: Discordification of Matrix/Synapse/Dendrites (feature request)

### ISSUE THREAD

**Issue by DonaldTsang** [vector-im/element-meta#1476]

**Comment by skylord123** [comment]
@DonaldTsang I've been using Jitsi for voice calling my wife and it works like a charm on mobile. They will be adding push-to-talk to riot soon as well ( vector-im/element-web#5993 ). So I think it's fine.

**Comment by nathanfranke** [comment]
Rooms that are part of a community shouldn't show in the Rooms dropdown if the community isn't selected.

Edit: This was implemented in https://github.com/matrix-org/matrix-react-sdk/pull/6497

**Comment by trosel** [comment]
@squarepupil A "room of rooms" would be a house. Call them Houses 🏡 😄 

Each House can have one or many rooms. This is something my grandma could understand.

@SimmyD I know mumble is super high quality and efficient, but the requirement of centralization on mumble is definitely a downside. Kind of antithetical to what matrix is trying to do. 

Something like the original Skype where there is multi-casting going on in the audio room would be ideal. I know Jitsi is like a matrix partner right now, but something more in the direction of [meething](https://github.com/meething/meething) may be better still

**Comment by acoollevel** [comment]
Should the ability to create private communities be added to this list? vector-im/element-web#12658
It's a pretty important feature in Discord, and I feel like if people see the message "Warning: any person you add to a community will be publicly visible to anyone who knows the community ID" they will be less likely to switch.

**Comment by heylix** [comment]
> > > clicking a user's username makes a mention to their username appear in the chatbox, i expect their profile to pop up
> > 
> > Click on the avatar
> 
> Even so, that is a discrepancy between user expectancy and actuality (**coming from discord**: clicking username == profile popup), plus different reactions even though you'll be clicking on the same "thing" (user avatar and username could be considered the same "thing" in my head that way), also the fact that clicking on a user's avatar has a different reaction **wasn't noted anywhere**, and so I assumed that "clicking on a user in chat" will produce a mention as the law of the land, that is bad UX then, if a user cannot figure out usage from contextual clues if no explicit mention or tutorial is given

So what you're really saying is that documentation and UI hints for onboarding are lacking. The problem is not that it works in a different way, but that users are accustomed to that. For me it's more intuitive that if I click on a name it appears in the chat as mention, as it worked in IRC.

For me it's logical: If you want to know more about a user, click on the representation of the user (their avatar). If you want to talk to the user, click on their name. It's analogous to conversations in real life: You recognise someone by their face or likeness and you talk to them by using their name which you might know from a name tag which is attached to the person.

I think the current behaviour is fine. If it's not, there's a possibility for someone to develop a Discord "skin" or "theme" for Riot which works differently – but I think the standard behaviour shouldn't be changed. Consistency in user experience is important and if we'd change things without thinking about the implications for current users, just because Discord or Slack are doing it differently, we'll be in a bad place.

"Good UX" is not "doing everything like other apps". If it were, we wouldn't have any evolution of UX.

**Comment by MyriaCore** [comment]
@DonaldTsang would you mind changing the issue description as discussed above?

<details>
<summary>atm you have this:</summary>

> * [ ]  Room feature support
>   * [ ]  Custom server-based and room-based emojis
>     * Have custom server emojis downloaded and be usable as a basic feature
>   * [ ]  Emoji collection sharing
>     * Similar to Telegram, Messenger, LINE and Whatsapp, but shareable and if possible, self-hosted or user-hosted
>   * [ ]  Emoji reaction for texts and files (useful for voting)
>   * [ ]  Automated (non-manual) key sharing
>     * Some people are sick of needing to sharing key every time someone gets in the room, they would like to have auto key sharing once in an E2E room
>   * [ ]  Multi-room search
> * [ ]  Community support
>   * [x]  Community id generation
>   * [ ]  Community room mass generation
>   * [x]  Community room searching
>   * [ ]  Community multi-admin multi-mod support
>   * [ ]  Community and sub-community sort
> * [ ]  Role and access support
>   * [ ]  Mass room invitation by role or community
>     * invitation to a server once application is approved
>   * [ ]  Mass room banning/kicking by role or community
>     * for when "unfavorable" behavior by certain users happen
>   * [ ]  Community room sub-categorization and access
>     * for visitor vs club member vs club staff separation
>   * [ ]  Role application and removal
>     * for upgrading users to automatically bring them to certain rooms
>   * [ ]  Announcement rooms by role
>     * rooms that allows viewing but not posting unless it is staff
>   * [ ]  Reaction allowance by role
>     * for voting by certain role but not others
> * [ ]  audio chat support
>   * [ ]  self-host SIP room support (tying SIP with server)
>   * [ ]  self-host  Mumble room support (tying Mumble with server)
>   * [ ]  Radio/Playlist bot support
> * [ ]  collaborative support
>   * [ ]  self-host Etherpad/Firepad support (tying *pad with server)
>   * [ ]  self-host Hackmd support (tying Hackmd with server)
</details>



<details>
<summary>But as of the time of writing, I feel this would be more appropriate:</summary>

* [ ]  Room feature support
  * [ ]  Custom server-based and room-based emojis
    * Proposed by [[MSC2545](https://github.com/matrix-org/matrix-doc/pull/2545)]
  * [ ]  Emoji collection sharing
    * Similar to Telegram, Messenger, LINE and Whatsapp, but shareable and if possible, self-hosted or user-hosted
  * [x]  Emoji reaction for texts and files (useful for voting)
  * [ ]  Automated (non-manual) key sharing
    * Some people are sick of needing to sharing key every time someone gets in the room, they would like to have auto key sharing once in an E2E room
  * [x]  Multi-room search
* [ ]  Community support
  * Element's "Communities" are actually an undocumented matrix feature called [groups](https://github.com/matrix-org/matrix-doc/issues/971), which happens to use a quite [jankey API](https://github.com/matrix-org/matrix-doc/blob/ff85e61be908f4f5f0ba846da0dd6c439147a1b0/proposals/1772-groups-as-rooms.md#appendix-problems-with-the-r0groups-api). [[MSC1772](https://github.com/matrix-org/matrix-doc/pull/1772)] proposes that the we refactor the jank a bit to make groups easier to work with.
  * [This issue](https://github.com/vector-im/element-web/issues/15930) proposes that element.io's client should support MSC1772, instead of using the undocumented groups API
  * [x]  Community id generation
  * [ ]  Community room mass generation
  * [x]  Community room searching
  * [ ]  Community multi-admin multi-mod support
  * [ ]  Community and sub-community sort
* [ ]  Role and access support
  * [ ]  Mass room invitation by role or community
    * invitation to a server once application is approved
  * [ ]  Mass room banning/kicking by role or community
    * for when "unfavorable" behavior by certain users happen
  * [ ]  Community room sub-categorization and access
    * for visitor vs club member vs club staff separation
  * [ ]  Role application and removal
    * for upgrading users to automatically bring them to certain rooms
  * [ ]  Announcement rooms by role
    * rooms that allows viewing but not posting unless it is staff
  * [ ]  Reaction allowance by role
    * for voting by certain role but not others
* [ ]  audio chat support
  * See matrix-org/matrix-doc#2903 for first-class "voice/video rooms".
  * See [this Proof of Concept implementation](https://github.com/matrix-org/matrix-react-sdk/pull/4400) for voice room / voice channel UI in the matrix react sdk
  * [ ]  self-host SIP room support (tying SIP with server)
  * [ ]  self-host  Mumble room support (tying Mumble with server)
  * [ ]  Radio/Playlist bot support
* [ ]  collaborative support
  * [ ]  self-host Etherpad/Firepad support (tying *pad with server)
  * [ ]  self-host Hackmd support (tying Hackmd with server)
</details>

**Comment by Jieiku** [comment]
> msc2545 implementation would be nice

What is msc2545?

**Comment by natrius** [comment]
I think https://github.com/matrix-org/matrix-spec-proposals/pull/2545 is meant. On the other hand, mumble is currently rewriting its core (i think) and it should be easier to implement this afterwards. https://github.com/mumble-voip/ 
Voice-Channels would should have priority above sticker packs :)

**Comment by prabhathc** [comment]
Hey all, is it possible to also consider the deafen feature? Deafen mutes the user's audio output and mutes all incoming audio from group calls just for the deafened user, convenient feature that should be straightforward to add.

**Comment by heyakyra** [comment]
https://github.com/vector-im/element-call/issues/223 and https://github.com/vector-im/element-call/issues/174 would be nice extensions to the now-merged https://github.com/matrix-org/matrix-spec/issues/730

**Comment by emidoots** [comment]
Could "Increase vertical density of new room list vector-im/element-web#14099" be added to this meta-issue? I think this is one big drawback compared to Discord's UX right now.

Compare the visual density of Element:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/3173176/177220414-ae5b56cc-a304-45d1-aeba-5b1b70e38f09.png">

vs. a similar Discord channel organization capabilities:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/3173176/177220443-697bcc49-8f67-4254-b705-20cd28869d5d.png">

**Comment by erkinalp** [comment]
Well, Discord is also adding a few ideas from Element, for example, the ability to selectively hide guild channels.

**Comment by kittykat** [comment]
Moving this issue to discussions in Element meta as we need to make a cross platform decision on how to proceed :+1:

**Comment by 42willow** [comment]
I personally prefer the way element is structured, but permissions that are for all the rooms in a space would be great.

**Comment by Icy-Thought** [comment]
Tag based pings would be wonderful to have. We have recently been flooded with scammers and tagging individual moderators has become a daunting task. Please re-consider adding this feature.

**Comment by heyakyra** [comment]
Could @DonaldTsang update the list of items and move the completed ones towards the bottom of their respective sections? 

It hasn't been mentioned yet, but Discord supports 'forum channels', which are "[Zulip/Twist-style](https://zulip.com/why-zulip/#zulips-unique-topic-based-threading-model-makes-efficient-communication-possible-heres-how)" [per-room threading modes](https://github.com/element-hq/element-web/issues/21990#issuecomment-1113010993). This is covered by tickets https://github.com/element-hq/element-meta/issues/209, https://github.com/element-hq/element-meta/issues/334, https://github.com/element-hq/element-meta/issues/271 which are still waiting to be implemented, lacking an enterprise customer that can sponsor the development. 

Discussion topic: https://github.com/element-hq/element-meta/discussions/3016

_Note: Unsure if "[threads 2.0](https://github.com/element-hq/element-x-android/issues/2831#issuecomment-2714254482)" (partially) paves the way for any of that. According to [this comment](https://github.com/element-hq/element-web/issues/2349#issuecomment-554011591), we need [label-based filtering](https://github.com/matrix-org/matrix-spec-proposals/pull/2326) for it._ 

P.S. Also view-only mode and knocking/call-screening i mentioned above: https://github.com/element-hq/element-meta/issues/1476#issuecomment-1521895966 should go on the updated list

**Comment by erkinalp** [comment]
forum channels would map to "threads as rooms", requiring no spec work but a slight client UX change (nicely displaying arbitrary child room events in the timeline for rooms without `m.space`)

**Comment by Mathias-g** [comment]
<img width="592" height="800" alt="Image" src="https://github.com/user-attachments/assets/faaa5110-1924-4195-aa32-1fe2b5ada993" />
