### ISSUE TITLE
[Epic] Location sharing

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-meta#1525]
# Open questions

```[tasklist]
### ❓
```

# Size estimate

* 2x S
* 6x M
* 1x L

# Scope

```[tasklist]
### User stories
- [ ] https://github.com/vector-im/element-meta/issues/1684
- [ ] https://github.com/vector-im/element-meta/issues/1674
- [ ] https://github.com/vector-im/element-meta/issues/1675
- [ ] https://github.com/vector-im/element-meta/issues/1677
- [ ] https://github.com/vector-im/element-meta/issues/1678
- [ ] https://github.com/vector-im/element-meta/issues/1682
- [ ] https://github.com/vector-im/element-meta/issues/1815
- [ ] https://github.com/vector-im/element-meta/issues/1683
- [ ] https://github.com/vector-im/element-meta/issues/1722
```

### Related issues
- [x] https://github.com/vector-im/element-x-ios/issues/526

# Out of scope

- Live location sharing

# Terminology

- **Sending map view**: The map view / dialog shown when you initiate location sharing from the message composer
  - Except for the overall project name, we reserve "sharing a location" for the OS-level functionality to share data to other apps
- **Expanded map view**: The large map view that is opened from location events in the timeline
- **Pin drop**: Sending an arbitrary static location that is different from your own
- **Location button**: The (usually crosshair-like) button commonly used to show your own location on a map

# References

- [Technical lead](https://gitlab.matrix.org/new-vector/internal/-/wikis/Departments/Engineering/Engineering-Roles#project-technical-lead): none / @Johennes
- Times sheeting: `Element X`
- [2023-05-03 Kick-off](https://docs.google.com/presentation/d/1yWoyTaA_9spFDTCYNg2hnlH7c8wGVKbOj1uckQFU9xc/edit#slide=id.gbc48777987_0_0)
- [2023-05-16 Story slicing & sizing](https://docs.google.com/document/d/1pfAmaQRQFGflWCPbh4BLkpNZEPHKnDHK7VhEvd94M6Q/edit#heading=h.gtlhn9asfygb)
- [Designs](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=3053-135402&t=BEzYZSDuqsNo8WDv-0)
- [MSC3488: Extending events with location data](https://github.com/matrix-org/matrix-spec-proposals/pull/3488)
