### ISSUE TITLE
[Epic] Polls - phase 1

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-meta#1526]
# Open questions

```[tasklist]
### ❓
- [ ] Rust: Accept end events only from the poll creator and users who have powers to redact
```

# Size estimate

* 0x S
* 3x M
* 1x L

# Scope

```[tasklist]
### User Stories
- [ ] https://github.com/vector-im/element-meta/issues/1827
- [ ] https://github.com/vector-im/element-meta/issues/1828
- [ ] https://github.com/vector-im/element-meta/issues/1829
- [ ] https://github.com/vector-im/element-meta/issues/1830
- [ ] https://github.com/vector-im/element-meta/issues/1974
- [ ] https://github.com/vector-im/element-meta/issues/2014
- [ ] https://github.com/vector-im/element-meta/issues/2021
- [ ] https://github.com/vector-im/element-meta/issues/2022
- [ ] https://github.com/vector-im/element-meta/issues/2048
- [ ] https://github.com/vector-im/element-meta/issues/2049
- [ ] https://github.com/vector-im/element-meta/issues/2071
```

# Out of scope

- Nothing

# Terminology

- **Disclosed polls**: In the context of the [MSC](https://github.com/matrix-org/matrix-spec-proposals/pull/3381) defines polls where the current results are shown to users while the poll is still open
- **Undisclosed polls**: In the context of the [MSC](https://github.com/matrix-org/matrix-spec-proposals/pull/3381) defines polls where the results are only shown to users once the poll was closed
- **Open polls**: Used in the current Element apps. The same thing as "disclosed polls" in the [MSC](https://github.com/matrix-org/matrix-spec-proposals/pull/3381).
- **Closed polls**: Used in the current Element apps. The same thing as "undisclosed polls" in the [MSC](https://github.com/matrix-org/matrix-spec-proposals/pull/3381).

# References

* [Technical lead](https://gitlab.matrix.org/new-vector/internal/-/wikis/Departments/Engineering/Engineering-Roles#project-technical-lead): @julioromano 
* Times sheeting: `Element X`
* MSC: https://github.com/matrix-org/matrix-spec-proposals/pull/3381
* FigJam: https://www.figma.com/file/8bsgS77yqIL3ozyQ4mAqZp/EX-Polls?type=whiteboard&node-id=0%3A1&t=XQKTbtOB3B9p1de1-1
* PRD for original implementation: https://docs.google.com/document/d/1e7L6QoanhJIo81bj2PEFnAPRw10uObKXVPzcei1pTQ4/edit
* New PRD: https://docs.google.com/document/d/1Fhpe6Wj_fwGAxtb46KXVud8W8MkhTmke6zC9gL-aYmE/edit
* Phase 2 https://github.com/vector-im/element-meta/issues/2020

**Comment by Johennes** [comment]
Element clients are currently implementing "v1" of the polls MSC: https://github.com/matrix-org/matrix-spec-proposals/blob/95fdc44b904d2b4d2f227db99050e539e43f3509/proposals/3381-polls.md

If we want to maintain backwards compatibility, we'll need to implement the same version on EX.

CC @julioromano
