### ISSUE TITLE
Review and update Spaces IA for cross-platform consistency

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#164]
We want to use the same strings and have same (within the confines of prioritising platform-specific behaviours) IA for Spaces on all platforms, but especially so for iOS and Android. The work for this issue should be based off [IA figma](https://www.figma.com/file/NdyVNd8OSVbcPMNSqCDKfY/%5BIA-map%5D-Mobile?node-id=0%3A1).

Things to look for:
- Interactions
- Strings

For this task to be complete, we needs to:

## Discovery tasks
- [x] As a team, review current designs

## Design tasks
- [x] vector-im/element-meta#178
- [x] vector-im/element-meta#181
- [x] vector-im/element-meta#184
- [x] https://github.com/vector-im/element-meta/issues/205
- [x] https://github.com/vector-im/element-meta/issues/206

## Development tasks
- [x] vector-im/element-ios#5747
- [x] vector-im/element-android#5334
- [x] vector-im/element-android#5346
- [x] vector-im/element-meta#185
- [x] vector-im/element-ios#5771
- [x] https://github.com/vector-im/element-android/issues/5486
- [x] https://github.com/vector-im/element-android/issues/5516
- [x] https://github.com/vector-im/element-ios/issues/5810
- [x] https://github.com/vector-im/element-android/issues/5524
- [x] vector-im/element-android#5658
- [x] vector-im/element-ios#4850
- [x] vector-im/element-android#5728

## Descoped
- [ ] vector-im/element-meta#179
- [ ] vector-im/element-meta#177

**Comment by kittykat** [comment]
Closing as all sub-issues have been resolved
