### ISSUE TITLE
[Story] View location in timeline

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-meta#1675]
* As a user
* I want to see location events in the timeline rendered as maps
* so that I can visualize where a location is

# Size estimate

M

# Dependencies

* https://github.com/vector-im/element-meta/issues/1684

# Designs

* https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?node-id=2408%3A115163&mode=dev

# Acceptance criteria

* When a message with a location fails to send, the usual timeline behaviour applies (timestamp becomes red with a warning sign next to it, and can be tapped to perform retry/cancel actions)
* Location events in the timeline are rendered as pins on a map view
* The map shows the map provider's copyright attribution
* The map is non-interactive
* Default zoom level: 15
* When rendering fails, a blurred map is shown with a retry prompt (see designs)
* If the geoURI can't be parsed, the message body is shown as text

# Out of scope

* Expanding the map – https://github.com/vector-im/element-meta/issues/1678
* Replying – https://github.com/vector-im/element-meta/issues/1677
* Redacting, forwarding, etc. – https://github.com/vector-im/internal-planning/issues/329
* Resending on failure – https://github.com/vector-im/internal-planning/issues/329
* Reacting – https://github.com/vector-im/element-meta/issues/1357
* View the `description` of location events – https://github.com/vector-im/element-meta/issues/1815

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

# Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/689
- [ ] https://github.com/vector-im/element-x-android/pull/933
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/1136
- [ ] https://github.com/vector-im/element-x-ios/pull/1355
- [ ] https://github.com/vector-im/element-x-ios/pull/1368
```

```[tasklist]
### Other
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2187
```

**Comment by alfogrillo** [comment]
@Johennes @callumu the zoom level on element was `15` happy to have the same here? LGTM.

**Comment by Johennes** [comment]
No concerns on my side. It might be best to just make a quick screenshot of what that would look like and post it into our demo room for Callum to look at.

**Comment by Johennes** [comment]
In the weekly today we agreed to remove the copy action from the contextual menu in the timeline. Copying the textual representation of a location is not very useful and is still possible via the system share functionality.

This story has already been reviewed but I think removing the copy action would probably be a very small fix. @alfogrillo do you think you could sneak it into this story after the fact?

On Android this seems to already be the case.

**Comment by alfogrillo** [comment]
> @alfogrillo do you think you could sneak it into this story after the fact?

@Johennes no problems at all. I'm raising a PR today.

Edit: [PR](https://github.com/vector-im/element-x-ios/pull/1355)

**Comment by callumu** [comment]
There is different behaviour when sending a map location with no signal or wifi depending on platform. 

Android:
![1000000805](https://github.com/vector-im/element-meta/assets/110109933/cbff8228-e900-4564-ab16-4320a45f400e)


iOS:
![IMG_8518](https://github.com/vector-im/element-meta/assets/110109933/99a59340-b643-4877-bdaa-65fdd85c8b71)

When selecting 'tap to load map' on iOS I get a random map location. 


As there is no signal or wifi, for both platforms I would expect to see a blurred map with the red error timestamp notifier that my location hasn't been able to be sent.

**Comment by alfogrillo** [comment]
> When selecting 'tap to load map' on iOS I get a random map location.

What do you mean by a "random" map location?

> As there is no signal or wifi, for both platforms I would expect to see a blurred map with the red error timestamp notifier that my location hasn't been able to be sent.

I think the rust sdk drives the error in the timeline. 
Maybe the sdk retries the network call several times before giving up and return us an error (which is showed as a red badge in the bubble).
Can you try waiting for a while to see if the red badge eventually comes?

**Comment by callumu** [comment]
> What do you mean by a "random" map location?

I should probably explain this better - with no wifi or signal I shared a location which didn't send -> 'tap to load map' was shown on a blurred map. When I had signal again and I pressed 'tap to load map' the map loaded and I was shown a London location which is about 10 miles away from where I am

> I think the rust sdk drives the error in the timeline. Maybe the sdk retries the network call several times before giving up and return us an error (which is showed as a red badge in the bubble). Can you try waiting for a while to see if the red badge eventually comes?

Okay I just tried this again. The red badge showed after a while and also 'tap to load map'. I don't think 'tap to load map' should show here as there is nothing to show as the sending failed. I pressed 'tap to load map' to see what would happen and the message just disappeared

**Comment by alfogrillo** [comment]
> When I had signal again and I pressed 'tap to load map' the map loaded and I was shown a London location which is about 10 miles away from where I am

This may be caused by a reduced localization accuracy of your device when the Wi-Fi off. 
Location services often use radio connections to refine the GPS signal.
So, I don't think this is an issue of EX.
Maybe you can try outdoor to see if it makes the difference.

> I don't think 'tap to load map' should show here as there is nothing to show as the sending failed.

Rendering the map in the timeline and sending the message are actually driven by two different servers:
- Rendering the map -> we use the map tiler API
- Sending the message -> we send to a matrix home server

 This is to say that sometimes you may be able to see a map in the timeline even if the actual message fails to be sent (maybe because of a temp issue on the homeserver). Actually we **always** show the map even before the message is sent thanks to the **local echo** feature. Hopefully this can clarify the app behavior.
 
 > I pressed 'tap to load map' to see what would happen and the message just disappeared
 
 This is weird. Does it happens all the time? Do you know if it happens on Element X Android as well.
 If so, maybe we should track it with a GH issue.
