### ISSUE TITLE
[Story] Reply to location

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-meta#1677]
* As a user
* I want to reply on a location event in the timeline
* so that I can refer to it in my message

# Size estimate

M

# Dependencies

* https://github.com/vector-im/element-meta/issues/1675

# Acceptance criteria

* When composing a reply, the location is rendered in the quote section
* Upon submitting the composer, the reply is sent
* The reply is rendered in the timeline including the quoted location

# Out of scope

* Navigate from quote to original event – https://github.com/vector-im/internal-planning/issues/365

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

# Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/728
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/1136
```

```[tasklist]
### Other
```

**Comment by alfogrillo** [comment]
> Tapping the quote section of a reply in the timeline jumps to the original event

EX doesn't have the jump to replied message in general.
People told me we need the rust support to do it properly.
So I think we should descope it from here.

fyi: @Johennes @VolkerJunginger

**Comment by Johennes** [comment]
Good call. I've moved it to the out-of-scope section.
