### ISSUE TITLE
[Story] View expanded map

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-meta#1678]
* As a user
* I want to expand a map view in the timeline
* so that I can inspect the surroundings of the location

# Size estimate

S

# Dependencies

* https://github.com/vector-im/element-meta/issues/1674
* https://github.com/vector-im/element-meta/issues/1675

# Acceptance criteria

* Tapping a map view in the timeline expands it
* The expanded map view shows the map provider's copyright attribution
* The expanded map view can be panned and zoomed
* Default zoom level: 15
* The share button opens the system sharing dialog for the location
* View the description of the location event (if it is not empty)
    * Show (if any) below the nav bar as in the design 
* Analytics tracking
  * When showing the sending map view
    *  Event: [`$screen`](https://github.com/matrix-org/matrix-analytics-events/blob/main/schemas/MobileScreen.json)
    * Property: `screenName = LocationView`

# Out of scope

* Location button – https://github.com/vector-im/element-meta/issues/1682

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

# Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/741
- [ ] https://github.com/vector-im/element-x-android/pull/916
- [ ] https://github.com/vector-im/element-x-android/pull/923
- [ ] https://github.com/vector-im/element-x-android/pull/933
- [ ] https://github.com/vector-im/element-x-android/pull/963
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/1182
- [ ] https://github.com/vector-im/element-x-ios/pull/1241
- [ ] https://github.com/vector-im/element-x-ios/pull/1354
```

```[tasklist]
### Other
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2187
```

**Comment by Johennes** [comment]
@julioromano in the review today we've found that the pin is too big in the expanded map and you said this might already be fixed. Could you verify that and if it is fix, set the Android status of this story to "Reviewed"?

**Comment by julioromano** [comment]
> 

It is fixed. But we're still missing on android this too https://github.com/vector-im/element-x-android/pull/916

**Comment by julioromano** [comment]
> > 
> 
> It is fixed. But we're still missing on android this too [vector-im/element-x-android#916](https://github.com/vector-im/element-x-android/pull/916)

It's now been merged but technically it's not been reviewed.

**Comment by Johennes** [comment]
Ok, thanks. I'll put this on the agenda for review again in the next weekly.
