### ISSUE TITLE
How should searching within a room work?

### ISSUE THREAD

**Issue by niquewoodhouse** [vector-im/element-meta#168]
Today, you can access room search on iOS and Android differently.  Both only search room unencrypted rooms, but don't include any warning or helpful information for users when searching encrypted rooms.

**Tasks**

- [ ] [Design] What's a good experience for searching a room's content
- [ ] [Android and iOS] Pair on feasibility of above + amend if required
- [ ] [iOS and Android] Identify constraints and such issues
- [ ] [Design] Deliver designs that we've agreed and aligned on

**Comment by daniellekirkwood** [comment]
Leaving this open and tagging as A-Search for when we take on Search as a project.

**Comment by daniellekirkwood** [comment]
Leaving this open and tagging as A-Search for when we take on Search as a project.
