### ISSUE TITLE
[Story] View maps in dark mode

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-meta#1683]
* As a user
* I want to use dark mode in map views
* so that the appearance matches with the rest of the app

# Size estimate

M

# Dependencies

* https://github.com/vector-im/element-meta/issues/1674
* https://github.com/vector-im/element-meta/issues/1675

# Acceptance criteria

* Dark/Light mode works on static images in the timeline
* Dark/Light mode works on the expanded map
* MapTiler dark/light styles can be hardcoded in the codebase

# Out of scope

* Nothing

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

# Subtasks

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

```[tasklist]
### Other
```

**Comment by alfogrillo** [comment]
@Johennes we are supporting the dark mode everywhere.
On EX-iOS's timeline it has been done [here](https://github.com/vector-im/element-x-ios/pull/1136) already. ;)

(URLs for dark/light styles are hardcoded ATM)

**Comment by Johennes** [comment]
Nice!

**Comment by julioromano** [comment]
Fixed the last bit on Android too https://github.com/vector-im/element-x-android/pull/766

**Comment by Johennes** [comment]
@julioromano nice! Can you set the Android status to done then?

**Comment by julioromano** [comment]
> @julioromano nice! Can you set the Android status to done then?

I should have now. Can you double check?

**Comment by Johennes** [comment]
Yes, looks good. 👍

![Screenshot 2023-07-05 at 08 38 05](https://github.com/vector-im/element-meta/assets/1137962/c28b4495-e911-4c8f-9ecd-3d6525e2094c)
