### ISSUE TITLE
[Story] Delete a message

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#1705]
As a user that has the power to delete a message I want to delete a message so that I can get rid of it.

In 1:1 chats
- A user can delete their own messages
- Optional: A user can delete = "hide" messages be the conversation partner

In group chats:
- A user can delete their own messages
- Admin or moderators can delete messages by others

## Scope
*These should be a list of technical tasks which take ½-1 day to complete*

```[tasklist]
### Tasks
- [ ] https://github.com/vector-im/element-x-ios/pull/1324
- [ ] https://github.com/vector-im/element-x-android/issues/969
```

```[tasklist]
### Signoff
- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion
- [ ] https://github.com/vector-im/element-x-ios/pull/1324
```

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
-

**Comment by ghost** [comment]
This doesn't seem complete. I can delete messages I have posted (1:1 or room) but as an Admin I cannot delete the messages of others. I can only "report" messages and block the user.

**Comment by manuroe** [comment]
@Velin92 can you check this on EIX to see if it is an app issue or a SDK issue, please?

**Comment by Velin92** [comment]
@manuroe Just checked is not an SDK issue, we just do not have implemented in the app yet a power level check to allow a user to delete messages that are not own messages.

However this might still require to expose on the FFI layer of the SDK some APIs to achieve this.

**Comment by manuroe** [comment]
An admin can delete a message in EIX now thanks to the SDK [PR](https://github.com/matrix-org/matrix-rust-sdk/pull/2279) and its usage in the app ([PR](https://github.com/vector-im/element-x-ios/pull/1324)).
