### ISSUE TITLE
[Story] Automatic send retries

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#1773]
As a user, I want my messages to be sent automatically as much as possible. If there are network problems, sending must be automatically retried once the network is back.
 
Question: 
- how much/long should we retry?

```[tasklist]
### Tasks for BBQ Release
- [x] Retry mechanism
- [x] Automatic classical exponential 3 times retries
```

```[tasklist]
### Tasks
- [ ] Automatic detection when network is back
```

- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion

##  Stretch goals
None at this time
<or add a tasklist>

## Out of scope
- Retry for media upload (EX does not need while the upload UX flow is blocking until the upload completes)

**Comment by manuroe** [comment]
Was done but we need to come back to it
