### ISSUE TITLE
MLS Spec Work WPD: Draft MSC

### ISSUE THREAD

**Issue by uhoreg** [vector-im/element-meta#1809]
```[tasklist]
### Tasks
- [ ] https://github.com/vector-im/element-meta/issues/1810
- [ ] https://github.com/vector-im/element-meta/issues/1811
- [ ] https://github.com/vector-im/element-meta/issues/1812
- [ ] https://github.com/vector-im/element-meta/issues/1813
- [ ] https://github.com/vector-im/element-meta/issues/1880
- [ ] https://github.com/vector-im/element-meta/issues/1881
- [ ] https://github.com/vector-im/element-meta/issues/1948
- [ ] https://github.com/vector-im/element-meta/issues/1949
```
