### ISSUE TITLE
[Story] View location description in timeline

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-meta#1815]
* As a user
* I want to see the description of a location event in the timeline if it is set
* so that I can better tell it apart from other locations

# Size estimate

S

# Dependencies

* https://github.com/vector-im/element-meta/issues/1675

# Designs

* https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=6389%3A199763&mode=dev

# Acceptance criteria

* View the `description` of the location event (if it is not empty)

# Out of scope

* View description in expanded map – https://github.com/vector-im/element-meta/issues/1678

# Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/pull/783
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/1236
```

```[tasklist]
### Other
```

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

**Comment by VolkerJunginger** [comment]
@kittykat no clue how to test that.

**Comment by callumu** [comment]
@kittykat I think this is only visible for specific clients so I echo Volker's comment above. Maybe one of the engineers can test this?

**Comment by kittykat** [comment]
@callumu I've linked Volker and Amsha to a suitable location share for testing, I'll forward it to you as well
