### ISSUE TITLE
[Prep] Bring back "v1" poll events in Ruma and the Rust SDK

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-meta#1827]
### Description

# Size estimate

M

# Dependencies

* None

# Acceptance criteria

* The poll start, response and end event types exist in Ruma (started in https://github.com/ruma/ruma/pull/1589)
* The event types are compatible with what's implemented in the old apps
* The Rust SDK depends on the version of Ruma that has the new event types

NB: Figure out how these ACs will be tested (we suspect ruma has unit tests but we're not sure right now).

# Out of scope

* Nothing

# Subtasks

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

```[tasklist]
### Other
- [x] Plumb through Ruma types in Rust SDK
- [x] Test parsing of events from Web/Legacy Android/Legacy iOS
- [ ] https://github.com/ruma/ruma/pull/1589
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2344
```
