### ISSUE TITLE
[Prep] Compute poll aggregation in Rust SDK

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-meta#1828]
### Description

# Size estimate

L

# Dependencies

* https://github.com/vector-im/element-meta/issues/1827

# Acceptance criteria

Acceptance criteria:

* The Rust SDK exposes a method that aggregates results for a given poll start / end event
* The aggregation does _not_ use the `/relations` API[^1] and instead aggregates sync'ed events only similar to how reactions are handled (see the skeleton in https://github.com/matrix-org/matrix-rust-sdk/compare/jplatte/polls-skel)
* The aggregation logic follows the MSC (e.g. in terms of accepted timestamps, last votes, etc.)
  * Responses later than the end time are discarded
  * Responses with too many options are truncated to the maximum number
  * Responses with invalid options are treated as spoiled (= voting for nothing)
  * Responses with no options are treated as spoiled (= voting for nothing)
  * Only the most recent response per-user (before the poll end time) is used

Unit Testing: Compute the aggregated state of a fake poll.

# Out of scope

* Expose aggregation result in Rust SDK timeline – https://github.com/vector-im/element-meta/issues/1829

# Subtasks

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

```[tasklist]
### Other
- [x] Keep track of all votes received for a poll
- [x] Implement a method to aggregate those votes
- [x] Handle spoiled votes -- no selection, or invalid selection
- [x] Handle too many selections -- truncate to maximum allowed
- [x] Handle late votes -- ignore if they're received after the end time
- [x] Edge case: handle receiving votes for polls we've not seen the start event for
- [x] Edge case: handle receiving close event for polls we've not seen the start event for
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2326
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2338
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2350
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2381
```

[^1]: To simplify the implementation, we initially rely on eventual consistency only – similar to how reactions are handled. This means that poll results will be incomplete in certain situations. However, the naive implementation can be follow up on later with an improvement that leverages the `/relations` API for accurate results.
