### ISSUE TITLE
[Prep] Expose aggregated poll start / end events in Rust SDK timeline

### ISSUE THREAD

**Issue by Johennes** [vector-im/element-meta#1829]
### Description

# Size estimate

M

# Dependencies

* https://github.com/vector-im/element-meta/issues/1828

# Acceptance criteria

* The result of the aggregation is published in the Rust SDK timeline (`matrix-sdk-ui::timeline`)
* The FFI layer uses new types that are mapped from the Ruma types
* Poll start and end events are both published in the timeline and in a way that clients can differentiate between them

# Out of scope

* Nothing

# Subtasks

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

```[tasklist]
### Other
- [x] Define new types in the UniFFI layer
- [x] Ensure start event contains aggregated results (so far, if disclosed)
- [x] Add tests for the aggregation logic
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2326
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2338
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2331
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2381
```

**Comment by julioromano** [comment]
In the end it was decided not to show end events in the timeline so the rust timeline doesn't expose them anymore.
