### ISSUE TITLE
Include development checklists in incoming issues for better status tracking

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#1864]
It is not easily visible when new issues (both defects and enhancement requests) are ready for development.

:tada: - for including definition in issue description
:rocket: - for bot comment

## Definition of ready:
As discussed in team sprint planning process doc, this covers all the points raised for defects:
```
 - [ ] Tagged as T-Defect, and with correct A-*, S-* and O-* labels
 - [ ] Can be reproduced from steps (see above)
 - [ ] Developer has acquired all needed info from issue author and issue is not labelled with X-Needs-Info
 - [ ] Design team has signed off on the feature:
   - [ ] does not need design input or
   - [ ] final design has been approved by the Element design team and attached to this issue: <link to design>
 - [ ] Acceptance criteria (in scope) have been clearly defined:
   - [ ] <replace this text with list of acceptance criteria>
 - [ ] Out of scope has been clearly defined:
   - [ ] <replace this text with list of what is outside the scope of this issue>
```

And enhancements:
```
 - [ ] Tagged as T-Enhancement and with correct A-* label
 - [ ] Product team confirmed that this feature:
   - [ ] …is on the roadmap or
   - [ ] …could be added to the roadmap or developed by a community member
 - [ ] Design team has signed off on the feature:
   - [ ] feature has no UI or
   - [ ] design has been finalised by the Element design team and attached to this issue: <link to design>
 - [ ] Acceptance criteria (in scope) have been clearly defined:
   - [ ] <replace this text with list of acceptance criteria>
 - [ ] Out of scope has been clearly defined:
   - [ ] <replace this text with list of what is outside the scope of this issue>
```

## How to do it
Set up a GitHub action to have the bot comment on the issue with a checklist.
