### ISSUE TITLE
[Prep] Get RTE SDK ready for integration in EX

### ISSUE THREAD

**Issue by langleyd** [vector-im/element-meta#1935]
### Description

# Size estimate

M

# Dependencies

* None

# Acceptance criteria

- The RTE SDK is ready to integrated in to EX to support the rich text mode

# Out of scope

* Nothing

# Subtasks

```[tasklist]
### Android
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/issues/315
- [x] [Android] Discovery: integration with EX
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/pull/787
```

```[tasklist]
### iOS
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/pull/742
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/pull/759
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/pull/761
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/pull/781
```

```[tasklist]
### Rust / Common
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/pull/745
```
