### ISSUE TITLE
[Story] RTE Plain/Markdown text mode on EX

### ISSUE THREAD

**Issue by langleyd** [vector-im/element-meta#1936]
### Description

* As a user
* I want to be able to able to enter plain text/markdown in the editor
* so that I can send simple messages to other room members

# Size estimate

M

# Dependencies

- https://github.com/vector-im/element-meta/issues/1935

# Acceptance criteria
- New option in developer settings
  - (default) When enabled, rich text formatting menu is available and markdown is disabled
  - When disabled, rich text formatting menu is not available and markdown is enabled
- When markdown is enabled (i.e. rich text formatting setting is disabled):
  - Plain text and markdown can be entered into the composer
  - The send button is enabled accordingly
  - Reply mode works
  - Editing a message works
    - When editing a message, the composer is populated with the plain text `body` of the original message
  - The message can be send and the formatting from the markdown is rendered correctly and message content sent is correctly formatted.
- Under the hood, the editor is always the Matrix Rich Text Editor (as opposed to a basic text field)

## Examples

| Feature flag state | User types | Expected `body` | Expected `formatted_body`|
|--------------------|------------|-----------------|--------------------------|
| Enabled  | `**Hello**`          | `**Hello**`     | `**Hello**` |
| Enabled  | `Hello`              | `Hello`         | `Hello` |
| Disabled | `**Hello**`          | `**Hello**`     | `<p><strong>Hello</strong></p>\n` |
| Disabled | `Hello`              | `Hello`         | undefined  |

## Technical details

| Feature flag state | Source of `body`  | Source of `formatted_body` |
|--------------------|-------------------|----------------------------|
| Enabled  | Output of RTE (from `getMessageMarkdown()`) | Output of RTE (from `getMessageHtml()`) |
| Disabled   | Output of RTE (from `getMessageMarkdown()`) | Generated by Matrix Rust SDK (from `messageEventContentFromMarkdown()` |

# Out of scope

- Mentions/Slash Commands

# Sign-off

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

# Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/pull/1289
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/1703
- [ ] https://github.com/vector-im/element-x-ios/pull/1742
```

```[tasklist]
### Other
```

**Comment by jonnyandrew** [comment]
~~Closing as not done (out of scope)~~
