### ISSUE TITLE
[Story] RTE Rich text mode on EX

### ISSUE THREAD

**Issue by langleyd** [vector-im/element-meta#1937]
### Description

* As a user 
* I want to format message content
* so that I can add structure to my longer messages.

# Size estimate

M

# Dependencies

- https://github.com/vector-im/element-meta/issues/1936

# Acceptance criteria

### Formatting buttons

Message content can be formatted with:
- Inline Formatting (Bold, Italic, underline, strikethrough, code)
- Lists(unordered and numbered)
- Blocks (Quotes, Codeblocks)

Hide and show formatting buttons
- Enable rich text formatting buttons from the action bottom sheet
- Quickly hide rich text formatting options with the X button

### Message output

When the user presses the send button, the app should send a message event with both: `formatted_body` containing the HTML output of the rich text editor and `body` containing the markdown formatted output of the rich text editor.
# Out of scope

- Mentions/Slash Commands
- Plain text / markdown
- Links (covered by #1975)

# Sign-off

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

# Subtasks

```[tasklist]
### Android
- [x] Replace current composer with rich text editor https://github.com/vector-im/element-x-android/pull/1172
- [ ] https://github.com/vector-im/element-x-android/pull/1261
- [x] Add error tracking
- [ ] https://github.com/vector-im/element-x-android/issues/1070
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/pull/796
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/1427
- [ ] https://github.com/vector-im/element-x-ios/pull/1464
- [ ] https://github.com/vector-im/element-x-ios/pull/1614
```

```[tasklist]
### Other
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2425
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2459
```

# Links
- [Kiwi test case](https://element.tenant.kiwitcms.org/case/806/)

**Comment by jonnyandrew** [comment]
@alfogrillo @langleyd I've pulled the error tracking requirement for iOS out of this story into a separate issue to be prioritised separately:
- https://github.com/vector-im/element-x-ios/issues/1695

**Comment by callumu** [comment]
iOS: code block and inline code colours need to be updated to the [designs](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=9623-138907&mode=design&t=aHxo5yqd7pilDZxc-4)

Android: there is still the border radius issue when moving from one line onto two lines. Code block spacing around the mono font is inaccurate in the composer. Code block and inline code colours are inconsistent in the composer vs on the timeline

**Comment by alfogrillo** [comment]
> iOS: code block and inline code colours need to be updated to the [designs](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=9623-138907&mode=design&t=aHxo5yqd7pilDZxc-4)

@callumu can you be more specific on this?
What's wrong? The background color looks in line with the design ("color gray 100")

**Comment by callumu** [comment]
> > iOS: code block and inline code colours need to be updated to the [designs](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=9623-138907&mode=design&t=aHxo5yqd7pilDZxc-4)
> 
> @callumu can you be more specific on this? What's wrong? The background color looks in line with the design ("color gray 100")

Sorry yes.

On dark mode the text colour for code blocks is the same colour as the background making the text impossible to see.

I also wanted to note that we discussed the difficulty getting inline code and code blocks to match the designs , and it's something to work on when there is more time.

**Comment by callumu** [comment]
I also noticed on Android that the mono font text size is different for code blocks vs inline code

**Comment by callumu** [comment]
I think the code block colour error is a bug:


https://github.com/vector-im/element-meta/assets/110109933/4ad844b1-8c5b-4569-a684-648e19dd2011

**Comment by alfogrillo** [comment]
> On dark mode the text colour for code blocks is the same colour as the background making the text impossible to see.

Just for the record: this seems not to be a color issue, but a bug on the RTE.
Notice how the color changes while typing (especially on new lines).


https://github.com/vector-im/element-meta/assets/19324622/0b6e5ff4-b957-48b1-adf1-0e806fd747b1

**Comment by alfogrillo** [comment]
> I think the code block colour error is a bug:

You found the same problem! 😄

**Comment by kittykat** [comment]
Any outstanding tasks will be added to https://github.com/vector-im/element-x-ios/issues/1702
