### ISSUE TITLE
[Epic] RTE on EX

### ISSUE THREAD

**Issue by langleyd** [vector-im/element-meta#1940]
# Open questions

```[tasklist]
### ❓
- [x] Do we support Markdown in plain text mode? (yes, plain text mode is in scope)
- [ ] https://github.com/vector-im/element-x-android/issues/85
```

# Size estimate

* 0x S
* 4x M
* 0x L

# Scope

```[tasklist]
### User Stories
- [ ] https://github.com/vector-im/element-meta/issues/1935
- [ ] https://github.com/vector-im/element-meta/issues/1937
- [ ] https://github.com/vector-im/element-meta/issues/1975
- [ ] https://github.com/vector-im/element-meta/issues/1936
- [ ] https://github.com/vector-im/element-meta/issues/1973
```

```[tasklist]
### Bugs / polish
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/issues/799
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/pull/798
- [ ] https://github.com/vector-im/element-x-android/issues/1315
- [ ] https://github.com/vector-im/element-x-ios/issues/1702
- [ ] https://github.com/vector-im/element-x-android/issues/1259
- [ ] https://github.com/vector-im/element-x-ios/issues/1672
- [ ] https://github.com/vector-im/element-x-ios/issues/1674
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/issues/832
- [ ] https://github.com/vector-im/element-x-ios/issues/1673
- [ ] https://github.com/vector-im/element-x-ios/issues/1671
- [ ] https://github.com/vector-im/element-x-android/issues/1293
```

# Out of scope

- Mentions/Slash Commands

# Terminology

- **RTE**: Rich Text Editor
- **Plain text mode**: The editor when the formatting options are disabled (which also supports Markdown).
- **Rich text mode**: The editor when the formatting options are enabled (regardless of whether shown) that shows the formatting directly (WYSIWYG - "What you see is what you get") in the editor

# References

* Times sheeting: `Element X`

**Comment by kittykat** [comment]
We are happy with the implementation for now, we need to fix the two outstanding issues after the October release as part of the polish on HTML handling
