### ISSUE TITLE
[Prep] EC in EX: Discovery - Can we use Element Call within a web view?

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#1953]
### Description

We need to ensure that we have all the expected behavior and controls of VoIP features when running it into a web view.

# Size estimate

S

# Dependencies

* None

# Acceptance criteria

* Permissions are asked as expected (Camera & Mic)
* Call is still up and running when the app goes in background
* Call is still up and running when the device is locked

# Out of scope

* Mute the mic when the app is in bg or device locked
* Terminate the call when the app is in bg or device locked

# Subtasks

```[tasklist]
### Android
- [x] Permissions are asked as expected (Camera & Mic)
- [x] Permissions are not re-asked for when already available
- [x] Cookies are shared between sessions (e.g. the display name is remembered)
- [x] Call is still up and running when the app goes in background
- [x] Call is still up and running when the device is locked
- [x] JavaScript can be invoked on the WebView
- [x] Event handlers can be used to respond to arbitrary requests
- [x] System audio routing is respected (e.g. connecting headphones will automatically be handled in the web app)
- [x] System UI can be shown when a call starts (e.g. CallKit iOS status bar green bubble and ongoing video indicator)
- [x] Other system audio (e.g. music) gets paused when a call starts
```

```[tasklist]
### iOS
- [x] Permissions are asked as expected (Camera & Mic)
- [x] Permissions are not re-asked for when already available
- [x] Cookies are shared between sessions (e.g. the display name is remembered)
- [x] Call is still up and running when the app goes in background
- [x] Call is still up and running when the device is locked
- [x] JavaScript can be invoked on the WebView
- [x] Event handlers can be used to respond to arbitrary requests
- [x] System audio routing is respected (e.g. connecting headphones will automatically be handled in the web app)
- [x] System UI can be shown when a call starts (e.g. CallKit iOS status bar green bubble and ongoing video indicator)
- [x] Other system audio (e.g. music) gets paused when a call starts
```

**Comment by manuroe** [comment]
Jitsi can work in background but it is very hacky.
@amshakal, @VolkerJunginger : can we descope this behavior for the tech preview? 
@fkwp says yes.
