### ISSUE TITLE
[Story] RTE full screen mode in EX

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#1973]
# Description

* As a user 
* I want to expand the rich text editor
* so that I can edit a long message comfortably

# Design
- [Figma](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?node-id=8046%3A129386&mode=dev)

# Size estimate

S

# Dependencies

- https://github.com/vector-im/element-meta/issues/1937

# Acceptance criteria
Rich text editor input can be made larger by dragging the handle

# Out of scope

Nothing

# Sign-off

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

# Subtasks

```[tasklist]
### Android
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/pull/822
- [ ] https://github.com/vector-im/element-x-android/pull/1447
```

```[tasklist]
### iOS
```

```[tasklist]
### Other
```
