### ISSUE TITLE
[Story] Create poll

### ISSUE THREAD

**Issue by julioromano** [vector-im/element-meta#1974]
# Description
* As a user.
* I want to create new polls.
* so that I can quickly gather a room's feedback about simple topics  .

# Size estimate
L

# Dependencies
* https://github.com/vector-im/element-meta/issues/1827

# Acceptance criteria
- Entry point:
  - A "Poll" button is present in the composer's "+" menu.
  - Clicking on "Poll" opens the "Create poll" screen.
- Question:
  - Only 1 question per poll.
  - No length limit.
  - Can't be empty.
- Options (i.e. the answers to the poll):
  - Min 2.
  - Max 20.
  - Can't be empty.
  - Max 240 characters.
  - Clicking on "Add option" adds an option.
    - When the 20th option has been added the “Add option” button disappears.
  - Clicking on the delete icon button removes an option.
    - When there's only 2 options the delete icon button are disabled.
- Poll type:
  - A switch allows to select between "disclosed" (aka "open", the default value) and "undisclosed" (aka "closed) polls.
- On pressing "cancel" (iOS) or navigating back (Android):
  - If the editor content is not empty show a confirmation dialog before dismissing the editor.
- On pressing "create":
  - If there are any empty text fields switch them to show an error state with a useful message to the user.
  - Otherwise send the "poll start" Matrix event and close the screen instantly (w/out showing any progress indicator); a local echo of the event must immediately appear in the timeline. Errors/retries must behave the same as with any other message in the timeline.

# Out of scope
* Reordering the options when creating or editing a poll

# Sign-off
### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

# Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-meta/issues/2010
- [ ] https://github.com/vector-im/element-meta/issues/2011
- [ ] https://github.com/vector-im/element-x-android/pull/1180
- [ ] https://github.com/vector-im/element-x-android/pull/1294
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/1571
```

```[tasklist]
### Other
- [ ] Create Kiwi test case
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/2388
```
