### ISSUE TITLE
[Story] Add/edit/delete a link using the RTE in EX

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#1975]
# Description

As a user 
- I want to add a link to text in the rich text editor
- so that I can send messages containing links

As a user 
- I want to edit or delete a link within the rich text editor
- so that I can change or fix links in my own messages

# Design
- TBC

# Size estimate

M

# Dependencies

- https://github.com/vector-im/element-meta/issues/1937

# Acceptance criteria

- User can add a link to selected text in the rich text editor.
- User can edit a link in the rich text editor.
- User can delete a link in the rich text editor.

# Out of scope

- https://github.com/matrix-org/matrix-rich-text-editor/issues/616
- https://github.com/matrix-org/matrix-rich-text-editor/issues/617
- https://github.com/matrix-org/matrix-rich-text-editor/issues/618

Nothing

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

# Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/pull/1309
```

```[tasklist]
### iOS
```

```[tasklist]
### Library
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/pull/801
```

**Comment by callumu** [comment]
When editing a link on Android, only the link can be edited, not the word that's had the link added to it. This is different to iOS. @jonnyandrew I feel like we discussed this as an Android limitation, but can you confirm?

**Comment by jonnyandrew** [comment]
Yes this is a known limitation but my understanding was that it affected all platforms as it is not yet implemented in the rust model (see open issues matrix-org/matrix-rich-text-editor#616, matrix-org/matrix-rich-text-editor#617, matrix-org/matrix-rich-text-editor#618). Are you sure it's working correctly on iOS @callumu? If so, perhaps iOS is using a workaround to achieve the behaviour @alfogrillo?

**Comment by callumu** [comment]
> Yes this is a known limitation but my understanding was that it affected all platforms as it is not yet implemented in the rust model (see open issues [matrix-org/matrix-rich-text-editor#616](https://github.com/matrix-org/matrix-rich-text-editor/issues/616), [matrix-org/matrix-rich-text-editor#617](https://github.com/matrix-org/matrix-rich-text-editor/issues/617), [matrix-org/matrix-rich-text-editor#618](https://github.com/matrix-org/matrix-rich-text-editor/issues/618)). Are you sure it's working correctly on iOS @callumu? If so, perhaps iOS is using a workaround to achieve the behaviour @alfogrillo?

Oh sorry this is my fault, it doesn't exist on iOS also. Ignore my initial comment and I'll mark this as done

**Comment by jonnyandrew** [comment]
No problem! Thanks for reviewing.
