### ISSUE TITLE
[Story] Reply to a poll

### ISSUE THREAD

**Issue by julioromano** [vector-im/element-meta#1976]
### Description

* As a user.
* I want to reply to a poll.
* So that I can comment on it without necessarily voting.

### Acceptance criteria

- Long-pressing a poll in the timeline must bring up the "message actions" bottom sheet.
- Timeline menu (aka "bottom sheet"):
  - Must show the poll preview in the composer.
  - Must not show the "forward" action
  - Must not show the "edit" action
  - Must not show the "copy" action
  - Screen readers must properly read aloud the poll preview
  - Works with dark and light theme
  - Other existing options in the bottom sheet are verified to work
- On replying:
  - The reply in the timeline includes the poll preview.
- Poll preview:
  - Contains (as usual) the sender of the replied message
  - Contains the poll's question and the poll icon ([design](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=14489%3A136013&mode=design&t=ymBFbaa4yigwsKhp-1)).
- Backward compatibility
  - Replies to polls are rendered as such on legacy Element clients

### Size estimate

S

### Dependencies

- https://github.com/vector-im/element-meta/issues/1830
- https://github.com/ruma/ruma/pull/1646

### Out of scope

- Showing the poll preview in the room list.
- Showing the edit or end poll actions.

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/pull/1848
- [ ] https://github.com/vector-im/element-x-android/pull/1857
```

```[tasklist]
### iOS
```

```[tasklist]
### Other
- [ ] Create Kiwi test case
- [ ] https://github.com/ruma/ruma/pull/1698
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2850
```

**Comment by julioromano** [comment]
This can go to phase 2 if we're time constrained in phase 1

**Comment by alfogrillo** [comment]
Investigated a bit why replies aren't working for polls: 
currently rust expects the reply to be for a `m.room.message` which have a `msgtype` and a `body`.
However the `m.poll.start` events don't have these fields so the parser fails.

There are at least two possible ways two fix:

1) Change the logic inside the matrix-rust-sdk to address explicitly replies to other kind of messages other than `m.room.message`

2) Make `m.poll.start` compliant to `m.room.message`. This means adding inside the `content` these two fields:
```
"body": "Poll start event description",
"msgtype": "m.text"
```
This is digested by the matrix-rust-sdk but it requires similar changes on the old clients to ensure interoperability.
However I think this approach is discouraged by the [Poll MSC](https://github.com/matrix-org/matrix-spec-proposals/blob/95fdc44b904d2b4d2f227db99050e539e43f3509/proposals/3381-polls.md) which says:

"Note that the extensible event fallbacks did not fall back to m.room.message in this MSC: this is deliberate to ensure polls are treated as first-class citizens. Client authors not willing/able to support polls are encouraged to instead support Extensible Events for better fallbacks."

fyi: @julioromano @langleyd

**Comment by julioromano** [comment]
Re: ☝️ 

https://github.com/ruma/ruma/pull/1646 plus some other rust sdk work should allow us to send replies for polls too.

**Comment by alfogrillo** [comment]
Replies to poll seem to work on EXI (and maybe also on EXA fyi: @julioromano)
However there is no specific UI in the composer when replying a to a poll (it's like replying to a text message).
@amshakal or @callumu do we have a design for it?

**Comment by callumu** [comment]
> Replies to poll seem to work on EXI (and maybe also on EXA fyi: @julioromano) However there is no specific UI in the composer when replying a to a poll (it's like replying to a text message). @amshakal or @callumu do we have a design for it?

I added something quickly [here](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=14489%3A136005&mode=design&t=w1vkaanC2PMp2Eh2-1) using the new poll icon.

Let me know if there are any issues / concerns

**Comment by alfogrillo** [comment]
> > Replies to poll seem to work on EXI (and maybe also on EXA fyi: @julioromano) However there is no specific UI in the composer when replying a to a poll (it's like replying to a text message). @amshakal or @callumu do we have a design for it?
> 
> I added something quickly [here](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=14489%3A136005&mode=design&t=w1vkaanC2PMp2Eh2-1) using the new poll icon.
> 
> Let me know if there are any issues / concerns

I guess we should use the same new icon everywhere in the timeline?
We also have an icon for the "ended poll" (with a little checkmark).
Is it gonna change as well?

**Comment by callumu** [comment]
> > > Replies to poll seem to work on EXI (and maybe also on EXA fyi: @julioromano) However there is no specific UI in the composer when replying a to a poll (it's like replying to a text message). @amshakal or @callumu do we have a design for it?
> > 
> > 
> > I added something quickly [here](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=14489%3A136005&mode=design&t=w1vkaanC2PMp2Eh2-1) using the new poll icon.
> > Let me know if there are any issues / concerns
> 
> I guess we should use the same new icon everywhere in the timeline? We also have an icon for the "ended poll" (with a little checkmark). Is it gonna change as well?

Yes but won't they be automatically updated when the icons in Compound change? Here are the new icons:

[Polls](https://www.figma.com/file/gkNXqPoiJhEv2wt0EJpew4/Compound-Icons?type=design&node-id=1098%3A28208&mode=design&t=7ZKIkmSCTXeAQaq2-1)

[Poll ended](https://www.figma.com/file/gkNXqPoiJhEv2wt0EJpew4/Compound-Icons?type=design&node-id=1924%3A16688&mode=design&t=7ZKIkmSCTXeAQaq2-1)

**Comment by alfogrillo** [comment]
> > > > Replies to poll seem to work on EXI (and maybe also on EXA fyi: @julioromano) However there is no specific UI in the composer when replying a to a poll (it's like replying to a text message). @amshakal or @callumu do we have a design for it?
> > > 
> > > 
> > > I added something quickly [here](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=14489%3A136005&mode=design&t=w1vkaanC2PMp2Eh2-1) using the new poll icon.
> > > Let me know if there are any issues / concerns
> > 
> > 
> > I guess we should use the same new icon everywhere in the timeline? We also have an icon for the "ended poll" (with a little checkmark). Is it gonna change as well?
> 
> Yes but won't they be automatically updated when the icons in Compound change? Here are the new icons:
> 
> [Polls](https://www.figma.com/file/gkNXqPoiJhEv2wt0EJpew4/Compound-Icons?type=design&node-id=1098%3A28208&mode=design&t=7ZKIkmSCTXeAQaq2-1)
> 
> [Poll ended](https://www.figma.com/file/gkNXqPoiJhEv2wt0EJpew4/Compound-Icons?type=design&node-id=1924%3A16688&mode=design&t=7ZKIkmSCTXeAQaq2-1)

Unfortunately there is manual work to be done:

We need to
- Update the library manually to use the new icons
- Update any snapshot / ui tests to match new icons

**Comment by alfogrillo** [comment]
@callumu apparently the new icons have not been release yet?
The latest update I can found is [here](https://github.com/vector-im/compound-design-tokens/pull/60)

**Comment by callumu** [comment]
> @callumu apparently the new icons have not been release yet? The latest update I can found is [here](https://github.com/vector-im/compound-design-tokens/pull/60)

Okay. Is it easier to wait for them to be updated before adding them?

**Comment by julioromano** [comment]
> Replies to poll seem to work on EXI (and maybe also on EXA fyi: @julioromano) However there is no specific UI in the composer when replying a to a poll (it's like replying to a text message). @amshakal or @callumu do we have a design for it?

Replies on EXA are disabled due to https://github.com/vector-im/element-meta/issues/1976#issuecomment-1719614764 as it was decided back then.

Since the rust work linked above has been done we can enable them as soon as we start working on this story.
