### ISSUE TITLE
[Tech task] Polls Analytics

### ISSUE THREAD

**Issue by julioromano** [vector-im/element-meta#2014]
# Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/pull/1284
- [ ] https://github.com/vector-im/element-x-android/pull/1285
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/1691
```

```[tasklist]
### Other
- [ ] https://github.com/matrix-org/matrix-analytics-events/pull/85
```
