### ISSUE TITLE
[Epic] Polls - phase 2

### ISSUE THREAD

**Issue by julioromano** [vector-im/element-meta#2020]
# Open questions

```[tasklist]
### ❓
- [ ] https://github.com/ruma/ruma/pull/1638/
```

# Size estimate

* 0x S
* 3x M
* 1x L

# Scope

```[tasklist]
### User Stories
- [ ] https://github.com/vector-im/element-meta/issues/2182
- [ ] https://github.com/vector-im/element-meta/issues/1976
- [ ] https://github.com/vector-im/element-meta/issues/2180
- [ ] https://github.com/vector-im/element-meta/issues/2179
- [ ] https://github.com/vector-im/element-meta/issues/2217
- [ ] https://github.com/vector-im/element-meta/issues/2187
- [ ] https://github.com/vector-im/element-meta/issues/2188
```

### Stretch goals

- [ ] https://github.com/vector-im/element-meta/issues/2183
- [ ] Start creating the state event described in the MSC to start caching polls
- [ ] [Story] Show UTD warning on polls when some votes are UTDs
- [ ] [Story] "Poll ended" push notifications

# Out of scope

- Nothing

# Terminology

- **Disclosed polls**: In the context of the [MSC](https://github.com/matrix-org/matrix-spec-proposals/pull/3381) defines polls where the current results are shown to users while the poll is still open
- **Undisclosed polls**: In the context of the [MSC](https://github.com/matrix-org/matrix-spec-proposals/pull/3381) defines polls where the results are only shown to users once the poll was closed
- **Open polls**: Used in the current Element apps. The same thing as "disclosed polls" in the [MSC](https://github.com/matrix-org/matrix-spec-proposals/pull/3381).
- **Closed polls**: Used in the current Element apps. The same thing as "undisclosed polls" in the [MSC](https://github.com/matrix-org/matrix-spec-proposals/pull/3381).

# References

* [Technical lead](https://gitlab.matrix.org/new-vector/internal/-/wikis/Departments/Engineering/Engineering-Roles#project-technical-lead): ~@julioromano~ @alfogrillo  
* Times sheeting: `Element X`
* MSC: https://github.com/matrix-org/matrix-spec-proposals/pull/3381
* FigJam: https://www.figma.com/file/8bsgS77yqIL3ozyQ4mAqZp/EX-Polls?type=whiteboard&node-id=0%3A1&t=XQKTbtOB3B9p1de1-1
* PRD for original implementation: https://docs.google.com/document/d/1e7L6QoanhJIo81bj2PEFnAPRw10uObKXVPzcei1pTQ4/edit
* New PRD: https://docs.google.com/document/d/1Fhpe6Wj_fwGAxtb46KXVud8W8MkhTmke6zC9gL-aYmE/edit
* Phase 1 https://github.com/vector-im/element-meta/issues/1526
