### ISSUE TITLE
[Story] Poll Vote

### ISSUE THREAD

**Issue by julioromano** [vector-im/element-meta#2021]
# Description
* Surface an API to send a poll vote event at the Rust FFI layer.
* Send a vote event when clicking on a choice inside a poll in the timeline.
* Users can vote multiple times, only their last vote counts.

# Size estimate
S

# Dependencies
* https://github.com/vector-im/element-meta/issues/1830

# Acceptance criteria
- Each room member (including the creator of a poll) has one vote
- Participants can change their votes as long as the poll has not been ended (last vote counts and poll is updated in real time)
- see local echo and smoothly transition to returned event from the server

# Open questions
* How to render when a vote event fails to send (dialog? Error state in the start event?)

# Sign-off

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

# Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-meta/issues/2025
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/1597
```

```[tasklist]
### Other
- [ ] Create Kiwi test case
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/2470
```
