### ISSUE TITLE
[Story] Poll End

### ISSUE THREAD

**Issue by julioromano** [vector-im/element-meta#2022]
# Description
- Surface an API to send an end poll event at the Rust FFI layer.
- Add the “end poll” button when long pressing a poll in the timeline.
- Send poll end event.

# Size estimate
S

# Dependencies
* https://github.com/vector-im/element-meta/issues/1830

# Acceptance criteria
- The creator can end a poll at any time
- Once a poll has been ended there are no more votes possible
   - If the poll was undisclosed the results are shown
   - The poll start event is updated and shows the "poll ended" look.
 - ~~A “Poll has been ended”- event is created in the timeline~~
   - ~~In the best case this event looks different than the original poll so the user understands what the difference is. “And the winner is!!”~~
- A poll that has been ended cannot be re-opened.

# Preconditions
* User must be poll creator, room moderator or admin. (i.e. "redact" power level)

# Sign-off
### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

# Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-meta/issues/2026
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/1597
```

```[tasklist]
### Other
- [ ] Create Kiwi test case
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/2471
```
