### ISSUE TITLE
[Story] Threaded message decorator in EX

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2037]
### Description

* As a user
* I want to know when a message is coming from a thread
* So that I can use the reply action to make my answer goes to a thread. It will not break the UX of other users with matrix clients supported threads

This is a cheap workaround before we implement threads in EX. We are aware that only matrix power users will understand that using the reply button will not break UX on thread-capable apps.

### Acceptance criteria

- Visual indicator like 🧵 on threaded messages in the timeline
- The action menu must display "Reply in Thread"
- The composer should have the hint "Reply in Thread"
- Reply to such a message will appear in the thread on matrix apps that support threads (Element Web and legacy mobile apps). There is nothing to implement here. It is already working

### Size estimate

S

### Dependencies

- None

### Preconditions

- None

### Out of scope

- No change in the room list
- No change in push notifications
- Polls and Stickers decorations

### Open questions

- None

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1236
- [ ] https://github.com/vector-im/element-x-android/issues/1423
- [ ] https://github.com/vector-im/element-x-android/issues/1422
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/1687
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/2519
```

- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion

**Comment by callumu** [comment]
I have a few questions:

1. When is the deadline for the design work on this needed?
2. Is changing the composer placeholder text or changing anything visually in the composer out of scope? I'm unsure if this follows 'change the composer behaviour'

**Comment by manuroe** [comment]
> 2. Is changing the composer placeholder text or changing anything visually in the composer out of scope? I'm unsure if this follows 'change the composer behaviour'

It is out of scope. UX will not be great. This is why I added warnings about only power users will know it. You can sync with @amshakal to understand the logic behind.

**Comment by Velin92** [comment]
As of right now the Rust SDK is only capable of checking if a Message Like Event is threaded or not.
These are the following event types that can be threaded:

```
case emote
case image
case audio
case video
case file
case notice
case text
case location
```

This means that Stickers and Polls are out of scope as of right now

**Comment by manuroe** [comment]
Thanks to the nice @callumu's  input in [figma](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3?node-id=10768:65625&mode=design#551841969), I removed the following from out of scope
*Change the composer behavior or add specific actions to threaded messages. Only aware people will know that they can use the existing reply action to not break the thread*

and added new acceptance criteria:
- The action menu must display "Reply in Thread"
- The composer should have the hint "Reply in Thread"

cc @ganfra @Velin92
