### ISSUE TITLE
[Story] Change user avatar within EX

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2039]
### Description

* As a user
* I want to change my avar within the app

Figma link: TBD

### Acceptance criteria

- The user can change their avatar in the app
- The avatar change is reflected everywhere in the app

### Size estimate

S

### Dependencies

None

### Preconditions

None

### Out of scope

?

### Open questions

?

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1302
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/1716
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2529
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2550
```

**Comment by jmartinesp** [comment]
Should we also allow removing the current avatar?

**Comment by manuroe** [comment]
This is a a good idea. I would say if we do it for this screen, we should do it for the room avatar as well.

@VolkerJunginger what do you think? Should we offer the user the option to remove their avatar now?

**Comment by VolkerJunginger** [comment]
Is this two things? My avatar and the avatar in a room?

**Comment by jmartinesp** [comment]
> we should do it for the room avatar as well.

That's already the case on Android, that's why I asked since we're more or less copying the code for the UI and event logic and adapting it to different Rust calls 🤔 .

**Comment by jmartinesp** [comment]
> Is this two things? My avatar and the avatar in a room?

@VolkerJunginger I think he meant for removing the avatar of a room in its settings?

FWIW I uploaded [a quick PR](https://github.com/matrix-org/matrix-rust-sdk/pull/2550) in the Rust SDK to allow removing the avatar, in case we want to do it en EX.

**Comment by VolkerJunginger** [comment]
If this is the same thing effort-wise. Sure.
