### ISSUE TITLE
[Story] Show polls in room summaries

### ISSUE THREAD

**Issue by julioromano** [vector-im/element-meta#2048]
### Description

* As a user
* I want to see polls in each room summary in the room list
* So that I can have a quick glimpse at the last message of a room from the list, even if it's a poll.

The preview of a room’s last event is usually shown in the room list. We need to add support in both the apps and the rust SDK to show such a preview when the last event is a poll.

### Acceptance criteria

- When a poll is the last event in a room, the user sees an appropriate summary of the poll when looking at the room entry in the room list.
- The summary is in the form "Poll: ${question of the poll}".

### Size estimate

S

### Dependencies

- https://github.com/vector-im/element-meta/issues/1827

### Preconditions

- None

### Out of scope

- None

### Open questions

- None

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/pull/1387
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/1770
```

```[tasklist]
### Other
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2580
```

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

**Comment by julioromano** [comment]
@amshakal @callumu Right now the idea is to blindly shove the poll's question in the room summary (if the poll is the last message of a room).
Should we do something different? E.g. prefix the question with "Poll: " ? Use an emoji? Is there any "prior art" regarding design of room summaries?

**Comment by callumu** [comment]
No prior art or template, but I like your suggestion of using the prefix 'Poll:' then the poll question. It's clearer that the most recent message was a poll and not just a message from a user. Can you add this?

We haven't discussed emojis in this use case so I'd like to avoid them in the room summary until we do so - emojis can affect the look and feel of an app quite a lot.

**Comment by julioromano** [comment]
> No prior art or template, but I like your suggestion of using the prefix 'Poll:' then the poll question. It's clearer that the most recent message was a poll and not just a message from a user. Can you add this?

Sure!
