### ISSUE TITLE
[Story] Show creator view in timeline

### ISSUE THREAD

**Issue by julioromano** [vector-im/element-meta#2049]
### Description

* As a user who created a poll
* I want to have quicker access to poll features 
* So that I can more readily manage my polls

Creator sees the poll start event differently than other users.
Creator will have easier access to certain features normally hidden behind a long press.
~We won’t offer the option to end a poll if nobody has voted yet (even though the spec allows for this). Users will have to remove (delete) the poll in such cases~. (removed because without "edit poll" capability it makes no sense to hide the "End Poll" CTA. Morevoer ending a poll i always possible form the long press menu).

### Acceptance criteria

- The poll timeline item shows a promiment "End poll" CTA on polls created by the current user.
- Clicking on such CTA opens a confirmation dialog with copy: "Are you sure you want to end this poll?" if confirmed, it ends the poll (same behavior as going through the long press menu).

### Size estimate

M

### Dependencies

- https://github.com/vector-im/element-meta/issues/1974
- https://github.com/vector-im/element-meta/issues/2022

### Preconditions

- The current user is the creator of the poll

### Out of scope

- None

### Open questions

~- Ending the poll is a final, non-undoable action, should we ask for confirmation when clicking on the "End poll" button or add some other UX behavior to prevent unwanted clicks (perhaps instead of clicking we could use a long click or a swipe?)?~ 

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/pull/1429
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/1765
- [ ] https://github.com/vector-im/element-x-ios/pull/1799
```

```[tasklist]
### Other
```

### Sign-offs

- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

**Comment by julioromano** [comment]
@amshakal can you please give a look at the open questions section and give us your take?

**Comment by julioromano** [comment]
@amshakal I see the "Creator view" only in the iOS designs, can we have the Android version too?

**Comment by amshakal** [comment]
@julioromano [It exists!](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=9898%3A74169&mode=design&t=9CmLL59abTpe1EQL-1) I just forgot to change the title of the flow.

Yeah you are right, maybe for ending a poll, having a confirmation will be nice.

The copy could say:

Are you sure you want to end this poll?
<Cancel>  <Yes>
