### ISSUE TITLE
[Story] Show a user has been mentioned in the timeline

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2062]
### Story

As a user that i looking at a message containing a mention I want to understand that this is a mention.

Figma link: TBD

### Acceptance criteria
- Resolve a mention into a "pill" design.
- Show the avatar and the name of the mentioned user

### Size estimate

M

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1433
- [ ] https://github.com/vector-im/element-x-android/issues/1449
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/1804
- [ ] https://github.com/vector-im/element-x-ios/issues/1822
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/2606
```

```[tasklist]
### Design
- [x] Complete user mentions designs
```

- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion

**Comment by Velin92** [comment]
Currently working on this, however there are no designs ready so the initial implementation will be a bit improvised.

Also since there is a loading state (since we lazily fetch the members) for some very big rooms the display name and the avatar of the suer are not ready yet, this only happens in very very big rooms, and is usually unnoticeable, however as of right now I am implementing a loading state for the mention that looks like this:
<img width="212" alt="Screenshot 2023-09-26 at 16 20 02" src="https://github.com/vector-im/element-meta/assets/34335419/fb5bf63e-52d9-40b9-b8ef-f1c2215d74d3">

Colors and design not final, this is just essentially displaying a placeholder of a @ with the user ID, this can of course be changed later if design wants, as I said is very unlikely to get into this condition

NOTE: This is also the El-Web default behaviour when a matrix user mention is done for a user that is not in the room
