### ISSUE TITLE
[Story] Open user profile when tapping on a mention

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2063]
### Story

As a user that has received a message containing a mention I want to open the user profile of the user that has been mentioned when I tap the mention so that I can get more info on that user.

Figma link: TBD

### Acceptance criteria
- Open the user profile when tapping on a mention

### Size estimate
S

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1448
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/1821
```

- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion
