### ISSUE TITLE
[Story] Show a "@" badge in the room-list if a user has mentioned me in a room

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2064]
### Story

As a user that has been mentioned in a room I want to see a badge in the room-list so that I can see that I have been mentioned right away.

Figma link: TBD

### Acceptance criteria
- Show a badge "@" for the user that has been mentioned in a room
- The badge "@" must stay if the room gets a limited flag 
- Hide the badge when the user has seen the message that is mentioning them 

@amshakal Not sure about this.

### Size estimate
M

### Preconditions
- We might need a better mark read room logic

### Subtasks - Deadline 21st December

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1450
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/1823#
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/2607
```

```[tasklist]
### Design
- [x] @ badge design for the room list
```

### Extra Goals for 2024
```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/2954
```

- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion

**Comment by Velin92** [comment]
Was mentioned here that we would also require to improve the mark room read logic to avoid, the read marker in the room list to be inconsistent:
https://github.com/matrix-org/matrix-rust-sdk/issues/2607

Maybe is worth opening an issue for such a task or a story for this too?
@VolkerJunginger  @manuroe

**Comment by amshakal** [comment]
What do we mean by limited flag?

**Comment by bnjbvr** [comment]
Can we close this now?

**Comment by manuroe** [comment]
yes, QA will happen at the epic level

**Comment by manuroe** [comment]
We had to ignore the new feature in the SDK. We need to come back to it next year.

**Comment by bnjbvr** [comment]
The SDK part is now fixed, should we close this again, after manual QA verification maybe? cc @manuroe @VolkerJunginger

**Comment by manuroe** [comment]
Final tests will happen at the epic level
