### ISSUE TITLE
[Story] Mention a user in message

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2066]
### Story

As a user I want to mention an other user in a message so that I can make sure that user might not miss my important message.

Figma link: TBD

### Acceptance criteria
In general:
- Only room-members can be mentioned in a room
- One can not mention themself
- If a users have been blocked they cannot be mentioned

Creating a mention
- typing @ +  mid into the composer creates a mention (@manuroe  is that right?)

Suggesting Users to be mentioned
- Typing "@" + an other letter into the composer opens a view with suggestions for room-members that the user is allowed to mention
- with each letter the suggestions get better
- The suggested users are shown w. avatar and name
- @room mentions all room members
- @room mentions only appear in the suggestions if the user has the right to trigger room notifications
- If the user taps on a suggestion a "mention-pill" is shown in the composer

### Size estimate
M

```[tasklist]
### Open Questions
- [x] ~~Should the @room pill have the room string be localised? I imagine that it should still be triggered by explicitly typing "@room" however i wonder if the pill itself when render can be localised~~ Not required.
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1455
- [ ] https://github.com/vector-im/element-x-android/issues/1452
- [ ] https://github.com/vector-im/element-x-android/issues/1453
- [ ] https://github.com/vector-im/element-x-android/issues/1591
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/1829
- [ ] https://github.com/vector-im/element-x-ios/issues/1826
- [ ] https://github.com/vector-im/element-x-ios/issues/1830
- [ ] https://github.com/vector-im/element-x-ios/issues/1858
- [ ] https://github.com/vector-im/element-x-ios/issues/1875
- [ ] https://github.com/vector-im/element-x-ios/issues/1914
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/2606
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/2722
```

```[tasklist]
### RTE
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/issues/848
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/issues/851
- [ ] https://github.com/matrix-org/matrix-rich-text-editor/issues/852
```

```[tasklist]
### Design
- [x] User suggestions view design (should account for the expanded case of the RTE, alongside landscape mode)
- [x] @room pill design
```

- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion

### Out of scope
- Known issue: suggestions will be slow to display in large rooms with thousands of users. This is the same problem as loading the room members list screen: https://github.com/vector-im/element-x-android/issues/851, https://github.com/vector-im/element-x-ios/issues/1360 and the related SDK issue: https://github.com/matrix-org/matrix-rust-sdk/issues/1979).

**Comment by Velin92** [comment]
Should the @room pill have the "room" string be localised? I imagine that it should still be triggered by explicitly typing "@room" (since this is how is interpreted by all the matrix clients) however i wonder if the pill itself, being a different view, should render the word room localised.

@VolkerJunginger

**Comment by VolkerJunginger** [comment]
you mean `@raum`. No, seems funny to me.

**Comment by Velin92** [comment]
Perfect then I'll keep it as @room in the text inside the pill for all languages

**Comment by Velin92** [comment]
Regarding instead the @room suggestion? In El-iOS it is also referred as "Everyone" but is not localised. Should it be localised? This is the string I am referring to
![Simulator Screenshot - iPhone 14 - 2023-10-12 at 15 50 35](https://github.com/vector-im/element-meta/assets/34335419/15987d8a-223c-4348-a9ff-e4e00dcd2c72)

@VolkerJunginger

**Comment by Velin92** [comment]
> Regarding instead the @room suggestion? In El-iOS it is also referred as "Everyone" but is not localised. Should it be localised? This is the string I am referring to ![Simulator Screenshot - iPhone 14 - 2023-10-12 at 15 50 35](https://user-images.githubusercontent.com/34335419/274621588-15987d8a-223c-4348-a9ff-e4e00dcd2c72.png)
> 
> @VolkerJunginger

Had a chat with @VolkerJunginger  about this we decided to try a localised approach.
So if we for example have the app in German, that name will be displayed as "Alle", this means that also looking fror @alle should give you this suggestion.
So botht the string and the suggestion should be localised (of course only if such localisation exists).
@ganfra

**Comment by jmartinesp** [comment]
> So botht the string and the suggestion should be localised (of course only if such localisation exists). @ganfra

That could be a bit problematic: if the user is using a language that didn't include a translation for this shortcut and then it did after an update, they'll try to type `@room` again an they won't understand why it's not working, and believe it's broken. Maybe we should try to include both the translated and the original one?

**Comment by Velin92** [comment]
> > So botht the string and the suggestion should be localised (of course only if such localisation exists). @ganfra
> 
> That could be a bit problematic: if the user is using a language that didn't include a translation for this shortcut and then it did after an update, they'll try to type `@room` again an they won't understand why it's not working, and believe it's broken. Maybe we should try to include both the translated and the original one?

the idea is that @room always works, is the additional @everyone that should be localised. (on legacy El-iOS and El web the @room mention works with both the @room tag and the  @everyone tag)

**Comment by Velin92** [comment]
Also of course @room is not localised since is a default matrix mention.
