### ISSUE TITLE
[Story] Reply to a message that contains a mention

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2067]
### Story

As a user I want to be able to reply to a message that contains a mention.

Figma link: TBD

### Acceptance criteria
- The design of the reply could take the mention into account.
- The reply should not to trigger notifications or badges for the mentioned user. (the user has already been mentioned for that message)
- The user can add an additional mention to their message

### Size estimate

S

### Open questions
```[tasklist]
- [x] ~~`The reply should not to trigger notifications or badges for the mentioned user` is not aligned with [MSC3952](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/3952-intentional-mentions.md#impact-on-replies)~~ Answered [here](https://github.com/vector-im/element-meta/issues/2067#issuecomment-1739685626)
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1456
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/1831
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/2606
```

- [ ] QA signoff on completion
- [ ] Design signoff on completion
- [ ] Product signoff on completion

**Comment by manuroe** [comment]
> `The reply should not to trigger notifications or badges for the mentioned user` is not aligned with [MSC3952](https://github.com/matrix-org/matrix-spec-proposals/blob/main/proposals/3952-intentional-mentions.md#impact-on-replies) that states `Clients should include the sender of the event being replied to as well as any mentioned users in that event (excluding yourself)`

@VolkerJunginger can you align with @daniellekirkwood on this acceptance criteria. Web and mobiles must have the same behavior.

**Comment by clokep** [comment]
> @VolkerJunginger can you align with @daniellekirkwood on this acceptance criteria. Web and mobiles must have the same behavior.

I think MSC3952 was mostly designed to *not change behavior*. The behavior of the legacy mentions was that both the sender of the original message and the mentioned user in it would end up in the "fallback" text causing both to be mentioned.

Luckily MSC3952 makes it so you can control the fallback separately from who is mentioned, so this is actually controllable now.

**Comment by manuroe** [comment]
Thanks @clokep. This is great. This is then a product decision to make the break with legacy apps or other matrix clients.

@VolkerJunginger the thing to get here is this is the sender app that decides the people to mention. EX can send mentions as you describe but there will no way to prevent a different behavior from messages coming another matrix client.

**Comment by Velin92** [comment]
> Thanks @clokep. This is great. This is then a product decision to make the break with legacy apps or other matrix clients.
> 
> @VolkerJunginger the thing to get here is this is the sender app that decides the people to mention. EX can send mentions as you describe but there will no way to prevent a different behavior from messages coming another matrix client.

according to @jplatte the [intentional mention task](https://github.com/matrix-org/matrix-rust-sdk/issues/2606) can allow us to not to trigger notifications or badges for the mentioned user

**Comment by jplatte** [comment]
Just to be clear, intentional mentions help when the client that sends the reply implements them. The problem will persist for messages received by EX that are sent by clients that don't implement intentional mentions. (what Manu said above)

**Comment by VolkerJunginger** [comment]
> Thanks @clokep. This is great. This is then a product decision to make the break with legacy apps or other matrix clients.
> 
> @VolkerJunginger the thing to get here is this is the sender app that decides the people to mention. EX can send mentions as you describe but there will no way to prevent a different behavior from messages coming another matrix client.

that's ok.

**Comment by Velin92** [comment]
Blocking https://github.com/vector-im/element-x-android/issues/1456 and https://github.com/vector-im/element-x-ios/issues/1831 since we need to decide if we want or not to display mentions as pills inside replies.
@callumu @VolkerJunginger
