### ISSUE TITLE
[Story] Push notifications for polls

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-meta#2071]
### Description

* As a user
* I want to receive notification for polls
* So that I'm aware of new started polls 

### Acceptance criteria
- The user receives a push notification for each "poll started" event in **group** and **direct** rooms
    - The above happens only if the **Group chat** / **Direct chat** notification settings are set to `All messages`
    - Notification message: `Poll: {poll_question}`
- Notifications should work both for encrypted and plain rooms
    - The rust sdk should apply already the push rules automatically for encrypted rooms
- [Polls push rules](https://github.com/matrix-org/matrix-spec-proposals/blob/travis/msc/polls-notifs/proposals/3930-polls-notifications.md) should be in **sync** with the ones of normal messages (see the table below)
- Element X should align poll rules with the one of messages whenever a message push rule changes (see the table below).
- In case of inconstancies the user should see [this screen](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=11265-23110&mode=dev).
    - A tap on the "Continue" button should sync all the rules. Poll rules should copy the messages one (see the table below)

| Poll rules | Align to |
| :- | :- |
|.m.rule.poll_start_one_to_one<br/>.org.matrix.msc3930.rule.poll_start_one_to_one|.m.rule.room_one_to_one|
|.m.rule.poll_start<br/>.org.matrix.msc3930.m.rule.poll_start| .m.rule.message|

### Size estimate
None

### Dependencies
- None

### Preconditions
- [Polls push rules](https://github.com/matrix-org/matrix-spec-proposals/blob/travis/msc/polls-notifs/proposals/3930-polls-notifications.md) on the home server. Apparently **matrix.org** don't have them. 

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### Out of scope
- TBD

### Open questions
- Can we ignore "poll end" events? (we don't show them in the timeline, and we couldn't jump to the start event when clicking on the notification, so does it make sense to display notifications for them?)
     - A: "poll end" events will be addressed together with poll history later 
- Push rules sync between poll rules and "regular" rules: do we really have to expose this to the user as it was done in legacy clients? Ideally this should be user transparent.
    - A: EX already has [a screen](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=11265-23110&mode=dev) to warn the user about "inconsistencies" on push rules (without mentioning any particular rule). polls rules should be aligned using the same screen in case of problems.

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/pull/1467
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/1852
- [ ] https://github.com/vector-im/element-x-ios/pull/1819
```

```[tasklist]
### Other
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2604
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2658
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2644
```

**Comment by julioromano** [comment]
> Can we ignore "poll end" events?

@VolkerJunginger wanted to have a notification on poll end. This means we can't ignore them. Though, with the current state of the SDK, I don't think we can scroll the timeline all the way to the start event when clicking on the "end poll" notification. What d'you think @alfogrillo ?

We definitely can manage to get push notifications for "poll ended" events.    
This would require  the sync of "poll end" push rules with the ones of normal messages (4 more lines in the table above).
But like you said we don't have a working "go to" navigation in the timeline atm.
To be fair I think this a general problem with push notifications and links and isn't limited to "poll end" events.
