### ISSUE TITLE
[Story] Receive and play a voice message

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#2083]
### Description

Receive and play voice messages in the timeline.

### Acceptance criteria

- It is behind a feature flag in developer settings
- It displays in the timeline
- It can be played from the timeline
- It works in encrypted and unencrypted rooms
- Message continues playing after scrolling out of view
- Navigating away from the room stops playback
- Play and pause the voice message
- Display length of message and play/pause state
- It is compatible with MSC3245 **v1**
- Sending an audio file attachment continues to work as expected
- It interoperates with classic Element mobile and web apps
- Files are not exposed through system file managers
- It works in encrypted and unencrypted rooms
- If you delete a voice message while it is playing it should stop playing
- Playing multiple messages one after the other should continue to work as expected.
- While voice message is a local echo in the timeline, the play button is disabled.

### Size estimate

None

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Out of scope

- Preview the voice message before sending

### Open questions

- [ ] Can we support MSC3245 v1 _and_ v2

### Subtasks

```[tasklist]
### Android
- [x] Verified with build in screen reader
- [x] Add feature flag
- [x] Display voice messages in timeline (with placeholder UI)
- [x] Allow voice messages to be played in timeline
- [x] Allow voice messages to be paused and resumed
- [ ] https://github.com/vector-im/element-x-android/pull/1503
- [ ] https://github.com/vector-im/element-x-android/pull/1606
- [ ] https://github.com/vector-im/element-x-android/pull/1607
- [ ] https://github.com/vector-im/element-x-android/pull/1609
- [ ] https://github.com/vector-im/element-x-android/pull/1637
- [ ] https://github.com/vector-im/element-x-android/pull/1643
- [ ] https://github.com/vector-im/element-x-android/pull/1654
- [ ] https://github.com/vector-im/element-x-android/pull/1660
- [ ] https://github.com/vector-im/element-x-android/pull/1664
- [ ] https://github.com/vector-im/element-x-android/pull/1668
- [ ] https://github.com/vector-im/element-x-android/pull/1682
- [ ] https://github.com/vector-im/element-x-android/pull/1683
- [ ] https://github.com/vector-im/element-x-android/pull/1826
```

```[tasklist]
### iOS
- [ ] Verified with build in screen reader
- [ ] Add feature flag
- [ ] Display voice messages in timeline (with placeholder UI)
- [ ] Allow voice messages to be played in timeline
- [ ] Allow voice messages to be paused and resumed
```

```[tasklist]
### Other
```

**Comment by langleyd** [comment]
Added a user case in the acceptance criteria regarding this bug on EI -> https://github.com/vector-im/element-ios/issues/7190

**Comment by langleyd** [comment]
Added a use case in the acceptance criteria for playing multiple voice messages(one after the other) based on a bug in EA -> https://github.com/vector-im/element-android/issues/8412
