### ISSUE TITLE
[Story] Record and send a voice message

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#2084]
### Description

Record and send a voice message.

### Acceptance criteria

- It is behind a feature flag in developer settings
- Tap and hold to record
- Release to send (to be enhanced in #2104 and #2105)
- System microphone permissions dialog displays if necessary
- Navigating away stops recording
- Navigating away discards the recording
- Sent messages are in Opus audio format
- Messages have a 30 minute maximum length
- Sending an audio file attachment continues to work as expected
- It interoperates with classic Element mobile and web apps
- Files are not exposed through system file managers
- It works in encrypted and unencrypted rooms
- We should apply a sleep lock so the phone does not sleep and therefor stop a recording.
- If a voice message fails to send the normal message retry button should work.
- Sending a voice message quickly after another one should work.
- Progress spinner displays while uploading media

#### Audio format
- Sample rate: 48kHz
- Bitrate: 24kbps
- Mono (single channel)
- Appropriate complexity and resample quality for the platform.
- Encoder application: 2048 (voice, default is typically 2049 as audio) (out of scope for Android)

### Size estimate

None

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Out of scope

- Save as draft
- Encrypting audio files stored on the device
- Typing notifications
- Reply with a voice message
- Recording length limits or warnings ([discussion](https://docs.google.com/document/d/1S_Y4Fkh7sJ7S1q5KltT1HdL3oYSJMglRl7ZbdBeQya0/edit?disco=AAAA57tDRfA))
- Edit a voice message
- Record a message when text formatting options are shown
- Using the VOIP encoder application on Android (due to https://github.com/vector-im/libopusencoder-android/issues/4)

### Subtasks

```[tasklist]
### Android
- [x] Verified with build in screen reader
- [ ] https://github.com/vector-im/element-x-android/pull/1546
- [x] ~~Release to send~~ Release to show placeholder for preview state
- [x] System microphone permissions dialog displays if necessary
- [x] Navigating away stops recording
- [x] Navigating away discards the recording
- [x] Messages have a 30 minute maximum length
- [x] Progress indicator displays while uploading media
- [x] Verified 1 minute of audio ≈ 180 kilobytes
- [ ] https://github.com/vector-im/element-x-android/pull/1650
- [ ] https://github.com/vector-im/element-x-android/pull/1652
- [ ] https://github.com/vector-im/element-x-android/pull/1645
- [ ] https://github.com/vector-im/element-x-android/pull/1663
- [ ] https://github.com/vector-im/element-x-android/pull/1672
- [ ] https://github.com/vector-im/element-x-android/pull/1677
```

```[tasklist]
### iOS
- [ ] Verified with build in screen reader
- [ ] Tap and hold to record
- [ ] Release to send
- [ ] System microphone permissions dialog displays if necessary
- [ ] Navigating away stops recording
- [ ] Navigating away discards the recording
- [ ] Messages have a 30 minute maximum length
- [ ] Progress indicator displays while uploading media
- [ ] Verified 1 minute of audio ≈ 180 kilobytes
```

```[tasklist]
### Other
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/2697
```

**Comment by langleyd** [comment]
Updated acceptance criteria to for a sleep lock during recording to address this bug on the classic app -> https://github.com/vector-im/element-ios/issues/7598

**Comment by langleyd** [comment]
Updated acceptance criteria to include message retry which was a problem in the classic apps -> https://github.com/vector-im/element-android/issues/8407

**Comment by langleyd** [comment]
Updated acceptance criteria to include sending a voice message quickly after another, as was reported as a problem int he class apps -> https://github.com/vector-im/element-android/issues/8362

**Comment by jonnyandrew** [comment]
> Updated acceptance criteria to include message retry which was a problem in the classic apps

This is already included under https://github.com/vector-im/element-meta/issues/2106

> sleep lock during recording to address this bug on the classic app -> https://github.com/vector-im/element-ios/issues/7598

It's possible that we are immune to this bug given the tap and hold UX. Should we change the AC to "voice message may be recorded for longer time than screen timeout setting?"

**Comment by jonnyandrew** [comment]
I've removed the VOIP encoder application type requirement from scope for Android as it's non-trivial to achieve (see https://github.com/vector-im/libopusencoder-android/issues/4 for details).

**Comment by jacotec** [comment]
I'm missing how to "lock" the recording without the need to keep the recording button pressed all the time. Will it be the "slide up" gesture like in the current Element/IOS?

**Comment by jonnyandrew** [comment]
> I'm missing how to "lock" the recording without the need to keep the recording button pressed all the time.

The lock mechanism won't be part of this iteration but it might be in a later one (cc @callumu / @VolkerJunginger).

**Comment by jonnyandrew** [comment]
@nimau @alfogrillo I've added a checkbox to roughly verify the file sizes we're creating. At 24 kbps, 1 minute of audio should be about 180 kB.
