### ISSUE TITLE
[Task] Track errors with voice messages

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#2085]
### Description

Voice message errors are tracked to Sentry (given user consent).

### Acceptance criteria

- Errors are tracked to Sentry.
- Errors are only tracked if user consent is given.
- Errors have a distinct top-level exception type (e.g. `VoiceMessageException`)

### Size estimate

S

### Dependencies

- #2084
- #2083

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Subtasks

```[tasklist]
### Android
- [x] Errors are tracked to Sentry
- [ ] https://github.com/vector-im/element-x-android/pull/1667
```

```[tasklist]
### iOS
- [ ] Errors are tracked to Sentry
```

```[tasklist]
### Other
```

**Comment by jonnyandrew** [comment]
@alfogrillo / @nimau are you happy with the level of error tracking in iOS? Can move this task to done?

**Comment by nimau** [comment]
> @alfogrillo / @nimau are you happy with the level of error tracking in iOS? Can move this task to done?

@jonnyandrew it should be fine. Currently, El-X doesn't send errors to posthog, so we've added a bunch of logs to track errors related to voice messages in rageshakes.
