### ISSUE TITLE
[Story] Preview a voice message

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#2104]
### Description

* As a user
* I want to listen back to my recording before sending it
* So that I know what the recipient will hear

### Acceptance criteria

- Releasing the record button doesn't send immediately but creates a preview
- Preview displays in the editor
- Play button plays the preview from start to end
- Pause button pauses playback
- Play button resumes playback
- Navigating away stops playback and discards the recording
- After tapping send, (while voice message is uploading)
   - stop playing the message, and
   - disable all interactivity in the preview

### Size estimate

None

### Dependencies

- #2084 

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Out of scope

- Edit a voice message
- Save as draft
- Encrypting audio files stored on the device
- Waveform and scrubbing UI
- Reply with a voice message
- Recording length limits or warnings ([discussion](https://docs.google.com/document-/d/1S_Y4Fkh7sJ7S1q5KltT1HdL3oYSJMglRl7ZbdBeQya0/edit?disco=AAAA57tDRfA))

### Subtasks

```[tasklist]
### Android
- [x] Verified with build in screen reader
- [x] Releasing the record button doesn't send immediately but creates a preview
- [x] Preview displays in the editor
- [x] Play button plays the preview from start to end
- [x] Pause button pauses playback
- [x] Play button resumes playback
- [x] Navigating away stops playback and discards the recording
- [x] Tapping send stops playback and disables interactivity during upload
- [x] Tapping delete stops playback
- [ ] https://github.com/vector-im/element-x-android/pull/1672
```

```[tasklist]
### iOS
- [ ] Verified with build in screen reader
- [ ] Releasing the record button doesn't send immediately but creates a preview
- [ ] Preview displays in the editor
- [ ] Play button plays the preview from start to end
- [ ] Pause button pauses playback
- [ ] Play button resumes playback
- [ ] Navigating away stops playback and discards the recording
- [ ] Tapping send stops playback and disables interactivity during upload
- [ ] Tapping delete stops playback
```

```[tasklist]
### Other
```
