### ISSUE TITLE
[Story] Discard a voice message preview

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#2105]
### Description

* As a user
* I want to be able to discard a voice message
* So that I am not forced to send a message after recording it

### Acceptance criteria

- Tap delete button to erase preview from device

### Size estimate

None

### Dependencies

- #2104 

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Out of scope

- Save as draft
- Encrypting audio files stored on the device

### Open questions

- TBD

### Subtasks

```[tasklist]
### Android
- [x] Verified with build in screen reader
- [x] Tap delete button to erase preview from device
```

```[tasklist]
### iOS
- [ ] Verified with build in screen reader
- [ ] Tap delete button to erase preview from device
```

```[tasklist]
### Other
```
