### ISSUE TITLE
[Story] Use timeline features for voice messages

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#2106]
### Description

Existing timeline features work as expected for voice messages. Much of this functionality may come for free.

### Acceptance criteria

- Retry a failed attempt to send
- Reply to a voice message
- Delete a voice message
- React with emoji to a voice message
- Admin powers (e.g. to delete) are honoured
- The "copy" action should be removed since isn't helpful

### Size estimate

None

### Dependencies

- #2083
- #2084 

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Out of scope

- Edit a voice message
- Share voice messages to other apps
- Decryption progress indicator
- Typing notifications
- Reply with a voice message
- Auto-play consecutive voice messages

### Subtasks

```[tasklist]
### Android
- [x] Verified with build in screen reader
- [ ] Retry a failed attempt to send
- [x] Reply to a voice message
- [x] Delete a voice message
- [x] React with emoji to a voice message
- [x] Admin powers (e.g. to delete) are honoured
- [ ] https://github.com/vector-im/element-x-android/pull/1658
- [ ] https://github.com/vector-im/element-x-android/pull/1673
- [ ] https://github.com/vector-im/element-x-android/pull/1700
- [ ] https://github.com/vector-im/element-x-android/pull/1704
```

```[tasklist]
### iOS
- [x] Verified with build in screen reader
- [ ] Retry a failed attempt to send
- [x] Reply to a voice message
- [x] Delete a voice message
- [x] React with emoji to a voice message
- [x] Admin powers (e.g. to delete) are honoured
- [ ] https://github.com/vector-im/element-x-ios/pull/1889
- [ ] https://github.com/vector-im/element-x-ios/pull/1893
- [ ] https://github.com/vector-im/element-x-ios/pull/1907
```

```[tasklist]
### Other
```

**Comment by alfogrillo** [comment]
@jonnyandrew can you clarify this?

> Verified with build in screen reader

Does this means we expects all the actions in the timeline menu being read by the screen reader?
Currently on EXI actions in the timeline menu aren't read in general (for any event).

**Comment by jonnyandrew** [comment]
I don't think we need to reverify any existing features with a screen reader here but perhaps we can check that the new timeline item doesn't introduce any problems, for example we could check:
- that we can traverse voice messages in the timeline with a screen reader
- that it's possible to add a reaction directly to a voice message from the timeline with a screen reader
- that the actions menu can be opened from a voice message with a screen reader

**Comment by alfogrillo** [comment]
> I don't think we need to reverify any existing features with a screen reader here but perhaps we can check that the new timeline item doesn't introduce any problems, for example we could check:
> 
> * that we can traverse voice messages in the timeline with a screen reader
> * that it's possible to add a reaction directly to a voice message from the timeline with a screen reader
> * that the actions menu can be opened from a voice message with a screen reader

Apparently we don't have the voice over (aka screen reader) at all in the timeline menu. Do you have it on EXA?

**Comment by jonnyandrew** [comment]
Yeah on EXA the timeline menu does support screen readers. If it's not supported on iOS then we can't verify anything here but I think it'd be worth opening an issue about that.

**Comment by alfogrillo** [comment]
> Yeah on EXA the timeline menu does support screen readers. If it's not supported on iOS then we can't verify anything here but I think it'd be worth opening an issue about that.

It seems we need very little work to have it on EXI.
No need for an additional issue. Open directly a [PR](https://github.com/vector-im/element-x-ios/pull/1907).

**Comment by jonnyandrew** [comment]
I've just tested this with a screen reader on Android. Long press (through double tap and hold) is not working on voice message items as it is with other timeline items.
