### ISSUE TITLE
[Story] Receive notifications for new voice messages

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#2108]
### Description

Notifications for voice messages

### Acceptance criteria

- Tap notification to enter the relevant room
- Notification content is the text representation of the voice message
    - Use the localized string `common_voice_message` for the notification body (and ignore the "fallback" event text representation)

### Size estimate

None

### Dependencies

- #2083 

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Out of scope

- Play voice message from the notification

### Subtasks

```[tasklist]
### Android
- [ ] Tap notification to enter the relevant room
- [ ] Notification content is the text representation of the voice message
- [ ] https://github.com/vector-im/element-x-android/pull/1705
```

```[tasklist]
### iOS
- [ ] Tap notification to enter the relevant room
- [ ] Notification content is the text representation of the voice message
```

```[tasklist]
### Other
```

**Comment by alfogrillo** [comment]
> Notification content is the text representation of the voice message

We typically use localized strings to represent media content.
On iOS we use `common_voice_message` for voice messages.
@jonnyandrew should we update the issue to make this clear?

**Comment by jonnyandrew** [comment]
Good point, please feel free to update the issue. Let's follow the pattern of other media notifications.
