### ISSUE TITLE
[Story] See voice message summary in room list

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#2109]
### Acceptance criteria

- When a voice message is the latest in a room, the text representation should be displayed in the room list.

### Size estimate

None

### Dependencies

- #2083

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Subtasks

```[tasklist]
### Android
- [x] Voice message summary displays in room list
```

```[tasklist]
### iOS
- [ ] Voice message summary displays in room list
```

```[tasklist]
### Other
```
