### ISSUE TITLE
[Story] Voice message analytics

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#2110]
### Description

Add analytics for voice messages.

### Acceptance criteria

- When user taps the send button the following event is tracked to Posthog:
  - Event: Composer
  - Property: isVoiceMessage
- Only send if user has given consent for analytics

### Size estimate

None

### Dependencies

- #2084
- #2104

### Android
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Subtasks

```[tasklist]
### Android
- [x] Event is tracked on tapping send button https://github.com/vector-im/element-x-android/pull/1706
```

```[tasklist]
### iOS
- [x] Event is tracked on tapping send button
- [ ] https://github.com/vector-im/element-x-ios/pull/2019
```

```[tasklist]
### Other
- [ ] https://github.com/matrix-org/matrix-analytics-events/pull/86
```

**Comment by jonnyandrew** [comment]
~~Blocked waiting for https://github.com/matrix-org/matrix-analytics-events/pull/86~~
