### ISSUE TITLE
[Story] Voice messages ‘hold to record’ tooltip

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#2111]
### Acceptance criteria

- 'Hold to record' tooltip shows after tapping the record button

### Size estimate

None

### Dependencies

- #2084

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Subtasks

```[tasklist]
### Android
- [x] Verified with build in screen reader
- [x] 'Hold to record' tooltip shows after tapping the record button
```

```[tasklist]
### iOS
- [x] Verified with build in screen reader
- [x] 'Hold to record' tooltip shows after tapping the record button
```

```[tasklist]
### Other
```

**Comment by jonnyandrew** [comment]
Superseded by tap to record behaviour in #2166
