### ISSUE TITLE
[Story] See waveform visualisation for voice messages

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#2112]
### Description

Display a waveform representing the voice message in the player

### Acceptance criteria

- Waveform displays in voice messages in timeline.
- Waveform displays in voice message held in the preview player.
- Waveform is generated from the audio details received in the 
message.
- Waveform for a given message displays the correct shape

### Size estimate

None

### Dependencies

- #2083 
- #2104

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Out of scope

- Scrubbing the playback position

### Subtasks

```[tasklist]
### Android
- [x] Tested waveform shape is correct (tested by comparing waveform peaks with EW)
- [x] Waveform displays in voice messages in timeline.
- [x] Waveform displays in voice message held in the preview player.
```

```[tasklist]
### iOS
- [ ] Tested waveform shape is correct
- [ ] Waveform displays in voice messages in timeline.
- [ ] Waveform displays in voice message held in the preview player.
- [ ] https://github.com/vector-im/element-x-ios/pull/1919
```

```[tasklist]
### Other
- [x] Fix incorrect waveform value range (resolved in https://github.com/matrix-org/matrix-rust-sdk/pull/2697)
```
