### ISSUE TITLE
[Story] See recording audio visualisation for voice messages

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#2114]
### Description

Display recording audio visualisation for voice messages

### Acceptance criteria

- A ~~pulsating~~ live waveform displays while recording a voice message
- ~~The waveform does not display the current audio, rather it shows amplitude or is some simple abstraction of audio.~~

### Size estimate

None

### Dependencies

- #2084

### Preconditions

- TBD

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Out of scope

- TBD

### Open questions

- TBD

### Subtasks

```[tasklist]
### Android
- [ ] A live waveform displays while recording a voice message
```

```[tasklist]
### iOS
- [ ] A live waveform displays while recording a voice message
```

```[tasklist]
### Other
```
