### ISSUE TITLE
[Design review] Improve voice message UXD

### ISSUE THREAD

**Issue by jonnyandrew** [vector-im/element-meta#2166]
### Description

- Tracking issue for voice messages tasks identified through [design review](https://docs.google.com/document/d/1WO4LQz5MwCh2bYqmzk3tq0xzugZBNBhdT4a--QUbzvY/edit).

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/pull/1704
- [ ] https://github.com/vector-im/element-x-android/pull/1705
- [ ] https://github.com/vector-im/element-x-android/pull/1686
- [x] Show download indicator only if download takes more than 2 seconds ([designs](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13150-101020&mode=design&t=bmcKNXBk2BC6j4z3-0)) https://github.com/vector-im/element-x-android/pull/1793
- [x] Show error dialog if voice message failed to upload ([design](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?node-id=13455:110271&mode=dev)) https://github.com/vector-im/element-x-android/pull/1796
- [x] Tap to record ([designs](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?node-id=14321:168946&mode=dev))   remove ‘hold to record tooltip’ https://github.com/vector-im/element-x-android/pull/1784
```

```[tasklist]
### iOS
- [x] Haptic feedback: vibrate on tap and release record button
- [x] VoiceOver support (end to end sending/receiving/playing voice messages)
- [x] Show download indicator only if download takes more than 2 seconds ([designs](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=13150-101020&mode=design&t=bmcKNXBk2BC6j4z3-0))
- [ ] https://github.com/vector-im/element-x-ios/pull/2013
- [ ] https://github.com/vector-im/element-x-ios/pull/2018
- [ ] https://github.com/vector-im/element-x-ios/pull/2021
- [x] Tap to record ([designs](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?node-id=14321%3A168946&mode=dev)) + remove ‘hold to record tooltip’
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by alfogrillo** [comment]
> Show download indicator only if download takes more than 2 seconds

@jonnyandrew I think we said on Google docs to show if it takes more than **1 second**.
Is it correct?

edit: maybe the value has been updated, now I see two seconds in the other doc 👍🏻

**Comment by jonnyandrew** [comment]
Sorry for the confusion. We updated it to 2 seconds after [this conversation](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3?node-id=13150:101638&mode=dev#602648577).
