### ISSUE TITLE
[Story] Edit a poll

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-meta#2179]
### Description

* As a poll creator
* I want to edit a poll
* So that I can amend polls quickly

### Acceptance criteria
- Poll creators see the "edit poll" button in the timeline when no one voted yet
  - Alternatively users can use the timeline menu to edit a poll
- If someone voted, the "Edit poll" button becomes "End poll" an the edit isn't allowed anymore
    - In this case the timeline menu should't show the "Edit poll" option anymore 
- After the edit starts, the apps shows a similar form as for the creation of a poll but with all the fields filled with the data from the editing poll ([design](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=9458-136968&mode=dev)).
- To complete the edit, the poll should pass all the preconditions we check for poll's creation (max 20 options, no empty options, no empty poll's question)
- After the tap on "Done",  the new event (the edited poll) is sent in the timeline.
    - The editor is allowed to complete the edit even if votes arrive during the edit. Votes sent during the edit should be considered "lost" and the edited poll must not take them into account. 
- Tap on "Cancel" shows [this alert](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=15019-37307&mode=dev) just if **at least a change has been made** in the form.
    - The same alert should be shown in the "create new poll" flow (copies need to updated).
-  Tap on "Delete a Poll" will show a [confirmation alert](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=15019-73397&mode=dev). If the action is confirmed, the poll is deleted from the timeline.
- Display the "(edited)" mark next to edited polls in the timeline

### Size estimate
M

### Dependencies
- https://github.com/vector-im/element-meta/issues/2180

### Preconditions
- Editor must be the poll creator.
- Poll must have no votes cast

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Out of scope
- TBD

### Open questions
- Can room's administrators (people having enough power levels) edit the poll as poll creators?
- ~What happens if votes are received while an a poll edit is in progress?~
    - ~Legacy clients ignore the problem and allow the edit anyway. In this case the votes preceding the edit are **not** rendered in the timeline.~
    - ~@VolkerJunginger suggests to disable the edit/raise an error when this happens~
- Is local echo working for edited event? What happens on the timeline if the edit fails? 

### Subtasks

```[tasklist]
### Android
- [x] Allow editing a poll https://github.com/vector-im/element-x-android/pull/1869
- [x] Add confirmation dialog for canceling an edit https://github.com/vector-im/element-x-android/pull/1886
- [x] Add delete button to edit poll screen https://github.com/vector-im/element-x-android/pull/1895
- [x] Display the "(edited)" mark next to edited polls in the timeline https://github.com/vector-im/element-x-android/pull/1897
```

```[tasklist]
### iOS
```

```[tasklist]
### Other
- [ ] https://github.com/ruma/ruma/pull/1638
- [x] Clean up unused strings in Localazy (particularly for common dialogs which now differ between the platforms)
```
