### ISSUE TITLE
Delight: App Layout (Mobile IA)

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#218]
## Intro

**Problem we’re solving**

* Set accurate first impression with new users to compete effectively and set playing field equally across platforms \(iOS & Android\) to deliver improvements to D1 later \(Q4\)

**Goals**

* Implement and release [the proposed redesign](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals) in order to:
* Cement Element as the leading Matrix app, where we’re ceding market mindshare to rising competition due to poor usability and poor first impression
* Convert our existing early adopters into promoters

**Problems we’re not solving**

* Re-designing ‘second tap’ screens or flows like settings, rooms, etc

**Design principles**

* Can be [found here](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=1779%3A103278)

**Success Metrics**

* The App layout project is a strategic bet, we do not think it will have direct impact on metrics such as D1
* We intend to approach this project with a "data-validated" mindset over a "data-led" mindset; we'll seek to confirm or disprove our hypothesis at each stage to ensure success, we will not start with data to define our direction
* Each experiment will have it's own success criteria based on the hypothesis being tested
* We will use overall SUS scores and other guardrails to ensure we're doing no harm

<hr />

## Discovery

We have designs that need validating before we ship to product.
We will run a series of experiments to increase confidence in the new designs:
- \[x\] https://github.com/vector-im/element-meta/issues/225
- \[x\] https://github.com/vector-im/element-meta/issues/219
- \[x\] https://github.com/vector-im/element-meta/issues/220
- \[x\] https://github.com/vector-im/element-meta/issues/221
- \[x\] https://github.com/vector-im/element-meta/issues/222

- \[x\] [Recruiting participants](https://github.com/vector-im/element-meta/issues/243)

<details>
  <summary><b>Click to see The Experimentation Plan!</b></summary>

## The Experimentation Plan

We intend to run a series of experiments to reduce risk, remove assumptions, and gain confidence in the proposals.

* The [full design proposals are here](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals)

| E2E Feedback | Space Switching | Edit Layout | Tab-less Layout | Invites |
|---|---|---|---|---|
| **Goal**<br />Show the new designs to new and existing Element users for feedback on the whole design | **Goal**<br />Move Space switching to the app header. Can users still access their Spaces, is it a positive interaction? | **Goal**<br /> How does the design for Edit layout impact the user's home screen and does it scale well? | **Goal**<br /> We don't believe we need tabs at the bottom of the screen, we need to understand if \(without tabs\) users can navigate the app and complete the flows successfully | **Goal**<br /> When a user receives invites, how do they appear? We need to ensure that they're not missed but also are not blocking or disruptive to the rest of the Element experience |
| https://github.com/vector-im/element-meta/issues/225 | https://github.com/vector-im/element-meta/issues/219 | https://github.com/vector-im/element-meta/issues/220 | https://github.com/vector-im/element-meta/issues/221 | https://github.com/vector-im/element-meta/issues/222 |
| **Overview of experiment**<br /> Both platforms, new and existing users | **Overview of experiment**<br /> Both platforms, functional prototype. Android first | **Overview of experiment**<br /> One platform, functional prototype. iOS | **Overview of experiment**<br /> Maze | **Overview of experiment**<br /> Maze |
| **Status**<br /> In design | **Status**<br /> In design | **Status**<br /> In design | **Status**<br /> In design | **Status**<br /> In design |
| **Expected behaviour**<br /> Users understand the new layout. Existing users highlight big impactful differences | **Expected behaviour**<br /> Users are able to find and switch Spaces and subspaces easily | **Expected behaviour**<br /> Users who take advantage of the Edit layout feature suggested have a good home experience | **Expected behaviour**<br /> Users are able to complete tasks in the app without getting lost | **Expected behaviour**<br /> Users are able to continue in their app without handling their invites first. |
| **Actual results**<br /> Pending... | **Actual results**<br /> Pending... | **Actual results**<br /> Pending... | **Actual results**<br /> Pending... | **Actual results**<br /> Pending... |
| **Decision**<br /> Pending... | **Decision**<br /> Pending... | **Decision**<br /> Pending... | **Decision**<br /> Pending... | **Decision**<br /> Pending... |

</details>

<hr />

## Delivery

1. Validate designs through tests and Experiments \(Est. 2 months\)
2. Build new designs into app \(Est. X months\)
3. Launch new designs to product - all at once \(Est. MM-2022\)

- \[x\] https://github.com/vector-im/element-android/issues/6605
- \[x\] https://github.com/vector-im/element-android/issues/6502
- \[x\] https://github.com/vector-im/element-ios/issues/6405

[A detailed overview of spec and delivery actions can be found here](https://www.craft.do/s/LbgfynbpqJJWRG)

### Risks and Mitigations

There are risks associated with the design, our mitigation efforts include:
- \[x\] vector-im/element-meta#225
- \[x\] vector-im/internal-planning#251
<details>
  <summary><b>Click to Risks and Mitigation plan!</b></summary>

  ## Mitigation Plan
| Risk | Details | Mitigation options | Decision |
|---|---|---|---|
| Timeline | Projects of this nature can often take time or encounter a lot of unexpected road bumps/blocks | Clarity of scope on deliverables and estimated timelines | <ul><li>Validate designs through experimentation \(Est. 2 months\)</li><li>Integrate designs into current app \(Est. XX months\)</li></ul> |
| Rolling out to new users will result negative impact to R30 | A big design change is hard for users who are used to the existing product. | <ul><li>[Understand the impact of the change](https://github.com/vector-im/element-meta/issues/225)</li><li> Ensure a clear notification plan to existing customers \(Insert GH\)</li></ul> | TBD |
| Measurability | It will be hard to measure the impact of these changes | Establish a baseline metric ASAP | vector-im/internal-planning#251 |
| ... | ... | ... | ... |

</details>

### Roll out details - WIP

These designs will be a big change for users and the roll out and launch must be managed effectively.
While in discussions the plan details will be [here](https://docs.google.com/document/d/1Ouu6q-uK0CFMFyh_Wb_XWTxYIAwF8abYGzNDaPXrxiI/edit?usp=sharing) as it promotes comments.

<hr />

## Decisions

There are notable decisions that the team will make along the way, we will note them here:

1. *ElementX or ElementiOS*: Where and how do we build the experiments?
     \* We are optimising for speed of delivery.
     \* We will built Edit Layout experiment in SwiftUI and deploy using ElementiOS app to participants.
     \* [Read the notes here](https://github.com/vector-im/internal-planning/issues/249#issuecomment-1106332314)
2. TBD...
     \* Lorem
     \* Ipsum

</details>

**Comment by daniellekirkwood** [comment]
## Decision made: We will prioritise this project, starting in Q2
It's accepted that this project may not directly impact D1 retention but is instead a strategic move to ensure that we compete visually today and have the right foundation and platform to improve D1 quicker and more effectively later. 

## Next Steps: April 12, 2022
- [x] Discuss the project and scope with the team (and run a pre-mortem)
- [x] Understand the design decisions to-date (with Designers)
- [x] Discuss metrics and measures and undertake [work to create Baseline](vector-im/internal-planning#251)
- [ ] Run the Maze experiments
- [x] Discuss the technical feasibility and approach (with Engineers)
- [x] Start to build the functional prototypes

**Comment by daniellekirkwood** [comment]
## Clarifying the plan (April 29, 2022)

- [x] We will build 2 experiments, 1 in each platform. (Building started May 2, 2022)
  - Space switching on Android
  - Edit layout on iOS
  - Each of these tests will be shared with at least 12 people, and will run for 2 weeks minimum. There will be at least 3 points that we collect feedback over this period. See [here for participant and feedback collection info](https://docs.google.com/document/d/18Nj7yMMK5h9kSdxuyR3uuXPJdPGlp8WfZGlBLHkzbp0/edit?usp=sharing).
- [ ] There are 3 experiments we will run on Maze. (Amsha will start building these when back from vacation May 9, 2022)
  - Invites, tab-less, and E2E flow
- [ ] While the prototypes are with users being tested (Space switching and Edit layout) we will start to build the changes confirmed by the Maze tests

**Comment by ericdecanini** [comment]
Android space switching epic [here](https://github.com/vector-im/element-android/issues/6605)

**Comment by gileluard** [comment]
iOS epic [here](https://github.com/vector-im/element-ios/issues/6405)

**Comment by daniellekirkwood** [comment]
https://github.com/vector-im/element-meta/issues/550

**Comment by daniellekirkwood** [comment]
Results: https://docs.google.com/spreadsheets/d/1d2jirxzoSbSvu0dkiaTkhm_-2r6IK1weRVBny1TmbJs/edit#gid=679956630
