### ISSUE TITLE
[Story] Poll history: list

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-meta#2187]
### Description

* As a user
* I want to access the history of polls
* So that I can find and vote on polls conveniently 

Users can access to the [poll history](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=15048-120409&mode=design&t=fn7ADGXrCdK1uXlr-4) from the room's settings. Polls are filtered by "open" and "ended" using a segmented control.
(for reference Element Legacy: [FigJam](https://www.figma.com/file/8bsgS77yqIL3ozyQ4mAqZp/EX-Polls?type=whiteboard&node-id=1-448&t=h3VITnMuscFFosNP-4))

### Acceptance criteria
- User can access to the poll history from the room's settings
    -  **(TBD: needs design)** direct chat rooms UX
- The history shows a loader during the fetch of the polls
    - **(TBD: needs design)**
    - Suggestion: limit the fetch to the latest 250 events and address backward pagination better in the next story
-  The poll history shows polls putting the most recent on top and the older following below (aka reverse chronological order)
    -  The default selected tab in the segmented control is "ongoing" (aka open polls)
- User can filter the polls using the segmented control
    - Ongoing = open polls
    - Past = ended polls 
- The poll history reacts to live updates
    - New polls?
    - New incoming votes
    - Ended polls (in this case the poll disappears from the "ongoing" polls list)

### Size estimate
L

### Dependencies
- None

### Preconditions
- None

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Out of scope
- User interaction with polls
- Backward pagination to load more polls

### Open questions
- TBD

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/pull/1913
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/2178
- [ ] https://github.com/element-hq/element-x-ios/issues/2230
```

```[tasklist]
### Other
```
