### ISSUE TITLE
[Story] Poll history: user interaction

### ISSUE THREAD

**Issue by alfogrillo** [vector-im/element-meta#2188]
### Description

* As a user
* I want to interact with the poll history
* So that I can interact with polls conveniently

In the poll history users can vote, edit or end polls. Furthermore users can load more polls in the past (potentially until to the start of the room itself).

### Acceptance criteria

- On **ongoing** polls user can
    - Vote
    - (if allowed) End a poll **(TBD: needs design)**
    - (if allowed) Edit a poll **(TBD: needs design)**
- If there are no polls in the first batch, users can load more polls ([design](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=15212-105485&mode=design&t=fn7ADGXrCdK1uXlr-4))
- When users reach the end of the poll history list by scrolling, they can tap on "Load more" to load another batch of polls ([Design](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=15140-11927&mode=design&t=fn7ADGXrCdK1uXlr-4))
    - The "Load more" button should be hidden if the start of the timeline has been reached
- If after loading more the start of the timeline is reached **and** there are no polls yet:
    - **(TBD: needs design)**  a text should say "There are no polls in this room"
    - **(TBD: needs design)** the "Load more" button is hidden

### Size estimate
M

### Dependencies
https://github.com/vector-im/element-meta/issues/2187

### Preconditions
- None

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Out of scope
- TBD

### Open questions
- TBD

### Subtasks

```[tasklist]
### Android
- [ ] Verified with build in screen reader
```

```[tasklist]
### iOS
- [ ] Verified with build in screen reader
```

```[tasklist]
### Other
```

**Comment by manuroe** [comment]
Will be done with done in https://github.com/vector-im/element-meta/issues/2187
