### ISSUE TITLE
App Layout: Space Switching Experiment [Meta]

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#219]
# Space Switching

The Delight team are running an experiment to validate hypothesis and assumptions from the new mobile layout designs. 

The [full designs are here](https://www.figma.com/file/Hw4gjP3pknMZUir8jQqmWH/%5BMobile%5D-IA-early-proposals?node-id=1119%3A103766). 

The [parent issue for experimentation is here](https://github.com/vector-im/element-meta/issues/218).

| Goal  | Understand if people see, use, and frequent the new Space Switching interaction. Does the design scale for all user groups and all numbers of Spaces? |
| ----------------------- | ------------------------------------------------------------ |
| Hypothesis | If we put Space switching in the header on the home page, then all users will see, click, use, and enjoy the interaction.<br />0 users will struggle to space switch and 100% users will be comfortable with the design, regardless of how many spaces they have. |
| Experiment methodology  | Start by building a functional prototype on Android<br />Later we will build the same to test on iOS<br />[See more information here.](https://github.com/vector-im/element-meta/issues/219#issuecomment-1110102677) |
| Participants  | We need to provide access to the design to a [minimum of 12 people](https://github.com/vector-im/element-meta/issues/219#issuecomment-1110103516). Ideally the split looks like;<br />- 3 New users (recruited using Twitter or friends of employees)<br />- 3 Community users (recruited with help from @kittykat)<br />- 3 Personal messaging users (recruited ??)<br />- 3 Workplace users (recruited ??) |
| Duration | Minimum 2 weeks. |
| Test outline | - Send a survey to all participants before they receive access to the product.<br /> - Share the product with test participants<br /> - At the end of week 1, [collect feedback](https://github.com/vector-im/element-meta/issues/219#issuecomment-1110108994)<br /><br /> - At the end of the second week, send another survey, and collect feedback |
| Team tasks and timeline | - [ ] Finish designs (Estimate: )<br />- [ ] [Build prototype on Android #5849](https://github.com/vector-im/element-android/issues/5849) (Estimate: 5 days)<br />- [ ] [Recruit participants and share intro-survey #242](https://github.com/vector-im/element-meta/issues/242) (Estimate: )<br />- [ ] Ship prototype to subjects (Estimate: )<br />- [ ] Gather results (Estimate:)<br />- [ ] Process and Iterate (Estimate: )<br />- [ ] Ship (Estimate: ) |
| Expected behaviour      | Users are able to find spaces and subspaces and navigate the app effectively. We want to hear that users were comfortable finding their spaces and subspaces. <br />We would expect users to mention the interaction positively, or not at all if it works and scales well for them. |
| Target metric  | TBD; Need to understand our ability to track events in the prototypes |
| Actual results   | Pending...    |
| Why?  | Pending...        |
| New insights   | Pending...   |
| Decision    | Pending...    |

**Comment by daniellekirkwood** [comment]
# Meeting April 11, 2022
* Changing just the header for the experiment; the rest of the app will not change to match the design. 
* Removing the left panel removes the space invites, settings, etc.

**Design needs:** 
* to add solution for removing the left-panel,
* designs for the experiment (not final design), 
* designs for how the list expands for users with lots of spaces or no spaces, 
* is the add space button pinned, 
* there's an out of the box experience and transitions, is that ok? (Yes)

**Estimates:**
* Android: 5 days
* iOS: 5 days

**Comment by daniellekirkwood** [comment]
## Decision: Which platform?
* We need to test this on both platforms as we know interaction patterns do not always carry across iOS and Android
* We need to test with a functional prototype as a "fake-o test" such as Maze will not show us behaviour over time, or a real view of how users find Spaces and subspaces
* We'll start by building the experiment on Android, and build on iOS later

**Comment by daniellekirkwood** [comment]
## Question: How many users _could_ have access to the APK? 
- There's no maximum. The limit will be informed by the method of feedback collection
[Link](https://matrix.to/#/!KiMXGIvzGnyVXjalxs:matrix.org/$gt5RuQ4afn_RU9TR4FFe4C6iTXk9BhRpVsPnZ4ucg-4?via=matrix.org&via=element.io&via=one.ems.host)

**Comment by daniellekirkwood** [comment]
## Question: How do we collect feedback?
 - [ ] We can send a survey before and after (and maybe during) the 2 week period for feedback.
 - [ ] It would be ideal to measure event tracking in the APK. @fedrunov, @gsouquet  would it be possible to use PostHog in these tests?
 - [ ] What are the other ways we can collect info from participants?

Just a thought: **Would it be best not to tell our participants what we're testing them with, to see if they notice or call out the spaces section specifically?** @amshakal

**Comment by daniellekirkwood** [comment]
The Space switching experiment is complete and successful. 
There's more information on the results in Figma and Airtable.
