### ISSUE TITLE
[Story] Android: Add switch for dark / light / system mode to advanced settings

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2195]
### Story

As a user that love to change the look of the app I want to be able to decide wether I want to use light or dark mode (or follow the system settings )so that I can sleep well at night knowing my app looks exactly like i want it to.

Ad an option to the advanced setting to switch between dark / light mode or to follow the system settings

This feature is already existing on iOS:

![Image](https://github.com/vector-im/element-meta/assets/8418515/e5e112fd-eec6-4736-8e28-ed94a3d887f0)

### Dependencies

- TBD

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [ ] Implemented
- [ ] https://github.com/vector-im/element-x-android/issues/1499
```

## Out of scope

- TBD

**Comment by bmarty** [comment]
It has been done in https://github.com/vector-im/element-x-android/pull/1844, and is available for testing in nightly and in latest version from the store.
@VolkerJunginger I let you close the issue once you have tested it?
