### ISSUE TITLE
[Story] Notification setting for invites

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2196]
### Story

As a user that get invited I want to be able to switch of being notified about invitation so that I can miss them and be sad that I have no one to talk to.

- Ad a setting in the notificsations setting screen to enable / disable the notification for invites
- default is enabled
- The feature has been asked for by a customer. @amshakal I am not sure if we should provide this feature with our version of the app, too. I believe an invitation to chat is too important (especially in a workplace context) to give the user the option to miss these. 

### Dependencies

- TBD

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### Web
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1944
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/2205
```

## Out of scope

- TBD

**Comment by pixlwave** [comment]
This is done on iOS, un-assigning myself from the issue.

**Comment by bmarty** [comment]
This is done on Android, un-assigning myself from the issue.
