### ISSUE TITLE
[Story] Mark a room or dm as favourite

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2197]
### Description

As a user that has favourite room I want to mark these as favourites so that I can find the fast.

[Figma](https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=529%3A49911&mode=design&t=MS8PTsJpMUFMcy6d-1)

### Acceptance criteria

- A room can be (un-) marked as favourite form the room-list and the room-details-page.
- There must be a visual (star-icon) in the room-headder (@amshakal ?) to show the user that this room is a favourite

### Leads

* Tech: @ganfra 
* Design: @amshakal 

### Size estimate

S/M/L

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2208
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2320
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3005
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by jplatte** [comment]
Favorite rooms are stored under `m.favourite` room account data. This should be pretty easy to integrate into `RoomInfo` on the Rust side, and expose to EX.

**Comment by manuroe** [comment]
@amshakal we would need some guidance on the design. Legacy apps do not have the same behavior.

**Comment by amshakal** [comment]
Not sure about adding a star to the room header but lets start with adding a button in the room details page. I added designs for it. I am slightly skeptical of changing the copy from favourite to un-favourite like we do for mute, unmute as the word is too long so would like to check if thats okay with everyone.
[Mark room as favourite](https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=508%3A4814&mode=design&t=MlDAfTFxjzHLPwgD-1): 
<img width="670" alt="Screenshot 2024-01-09 at 4 59 00 pm" src="https://github.com/element-hq/element-meta/assets/85162587/ffcc58e8-439c-4367-9091-674eb7171e6f">

[Mark DM as favourite](https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=508%3A4813&mode=design&t=MlDAfTFxjzHLPwgD-1):
<img width="672" alt="Screenshot 2024-01-09 at 4 59 05 pm" src="https://github.com/element-hq/element-meta/assets/85162587/68391b10-fdb6-4197-acf6-042fc3ce67b4">
