### ISSUE TITLE
[Story] DMs are DMs and not Rooms

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2199]
### Story

As a user that has a DM I want to recognise this as a DM at any time so that I can distinguish them from rooms.

@VolkerJunginger collect all places where DMs are still referred to as Rooms.

### Dependencies

- TBD

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### Web
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [ ] Verified with build in screen reader
```

```[tasklist]
### iOS
- [ ] Verified with build in screen reader
```

```[tasklist]
### Web
- [ ] Verified with system in screen reader
```

## Out of scope

- TBD

**Comment by manuroe** [comment]
We need to address https://github.com/vector-im/element-x-android/issues/1548 with this story.

**Comment by VolkerJunginger** [comment]
https://github.com/element-hq/element-meta/issues/2254
