### ISSUE TITLE
[Story] Manually mark a room as unread

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2201]
### Description

As a user that has read the messages in a room but does not have the time to react I want to manually mark a room as unread in the room-list so that I can easily identify room with open todos.

Product requirements: https://docs.google.com/document/d/15Rk9ERkQNOM9yQubbWEh-XpMzRL2iiN5HoSe_SybBbo/edit

### Acceptance criteria

N.B. Is has been decided that the old implementation of this on Legacy Element iOS will be removed to avoid conflicts between clients.

* expose "mark as (un)read" options on individual rooms on the room list
* once marked as unread the room should show a green badge. If new events come in, the room should continue showing the green badge and optionally a green mention badge, if a mention ocurred
* rooms marked as unread should show a green badge even if their notification settings are set to mentions&keywords or muted. After being marked as unread  or being rendered a room should go back to showing the default colors for those options
* marking the room as read from the room list should remove all badges **and send read receipts**, marking everything as read
* when entering a room, the manual unread flag should be unset but read receipts **should not** be sent. The timeline should handle that based on what the current position is and what is actually visible (especially after the fully read marker will start informing positions)

### Leads

* Tech: @stefanceriu 
* Design: <GitHub id>

### Size estimate

M

### Dependencies

-  Maybe MSC https://github.com/matrix-org/matrix-spec-proposals/pull/2867 if we decide to use it.

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
- [x] Does https://github.com/matrix-org/matrix-spec-proposals/pull/2867 fit our need? It is used by several matrix clients.
- [x] Is it ok to use this MSC? --> YES
```

### Subtasks
```[tasklist]
### Web
- [ ] https://github.com/element-hq/wat-internal/issues/136
```

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2261
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2360
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3037
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/3111
```

```[tasklist]
### Other
```

### Web
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by manuroe** [comment]
The MSC is currently scheduled for the next version 1.10 which should be end of Feb.

**Comment by daniellekirkwood** [comment]
This is still open on Web though all the dev work is done, just not the launch :)

here's the posthog: https://posthog.hss.element.io/insights/dOHeC0O2
