### ISSUE TITLE
Create room: Improve Userflow when adding users to a room

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2205]
### Story

When creating a room the userflow is not very good right now (see attached video).

Instead of forcing the user to cancel the search before they can continue to create the room the user should be able to continue. The change to a search focusses screen seem unnecessary.

https://github.com/vector-im/element-meta/assets/118339066/d38031aa-f086-4894-9a30-4cf39fc0df92

### Dependencies

- TBD

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [ ] TODO: Create an issue
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/pull/2209
```

## Out of scope

- TBD

**Comment by callumu** [comment]
On my iPhone I see the required behaviour which is this:


https://github.com/vector-im/element-meta/assets/110109933/477dacbf-d172-41ab-b2e7-47b919810d0b


It seems like this is a bug on your end

**Comment by Velin92** [comment]
There is definitely a bug, I was currently investigating this, since it was an easy fix, and realised that sometimes the top bar is hidden and sometimes not, even when it should not be.

**Comment by Velin92** [comment]
I found a fix here:
https://github.com/vector-im/element-x-ios/pull/2182

**Comment by callumu** [comment]
> I found a fix here: [vector-im/element-x-ios#2182](https://github.com/vector-im/element-x-ios/pull/2182)

Nice! Is there a way to add the 'Cancel' button in like the video I shared above? It's not a huge issue this is mainly for consistency

**Comment by Velin92** [comment]
Sadly I have to reopen the issue, on iOS 17.1.1 there is a bug where this fix makes the screen scrambled and look like this. Seems to only happen on 17.1.1
![IMG_0881](https://github.com/vector-im/element-meta/assets/34335419/88eaaa76-41ff-461a-b0d8-8c5792dd057f)

Looking into it

**Comment by Velin92** [comment]
At this point I am reverting my fix, in the hope that when a new update of iOS is going to get released this issue won't happen anymore.

**Comment by Velin92** [comment]
We fixed the scrambled screen issue however on iOS 17.1.1 is not possible to NOT hide the navigation bar in any way on 17.1.1

I tested the 17.2 Beta, where is technically possible to do a fix that allows the navigation bar to not hide, but the fix may break on previous versions, which is fine we could handle that so that it doesn't, but since Apple is making this system component less customisable on SwiftUI to allow for such a change, maybe we should consider changing the designs for the search bar

**Comment by manuroe** [comment]
@VolkerJunginger do you want to do something on android too?

**Comment by pixlwave** [comment]
I've fixed this on iOS here: https://github.com/vector-im/element-x-ios/pull/2209

Note that the only down side is that the search field pops in after the invites screen has been pushed, but this seems like a reasonable trade-off to fix the flow.

https://github.com/vector-im/element-meta/assets/6060466/f4004e2d-b8ae-493f-bace-8bad1bc84e93
