### ISSUE TITLE
[Story] User detail view: Show "1:1" chat button

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2207]
### Story

As a user that is visiting an other users detail view I want to have an easy way to start a 1:1 conversation so that I can start chatting.

- Ad a button to start a 1:1 chat (DM) with a user to the user detail view.

### Dependencies

- TBD

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1915
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/2179
```

## Out of scope

- TBD

**Comment by manuroe** [comment]
We would need canonical DM to implement it correctly.

The legacy apps have a list of DMs on this screen:


![Image](https://github.com/vector-im/element-meta/assets/8418515/1f15c67a-623d-4ddb-943b-ebc808cf6d82)

**Comment by ganfra** [comment]
@manuroe So what is the status about this ticket?

**Comment by manuroe** [comment]
We want to reuse the mechanism that is used when creating a DM. If the user tries to create a DM with someone with an already existing room, the app jumps to this room instead of creating one.
It means we are going to display only one room, the one the existing algorithm provides.

@VolkerJunginger, can you confirm this?

**Comment by ganfra** [comment]
Also, when opening the DM, where back navigation should lead? to the `RoomMemberDetails`? to the `RoomList`?

**Comment by manuroe** [comment]
@amshakal what do you think ^?

**Comment by VolkerJunginger** [comment]
> We want to reuse the mechanism that is used when creating a DM. If the user tries to create a DM with someone with an already existing room, the app jumps to this room instead of creating one. It means we are going to display only one room, the one the existing algorithm provides.
> 
> @VolkerJunginger, can you confirm this?

yes.

**Comment by VolkerJunginger** [comment]
@amshakal Could yo test this? I think the button is wrong

**Comment by VolkerJunginger** [comment]
@stefanceriu iOS is using an other string than Android.

**Comment by stefanceriu** [comment]
@VolkerJunginger 
> iOS is using an other string than Android.

Are you sure about that? To me, they both seems to use `Direct chat`: [iOS](https://github.com/element-hq/element-x-ios/pull/2186/files#diff-c6dbd14b155ef983d5a8ccf08e00c4d71e13b202320467d45e67ecd5582c051e) vs. [Android](https://github.com/element-hq/element-x-android/pull/1938/files#diff-c5b41961632d5c3562ddc9132be2f640f6a2c4051dcdb86f61fa37854869fc04)

**Comment by VolkerJunginger** [comment]
The iOS app does show an english text - Android is German. So something must be off.

**Comment by stefanceriu** [comment]
Oh, so they're not using different strings, it's just that iOS is missing some translations.

Will be fixed in element-hq/element-x-ios/pull/2288 (https://github.com/element-hq/element-x-ios/pull/2288/files#diff-9c27e8b707146678ab814769be3d29a8f93eef6e475491af0a2a15e884db270bL112)

**Comment by VolkerJunginger** [comment]
We're closing this. Design changes might come w. another ticket
