### ISSUE TITLE
[Story] User detail view: Magnify avatar

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2208]
### Story

As a user that is visiting an other user profile want to be able to magnify their avatar so that I can enjoy the beauty of it.

- Ad the option to magnify the avatar by tapping on it in the user detail view.

### Dependencies

- TBD

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### Web
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1907
```

```[tasklist]
### iOS
- [ ] Verified with build in screen reader
```

```[tasklist]
### Web
- [ ] Verified with system in screen reader
```

## Out of scope

- TBD

**Comment by manuroe** [comment]
Done on android

**Comment by manuroe** [comment]
Reoponed to let @VolkerJunginger test it
