### ISSUE TITLE
[Story] Scroll to end of timeline when sending a new message

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2212]
### Story

As a user that has send a message I want the timeline to scroll to that message at the end of the timeline so that I can have a look at what I just send.

- iOS should do that when sending a message from the middle of the timeline for example when sending a reply
-  On Andriod this seems buggy in general. The scrolling seems to be buggy even when sending any message.

### Dependencies

- TBD

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1877
```

```[tasklist]
### iOS
- [ ] https://github.com/vector-im/element-x-ios/issues/2147
```

## Out of scope

- TBD

**Comment by ganfra** [comment]
@VolkerJunginger so we want to scroll at the bottom no matter our position in the timeline?

**Comment by VolkerJunginger** [comment]
Yes. We want to scroll down - no matter what.

**Comment by VolkerJunginger** [comment]
This has been tested successfully for iOS.

On Android the scroillig does only happen when sending text-messages. Pictures & others do not work

**Comment by bmarty** [comment]
> On Android the scroillig does only happen when sending text-messages. Pictures & others do not work

This is now fixed.

**Comment by manuroe** [comment]
@VolkerJunginger can you check it again?
