### ISSUE TITLE
Improve back-navigation for invitations

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2213]
### Story

When accepting or declining invitations the back navigation flow need to be optimised so that the user is not landing on an empty invites page.

- @amshakal , @callumu & @VolkerJunginger to write down the flows.

### Dependencies

- TBD

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

#### Web
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2022
```

```[tasklist]
### iOS
- [x] Improve back-navigation for invitations
- [ ] https://github.com/element-hq/element-x-ios/issues/2245
```

## Out of scope

- TBD

**Comment by manuroe** [comment]
We would need to use some design tricks to make it happen. The slowness is probably due to backend problems.
Also, this should not be new problem on EX. BWI should see the problem on the legacy app too. So, do we really want to work on this for EX?

**Comment by ganfra** [comment]
@VolkerJunginger do we want the invite list screen to pop only when coming back from room? 
Meaning, if we accept the last invite from an other client while we are in the invite list screen, should we stay on it?

**Comment by manuroe** [comment]
We need to close the screen.

**Comment by bmarty** [comment]
Done, ready to be tested.
