### ISSUE TITLE
Android: Don't crop pictures in the timeline

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2214]
### Story

Pictures are cropped on top and bottom in the timeline. This should not be the case.

### Dependencies

- TBD

#### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Scope

```[tasklist]
### Android
- [ ] https://github.com/vector-im/element-x-android/issues/1940
```

## Out of scope

- TBD

**Comment by pixlwave** [comment]
Late follow-up from the discussion this morning, here is the logic we use on iOS. Completely forgot we have a minHeight too: [TimelineMediaFrame.swift](https://github.com/vector-im/element-x-ios/blob/develop/ElementX/Sources/Other/SwiftUI/Layout/TimelineMediaFrame.swift)

**Comment by manuroe** [comment]
I confirm that a screenshot from an iPhone 13 is not fully rendered in the timeline on EXA. It is normal to protect the rendering in the timeline.

Let's align Android with iOS as a minimum.

Android algo: https://github.com/vector-im/element-x-android/blob/develop/features/messages/impl/src/main/kotlin/io/element/android/features/messages/impl/timeline/components/event/TimelineItemAspectRatioBox.kt#L28

**Comment by manuroe** [comment]
We need design feedback on https://github.com/element-hq/element-x-android/pull/1941

**Comment by bmarty** [comment]
Done, ready to be tested
