### ISSUE TITLE
[Story] Show recently accessed users as potential invitees when creating a new room

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2243]
### Description
As a user that is creating a new room I'd like to see some user suggestions to start a chat with.

### Acceptance criteria

- when tapping on the new room button (within the start chat screen) the user should be pushed to the room creation flow in which they should be presented with suggestions for potential invitees based on their recent **DMs**
- a maximum of 5 users should be shown
- this list should be replaced when searching for users

### Leads

* Tech: @stefanceriu 
* Design: https://www.figma.com/file/AO7bFhGSUQt4IyBhmW26Cu/Room-List-%2B-Navigation-(new)?type=design&node-id=1-632&mode=design&t=by5d8ot3EXZdevjE-0

### Size estimate

S

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2633
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2624
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3290
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion
