### ISSUE TITLE
[Story] Timeline: Improved UX: Emotional beginning of timeline

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2244]
### Description

TODO

* As a [beneficiary]
* I want to [objective]
* So that [value generated]

### Acceptance criteria

- TBD

### Size estimate

None

### Dependencies

- TBD

### Preconditions

- TBD

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### Out of scope

- TBD

### Open questions

- TBD

### Subtasks

```[tasklist]
### Android
- [ ] Verified with build in screen reader
```

```[tasklist]
### iOS
- [ ] Verified with build in screen reader
```

```[tasklist]
### Other
```
