### ISSUE TITLE
[Story] Change the role of a user

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-meta#2259]
### Description

* As a room admin
* I want to be able to change the role of other room members to one of Admin, Moderator or Room member.
* So that I can share the responsibility of moderating a room with other trusted users.

Designs: [Admin](https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=514-17252&mode=design&t=ySW01Qx6jiTlkRXk-4) and [Moderator](https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=765-41533&mode=design&t=ySW01Qx6jiTlkRXk-4)

### Acceptance criteria

- [ ] When visiting the user profile of a room member, anyone who is an admin will see an additional option to change that user's role to one of Admin, Moderator or Room member.
- [ ] The new option should not be shown when visiting a user profile from a DM (1:1 room with `isDirect && isEncrypted`), only for regular rooms.
- [ ] Posthog tracking:
- Event: RoomAdmin
- Property: Change_Userrole_Admin, Change_Userrole_Moderator, Change_Userrole_User

### Size estimate

S

### Dependencies

- None

### Out of scope

- Compatibility with other matrix clients that use the moderation APIs in other ways, such as supporting power levels outside of member, mod and admin.

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2257
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2356
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3034
```

```[tasklist]
### Other
```

**Comment by jmartinesp** [comment]
> When visiting the user profile of a room member, anyone who is an admin will see an additional option to change that user's role to one of Admin, Moderator or Room member.

Given the designs, I guess this is no longer true?
