### ISSUE TITLE
[Story] Remove a user from a room

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-meta#2260]
### Description

* As a user that has the appropriate power level.
* I want to be able to
    * Kick a user (user can rejoin).
    * Ban a user (user cannot rejoin).
    * Unban a banner user (user can now rejoin).
* So that the room can be moderated on mobile whilst on the go.

[Designs](https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=765-41541&mode=design&t=ySW01Qx6jiTlkRXk-4)

### Acceptance criteria

- [ ] When visiting the user profile of a room member, anyone who has the power level to kick will see an additional button to remove that member from the room.
- [ ] When the user clicks this button, if they have the power level to ban they will be prompted whether the action is permanent or if the member will be allowed to rejoin.
- [ ] Users that are kicked out of a room are no longer members of the room. They don’t show up in the room-member list anymore.
- [ ] Users that are banned should show at the end of the room-member list in a section only visible to members that have the right to ban room members. Visiting the profile of one of these users should show a button to unban that user.
- [ ] The new button should not be shown when visiting a user profile from a DM (1:1 room with `isDirect && isEncrypted`), only for regular rooms.
- [ ] Posthog Tracking:
- Event: RoomAdmin
- Property:
- -Kickuser
-- BanUser
-- UnbanUser

### Size estimate

S

### Dependencies

- https://github.com/element-hq/element-meta/issues/2263

### Out of scope

- Compatibility with other matrix clients that use the moderation APIs in other ways, such as supporting power levels outside of member, mod and admin.

### Open questions

```[tasklist]
### Questions
- [ ] PRD says that users can be unbanned by anyone who can kick and ban users, but in reality the API only cares about the power-level for banning. Do we specifically want to check both in the app or are we happy with just checking for ban?
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2258
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2357
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```
