### ISSUE TITLE
[Story] Change user rights

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-meta#2261]
### Description

* As a room admin.
* I want to be able to change the rights for each user-role.
* So that the room can be configured from mobile whilst on the go.

[Designs](https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=765-41549&mode=design&t=ySW01Qx6jiTlkRXk-4)

### Acceptance criteria

- [ ] When visiting the Edit Room Details Screen, the following operations should be shown to room admins:
    - Change room appearance:
        - Change the room name
        - Change the room avatar
        - Change the room topic
    - Create & delete content:
        - Send messages in the room
        - Delete messages from other users in the room
    - Administrate room members:
        - Invite users to the room
        - Kick users from the room
        - Ban users from the room
- [ ] Each operation should be configurable between one of Admin, Moderator or Member.
- [ ] Add an option to "reset" the changed user-rights to "default"
- [ ] The new settings should not be available for DMs (1:1 room with `isDirect && isEncrypted`), only for regular rooms.
- [ ] Posthog Tracking
- Event: RoomAdmin
- Property: 
- - change_room_name
- - change_room_avatar
- - change_room_topic
- - change_rights_sendmessages
- - change_rights_deletemessages
- - change_rights_inviteusers
- - change_rights_kickusers
- - change_rights_banusers

### Size estimate

S

### Dependencies

- None

### Out of scope

- We do not need parity with web, which has many more configurable options.
- Compatibility with other matrix clients that use the moderation APIs in other ways, such as supporting power levels outside of member, mod and admin.

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2259
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2358
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3035
```

```[tasklist]
### Other
```

**Comment by jmartinesp** [comment]
The story mentions 'Add an option to "reset" the changed user-rights to "default"' but I don't think we have anything that either returns those default values or resets them in the Rust SDK.
