### ISSUE TITLE
[Story] Show sections for roles in room-member list

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-meta#2263]
### Description

* As a user.
* I want to be able to easily find responsible users (room-admins, moderators) within a room.
* So that I know who to contact for moderation and/or administrative tasks.

[Designs](https://www.figma.com/file/A2pAEvTEpJZBiOPUlcMnKi/Settings-%2B-Room-Details-(new)?type=design&node-id=761-40822&mode=design&t=ySW01Qx6jiTlkRXk-4)

### Acceptance criteria

- [ ] When opening the room member list, members should be sorted into the following sections:
    1. Admins
    2. Moderators
    3. Members
    3. Banned Members (visible only to users that have the right to ban room members)
- [ ] This should have no impact on DMs (1:1 room with `isDirect && isEncrypted`), it is only a change for regular rooms.

### Size estimate

S

### Dependencies

- None

### Out of scope

- Compatibility with other matrix clients that use the moderation APIs in other ways, such as supporting power levels outside of member, mod and admin.

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2256
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2355
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3033
```

```[tasklist]
### Other
```

**Comment by daniellekirkwood** [comment]
it should be a quick win to replicate whatever y'all do on mobile to web for parity. please ping me with the designs/ screenshot when available and i'll create the item in our backlog :)
