### ISSUE TITLE
[Story] Show last visited rooms in the "start chat" screen

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2264]
### Description

Show a list of the last five recently accessed DM counterparts in the create a new chat view under the "new room" entry.
- Show the last five visited rooms or dms
- Taping on the room or dm opens the room or dm

### Acceptance criteria

- The user can enter the new room flow by tapping on the top right compose button in the room list
- On this screen they can search for individual users/DMs and either create a new one or access an existing one. At this same point the can chose to create a room instead of a DM
- It's on this screen that we would like to show the users their most recent **5** conversations so they can easily access them

### Leads

* Tech: @stefanceriu 
* Design: https://www.figma.com/file/AO7bFhGSUQt4IyBhmW26Cu/Room-List-%2B-Navigation-(new)?type=design&node-id=232-8678&mode=design&t=by5d8ot3EXZdevjE-0

### Size estimate

S

### Dependencies

- None

### Out of scope

- 

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2634
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2625
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3290
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by bmarty** [comment]
@VolkerJunginger you said IIIC that it was the same behavior on WA, but I cannot see where. Can you post some screenshot please?

Displaying an existing room list in the screen to create a room looks quite weird.

**Comment by VolkerJunginger** [comment]
![Screenshot 2024-03-19 at 08 38 01](https://github.com/element-hq/element-meta/assets/118339066/ce4e76bf-673d-4803-b358-a7ae2dacccf8)

**Comment by VolkerJunginger** [comment]
Tested and handed over to customer for sign of.
