### ISSUE TITLE
[Prep] Support for encrypting Rust stores with key data.

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-meta#2265]
### Description

Currently the Rust SDK expects a passphrase to encrypt the stores when creating a client. This string is run through password based key derivation (PBKDF2, with 200k iterations or so) to get a 256bits key which is fine, but for EX clients we can generate that key directly, and as pbkdf is slow by design this hurts the performance when opening the stores. Ideally we should add an API to pass the key directly.

(Related web issue: https://github.com/element-hq/element-web/issues/26821)

EXI and EXA are about to implement database encryption with the passphrase for Nightly users, but we would prefer not to roll this out to everyone until the API accepts key data, otherwise we'll have to deal with 2 different types of keys going forward (we're happy for Nightly users to be signed out at some point).

# Acceptance criteria
- EXI and EXA can pass a key directly to the SDK instead of converting it to a string first.

# Size estimate
M (might be small, but looking through the Rust code, there appears to be a lot of levels involved to me)

# Dependencies    
- None

# Out of scope
- 

# Subtasks
```[tasklist]
### Android
- [ ] Adopt the new database encryption key API, requiring anyone using the old one to login again.
```

```[tasklist]
### iOS
- [ ] Adopt the new database encryption key API, requiring anyone using the old one to login again.
```

```[tasklist]
### Rust
- [ ] Add support for supplying database key data as an alternative to a passphrase.
```

```[tasklist]
### Other
```
