### ISSUE TITLE
[Story] Username disambiguation

### ISSUE THREAD

**Issue by Velin92** [vector-im/element-meta#2269]
### Description

* As a user I want my username and the username of other users to not be spoofed by other malicious users by having the user ID being shown if multiple users in the same room share the same display name, so that I can always understand who really is the user having that display name, and if they are pretending to be someone else.

### Acceptance criteria

- If multiple users have the same display name in a room we should display also their user id in the timeline and in notifications
- The additional user ID displayed in the timeline should probably be displayed with a slightly different format than the display name, this is already done on web, this is for security reason to avoid users spoofing also the presence of the user ID in their name to circumvent the ambiguity check.

### Leads

* Tech: @Velin92 
* Design: @amshakal 

### Size estimate

S

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
[ ] - how to display the additional user ID in the timeline?
[ ] - How to display it in the notifications? (since we can't do different formatting there)
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/pull/2221
- [ ] https://github.com/element-hq/element-x-android/pull/2295
```

```[tasklist]
### iOS
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion
