### ISSUE TITLE
[Prep] Experiment room list filter

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2270]
### Description

We have several concepts and we need to be able to see the behavior on real data within the app. We are going to experiment it in specific builds of the apps
Here are the [designs](https://www.figma.com/file/AO7bFhGSUQt4IyBhmW26Cu/Room-List-%2B-Navigation-(new)?type=design&node-id=335-4418&mode=design&t=KUglvqiHulTS6XNF-0)

# Acceptance criteria
- PR build to share for testing the PoC
- Feature flag in the developer options to enable room filtering
- Start with those filters: "Rooms" and "People"
- Selecting a filter will remove mutually exclusive filter, ie selecting "Rooms" must hide "People"
- We need to be able to unselect a filter
- TBD: implement or mock "Unreads" or "Favorites" to check multiple filters

# Size estimate
M

# Dependencies    
- None

# Out of scope
- This is a PoC. We do not expect the code to go in production and on main/develop
- We can be light on the tests
- Some features may be just mocked (TBD)
- The option to set a room as favorite or low priority is another story

# Open questions
- [x]  what do we consider as unreads? https://github.com/element-hq/element-meta/issues/2270#issuecomment-1927214688

# Subtasks
```[tasklist]
### Android
 - [ ] https://github.com/element-hq/element-x-android/issues/2232
 - [ ] https://github.com/element-hq/element-x-android/issues/2233
 - [ ] https://github.com/element-hq/element-x-android/issues/2234
```

```[tasklist]
### iOS
 - [ ] https://github.com/element-hq/element-x-ios/issues/2339
 - [ ] https://github.com/element-hq/element-x-ios/issues/2340
 - [ ] https://github.com/element-hq/element-x-ios/issues/2341
```

```[tasklist]
### Rust
 - [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3020
 - [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3021
 - [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3022
```

```[tasklist]
### Other
 - [ ] Make people test it and manage feedbacks
```

**Comment by Velin92** [comment]
@Hywan today actually asked a very good question.
Wha do we consider as "Unread" do we want to consider Unread Notifications or Unread Messages?
If we consider Unread notifications, we will only display rooms that have unread content that respects the global or the custom push rules (so a mentions only will be displayed only if it has unread mentions,. but not if it has unread messages)
If we consider Unread messages, we will display any room that simply has unread messages regardless if it is muted, is in mentions only and so on.

So how this filter should behave? 
@VolkerJunginger

**Comment by VolkerJunginger** [comment]
Unread rooms are those that have been triggered by a "green badge" notification.
Also setting a room manually as "unread" triggers a "green" badge badge and should be shown here.

**Comment by Hywan** [comment]
@Velin92 I'm not sure the issue is closed ^^. Is it?

**Comment by Velin92** [comment]
> @Velin92 I'm not sure the issue is closed ^^. Is it?

Me and @manuroe decided to close it since we migrated to the final well defined story here:
https://github.com/element-hq/element-meta/issues/2283

Everything has already been moved

**Comment by Hywan** [comment]
Great, thanks!
