### ISSUE TITLE
WebR full support for dehydrated device v2

### ISSUE THREAD

**Issue by pmaier1** [vector-im/element-meta#2278]
```[tasklist]
### Tasks
- [x] wasm bindings
- [x] create and rehydrate device in js-sdk
- [x] create and rehydrate device in react-sk
- [x] add `dehydrated` flag in Rust
- [x] don't show dehydrated devices as normal devices
- [x] periodically recreate dehydrated device
- [ ] update MSC
```

**Comment by BillCarsonFr** [comment]
Adding the dehydrated flag on the device keys payload will break SQL lite store https://github.com/matrix-org/matrix-rust-sdk/issues/3132

=> We have to release EAR and EIR with a new sdk version before starting creating web dehydrated device

**Comment by uhoreg** [comment]
Current status:

- dehydration only enabled by setting `well-known` (or if dehydration key is in SSSS)
- dehydrated device is displayed differently in device lists (if the user only has one device marked as dehydrated) -- as a localizable string in device list, and hidden in session manager but shown as an enabled feature in encryption settings
- only enabled when unlocking SSSS by passphrase/key (not enabled when verifying with another device)
- creates new dehydrated device once a week, but only if Element is not restarted/reloaded (dehydration key only stored in memory)

Work for future phases

- persist dehydration key, so that dehydrated devices can be recreated even after restarts
- add UI to enable dehydration (don't require enabling in `well-known`)
- gossip dehydration key?
- look into possibility of not encrypting to dehydrated device if recipient has enough other devices available

**Comment by uhoreg** [comment]
Relevant PRs:

- https://github.com/matrix-org/matrix-rust-sdk/pull/3164 ETA Mar 18
- https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/pull/104 ETA Mar 19
- https://github.com/matrix-org/matrix-js-sdk/pull/4062 ETA Mar 21
- https://github.com/matrix-org/matrix-react-sdk/pull/12316 ETA Mar 25

**Comment by uhoreg** [comment]
Screenshots:

Dehydrated device is removed from list of devices in Sessions tab.

![Image](https://github.com/element-hq/element-meta/assets/1012976/905865d4-deb3-446d-9788-10fce5e1f7e4)

Presence of dehydrated device is indicated in Security & Privacy tab (called "Offline device" for now)

![Image](https://github.com/element-hq/element-meta/assets/1012976/48a9d3b1-fe1a-44df-b89d-d746728f71ba)

In user info sidebar, dehydrated device is shown as "Offline device" (maybe we want to add some help text somehow?)

![Image](https://github.com/element-hq/element-meta/assets/1012976/d4467532-e6b5-4efa-9a46-a2e93107ffdb)

**Comment by pmaier1** [comment]
Thanks! I think we can find a better design for this but it's good enough for now. We should think about improvements once we plan delabsing it.

**Comment by uhoreg** [comment]
I've documented what's left to be done for phase 2 at https://github.com/element-hq/element-web/issues/27336
