### ISSUE TITLE
[Story] Show filters for room-list

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2283]
### Description

As a user of EX I want to be able to filter my roomlist in order to get a faster overview.

Create filters for:
- unread: All room that have a green badge or @ (triggered by new messages or marked manually as unread)
- favourites: All room w. the favourite flag
- people: Only DMs with max. 2 members
- rooms: only rooms; no DMs with max 2 members

It should be possible to combine filters for example:
- Rooms + unread
- Favourites + people

Sorting
- The sorting of the rooms is always chronological: Rooms with the most recent message first

Updating the view
- If a user has a room filtered and a new room is added to that filter it should be visible instantly.
- Example: 
  - The user has the room on "Unread" and is on the room-list
  - The user gets a new message in room that is not in the filtered view
  - The room should appear on top of the filtered view.

### Size estimate

M

### Dependencies

- None

### Open questions

```[tasklist]
### Questions
- [x] ~~Where should invites live?~~ We have an experimental story about it https://github.com/element-hq/element-meta/issues/2320
- [x] ~~Sorting of rooms in the room list and how that impacts room filters~~ For now we will use the current chronological ordering that we already have
- [x] ~~UI of filters~~ - we have new figma
- [x] ~~Animation of filters~~ Animations as we already have but the ordering is not kept, like Google's File app.
- [x] ~~Order of filters - should unreads be first?~~ Yes
- [x] ~~How should we turn filters on and off? Should it just be a toggle or do we need additional settings for it?~~ Filters are immediately available for everyone
- [x] What should fall under unreads filter? - Any room that contains unread notifications
- [x] ~~Search behaviour with filters (we probably want to hide them as soon as the search bar is focused)~~ no filters during search
- [x] ~~Advanced setting? https://github.com/element-hq/element-meta/issues/2283#issuecomment-1929101137~~ No settings.
- [x] ~~Empty state for unreads filter~~ We have a non-final but usable design that can be used for now, also if there are no rooms at all, we won't show the filters
```

### Subtasks

```[tasklist]
### Android
 - [ ] https://github.com/element-hq/element-x-android/issues/2232
 - [ ] https://github.com/element-hq/element-x-android/issues/2233
 - [ ] https://github.com/element-hq/element-x-android/issues/2234
 - [ ] https://github.com/element-hq/element-x-android/issues/2486
```

```[tasklist]
### iOS
 - [ ] https://github.com/element-hq/element-x-ios/issues/2339
 - [ ] https://github.com/element-hq/element-x-ios/issues/2340
 - [ ] https://github.com/element-hq/element-x-ios/issues/2341
 - [ ] https://github.com/element-hq/element-x-ios/issues/2520
```

```[tasklist]
### Rust
 - [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3020
 - [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3021
 - [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3022
```

```[tasklist]
### Other
```

**Comment by Velin92** [comment]
@VolkerJunginger 
Do we still want to have the filters being a toggle in the advanced settings? And if so, is it enabled by default or is it disabled?

**Comment by manuroe** [comment]
All done. QA will happen at the epic level.
