### ISSUE TITLE
Posthog | Increase decryption failure grace period

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#2303]
The current grace period for visible UTDs is set to 4s.

We want to increase it to 30s

```[tasklist]
### Tasks
- [ ] EIR set DecryptionFailureTracker GRACE_PERIOD to 30s
- [ ] EAR set `DecryptionFailureTracker` GRACE_PERIOD_MILLIS to 30s
- [ ] https://github.com/element-hq/element-web/issues/27093
- [ ] EIX set decryption failure tracker grace period to 30s
```

**Comment by BillCarsonFr** [comment]
See https://github.com/element-hq/element-meta/issues/2300

**Comment by BillCarsonFr** [comment]
We are going to instead introduce a timeToDecrypt property to the event, that will allow to do the filtering on posthog side (if timeToDecrypt > 30 we consider permanent failure)

See https://github.com/element-hq/element-meta/issues/2332

Might close this issue and switch to that solution instead.

**Comment by BillCarsonFr** [comment]
Closed in favor of https://github.com/element-hq/element-meta/issues/2332
