### ISSUE TITLE
Expected UTDs: Hide device-relative historical UTDs

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#2313]
A freshly logged in session will have access to event in the joined rooms, but not to the keys for the messages as the device didn't exist when the event were sent.
The new device has to go through the verification process in order to get access to the keys and properly display history.

We are talking here about `Device-Relative` history:
<img width="857" alt="image" src="https://github.com/element-hq/element-meta/assets/9841565/bea9c97c-a805-414f-85bb-197d4fd936aa">

Currently EIX is hiding such history until the device has access to backup:

![image](https://github.com/element-hq/element-meta/assets/9841565/e0ef355a-bb20-4de1-8d03-16313cefec31)

## Technical Inputs

How to detect when an event is historical to the current device?

Currently EIX is using events `origin_server_ts` of events ([isItemInEncryptionHistory](https://github.com/element-hq/element-x-ios/blob/14d76d98605677d4515441b571144d842f2b9b57/ElementX/Sources/Services/Timeline/TimelineController/RoomTimelineController.swift#L364)). It's comparing the local creation date of the device ( since the unix epoch) to the event `origin_server_ts` (Timestamp in milliseconds since the unix epoch on originating homeserver when this event was sent.)

Some downside on this approach is that if the device local time or server local time is wrong it could messed up things.

Another approach could be to use the API end-point used to get the messages?
- From sync: If not an initial sync it's not an historical message.
- From sync: If an initial sync, could be a mix of it, but mainly historical? (unless a clear cache is done)
- From [/message](https://spec.matrix.org/v1.9/client-server-api/#get_matrixclientv3roomsroomidmessages) (back pagination). Would be mostly historical to the current device (unless there was a clear cache?)
- From [/relation](https://spec.matrix.org/v1.9/client-server-api/#get_matrixclientv1roomsroomidrelationseventid) (threads?). Would be mostly historical?

It's anyhow hard to see if something is really device relative history, as the process of sending is inherently racy.
There might be some events that are shown were they shouldn't (sent around the same time the device is logged in but before propagated to anyone)

## Proposal

- Hide historical messages (expected UTD) until the user has access to backup
- Hide historical messages (expected UTD) while keys are beeing downoaled.
- Once the keys have been downloaded, show the events.

If an UTD has not be displayed on screen, it should not be reported to analytics.

## Tasks

```[tasklist]
### Tasks
- [x] EX Hide device relative historical messages until the device has access to backup.
- [x] WebR: Hide device relative historical messages until the backup has been downloaded.
- [x] WebR: make sure that UTDs due to this are reported separately in Posthog
```

## Known possible issues

- If we hide the device relative historical messages, and the users manually import keys from a file, what should we do?
- After the backup import, some messages might still be in UTDs (key was not in the used backup). That's fine, we should just display the UTD and report to analytics

**Comment by richvdh** [comment]
Probably requires a fix to https://github.com/element-hq/element-web/issues/27009?

Edit: not really. The two are orthogonal.

**Comment by richvdh** [comment]
> There might be some events that are shown were they shouldn't (sent around the same time the device is logged in but before propagated to anyone)

This is somewhat related to https://github.com/element-hq/element-meta/issues/2314, and dealing with the race condition might have a similar solution.

**Comment by richvdh** [comment]
As a first step, we will not hide the events altogether, but display a placeholder.

**Comment by BillCarsonFr** [comment]
Note: we should ensure that it's also hiding historical UTDs in thread view.

**Comment by richvdh** [comment]
Rough idea for approach here:

* Add a new `code` value to `DecryptionError` which reflects a message that is older than the device, when we don't have backup enabled.
* Update `DecryptionFailureBody` to display the failure differently to the user
* Update `DecryptionFailureTracker` to report the failure differently to posthog.

More detailed work:

- [x] Move `DecryptionError` out of legacy crypto code and into `crypto-api`. Replace its `code` with an enum: https://github.com/matrix-org/matrix-js-sdk/pull/4126 
- [x] Refactor `EventDecryptor.attemptEventDecryption` so that all the logic isn't inside a `catch` block. https://github.com/matrix-org/matrix-js-sdk/pull/4138
- [x] Expose a new method `PerSessionKeyBackupDownloader.isBackupConfigured()`.
- [x] When we get a `MissingRoomKey` or `UnknownMessageIndex`, compare the timestamp on the event with the creation time of our own device (available via [`Device.firstTimeSeen`](https://matrix-org.github.io/matrix-rust-sdk-crypto-wasm/classes/Device.html#firstTimeSeen)), and check `isBackupConfigured`. If it's an old event, and backup is not configured, use different `code`s on `DecryptionError`. https://github.com/matrix-org/matrix-js-sdk/pull/4139
- [x] `DecryptionFailureBody`: use different text for new error codes. https://github.com/matrix-org/matrix-react-sdk/pull/12391
- [x] `DecryptionFailureTracker`: use different error code. https://github.com/matrix-org/matrix-react-sdk/pull/12389
- [x] Playwright tests (some may exist and just need updates). https://github.com/matrix-org/matrix-react-sdk/pull/12391
    - [x] Old event, with backup disabled. 
    - [x] Enabling backup changes the UI for the event *even if the key isn't in the backup*.

**Comment by BillCarsonFr** [comment]
Some design exploration https://www.figma.com/file/a1NWmg6mOi2VZuSgaJx6nD/Displaying-UISI?type=design&node-id=1-12313&mode=design&t=6hb0XIH9Ftv5SI46-0

**Comment by richvdh** [comment]
Decision tree for the text to be displayed:

```mermaid
flowchart TD
A{Timestamp on the message postdates the creation of our device}
A -- Yes --> X
A -- No --> B
B{Is there a backup}
B -- No --> Y
B -- Yes --> C
C{Is the device verified}
C -- No --> Z
C -- Yes --> X

X([Normal UTD error])
Y([History is not available on this device])
Z([You need to verify this device])
```

**Comment by andybalaam** [comment]
Discussion today suggests the full flow diagram implemented looks like this:

```mermaid
flowchart TD
A{Is the message newer than the device?}
A -- No --> B
A -- Yes --> X
B{Is there a backup on the server?}
B -- No --> Y
B -- Yes --> C
C{Is backup working on this device?}
C -- No --> D
C -- Yes --> X
D{Is this device verified?}
D -- No --> Z
D -- Yes --> X

X([Normal UTD error])
Y([History is not available on this device])
Z([You need to verify this device])
```

In matrix-js-sdk most of this is implemented when we [choose a `DecryptionFailureCode`](https://github.com/matrix-org/matrix-js-sdk/blob/5bcd26e5062d2e4a6724a8f260e1760dbf06273c/src/rust-crypto/rust-crypto.ts#L1996) and some ("Is this device verified?") when we [display a message to the user](https://github.com/element-hq/element-web/blob/d68c5a26af1aa8e17300eb3e0d3f76a804f89c3d/src/components/views/messages/DecryptionFailureBody.tsx#L27).

I am looking at this as I am implementing similar logic in matrix-rust-sdk, probably in [UtdCause::determine](https://github.com/matrix-org/matrix-rust-sdk/blob/e1f0037fd5eb3b263a471a0c515daf6bf95cd784/crates/matrix-sdk-crypto/src/types/events/utd_cause.rs#L94).

**Comment by andybalaam** [comment]
(I am working on https://github.com/element-hq/element-meta/issues/2638 )
