### ISSUE TITLE
[Story] Show invites as part of the room list

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2320]
### Description

To do:
- Remove the separate invites list 
- Move the invites into the room list
- Add an invites filter
- Tapping the cell outside "Decline" and "Accept" buttons open the room preview

Designs https://www.figma.com/file/AO7bFhGSUQt4IyBhmW26Cu/Room-List-%2B-Navigation-(new)?type=design&node-id=363-23877&mode=design&t=STKKbY6CQ5GQkDmM-0

On the room-list cell:
- Show the same info and call to actions as we do now in the separate room list.

Read the PRD https://docs.google.com/document/d/1h0tlg3dc_AEw7xxjNugwoaYVyY555zXW_lpXuNhUzA8/edit#heading=h.vvz62qbzsphw for more info on the why.

### Acceptance criteria

- TBD

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2707
- [x] [Task] Cleanup - Remove old invites list
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2670
- [x] [Task] Cleanup - Remove old invites list
```

```[tasklist]
### Rust
- [x] [Task] Cleanup - Remove invites list and feature flag
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion
