### ISSUE TITLE
[Story] Join a public room

### ISSUE THREAD

**Issue by Velin92** [vector-im/element-meta#2340]
## Story
This story is related to the first deliverable for BWI for Apr 2024.

## Requirements
- As a user, If the room allows it, I would be like to see and preview a room I have searched for. (stretch goal)
- As a user, if the room allows it, I would like to be able to join the public room.

## Leads
Tech: @Velin92
Design: @americanrefugee 

## Size Estimate
M

## Stretch Goals
- Previewing a room is a stretch goal, in that case we can just offer to join the room directly from the search view, since it requires some big SDK refactors first

## Out of scope
- Knocking is out of scope.

## Design
https://www.figma.com/file/TKbfHw1zboMfAfP9xxSTsF/Search?type=design&node-id=249-61362&mode=design&t=Y4AdaYGpeDyILBZa-4

## Open questions

```[tasklist]
### Questions
- [x] ~~Designs? Without those is hard to estimate iOS and Android work, and create tasks for them~~
- [x] ~~Do we want to navigate also towards rooms that can't be previewed? In that case should we show some kind of "This room can't be previewed" error/alert/screen ?~~ We have a non previewable room screen where we propose the user to join if possible
- [x] ~~What about the rare edge case of rooms that can't be previewed... and can't be joined?~~ We can just not show them
- [x] ~~Can I also just join the room by tapping the join button without previewing it directly from the search?~~ We want to always show a room preview/ or a room screen even without preview by proposing the user to join
- [x] ~~Does the SDK Timeline support room previews as of right now?~~ Yes but you won't be able to receive new messages until you either reload the room, or join. However we still need to expose a way for the public room API to be used on FFI, and generate the timeline
```

### Subtasks

```[tasklist]
### Design
- [x] We need designs for how the preview and the join should happen
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/3260
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2590
```

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2578
```

**Comment by Velin92** [comment]
Cloned from: https://github.com/element-hq/element-internal/issues/560
