### ISSUE TITLE
[Story] Click on room permalink

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-meta#2341]
### Description

As a user I want to navigate to the room when I click on the room permalink so that I can see the timeline of the room, or be able to join the room.

Several cases must be handled:

**The room is the same than the current room:** 
In this case, there is no action to perform. 

**The room is not the same room**

_The user is already a member of the room_
The timeline is opened and added to the backstack, i.e. the user can navigate back to the current room and the timeline position is not lost.

The backstack is set back to default whenever the user opens a room through an other entry point (for example notification).

_The user is not a member of the room_ 
- User is invited to the room: Show room startpage with the option to accept or reject the invitation
- The room is public. Show room startpage with the option to join the room. 
 
- The room is not public and cannot be joined without an invite: Go Berghain and user cannot join.

Maybe:
- The room is a space: in this case I get the application can display an error dialog to inform that Spaces are not supported yet in EX.

### Acceptance criteria

- TBD

### Size estimate

M

### Dependencies

- None

### Out of scope

- The room is  knockable. In this case the user will see a screen with action to knock to the room. Knocking is currently not supported.
- Note that room preview (messages) for public room is out of the scope.

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2642
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2632
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3298
```

```[tasklist]
### Other
```
