### ISSUE TITLE
[Story] Render permalinks in the timeline

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-meta#2342]
### Description

As a user, I want to be able to visually identify permalink included in the message rendered in the timeline, so that I can understand that I can click on it, and I can expect that I will be redirected to the correct target. The permalink will render as pills and the link will be replaced by more useful information, like the room name, or the user display name.

- Permalink for users are rendered correctly on the timeline. Generally permalink for users are for user members, but it can be any matrix.to link for users.
- Permalink for rooms are rendered correctly on the timeline. Room details have to be retrieved, so that room display name can replace the link. Note that depending on the room state, the room details can be retrieved even if the user is not a member of the room.
- Permalink for messages are rendered correctly on the timeline. Links to message contain the room Id, so same than for room, it can be possible to retrieve the room details even if the user is not a member of the room.

Note that some cases may already be implemented in some EX mobile clients.

[Figma](https://www.figma.com/design/2qAtUobdikIwVBFHmZcLvb/Permalinks?node-id=215-1917&t=Eo3CxDFUMfb5yuS2-0)

### Leads

* Tech: @Velin92 
* Design: 

### Acceptance criteria

- TBD

### Size estimate

M

### Dependencies

- None

### Out of scope

- Permalink auto completion in the editor will happen in a separate story.

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2643
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2633
```

```[tasklist]
### Rust
```

```[tasklist]
### Bugs
- [ ] https://github.com/element-hq/element-x-ios/issues/3852
```

**Comment by mxandreas** [comment]
While we can implement the pill in the timeline, it would make sense to also do it in the editor if we start working on this already. Thus, either enlarge the scope of this item or create a separate story for editor and put them under one epic.

**Comment by Velin92** [comment]
https://www.figma.com/design/2qAtUobdikIwVBFHmZcLvb/Permalinks?node-id=215-1917&t=z7tevkUV6nrS3uhE-0 @amshakal could you double check if these design for pills are up to date?

For user mentions, we used to show an avatar but later before release it was decided to scrap the avatars entirely and just keep them simple, containing only text, maybe that's what we want to do also for room pills and message pills?

**Comment by Velin92** [comment]
> https://www.figma.com/design/2qAtUobdikIwVBFHmZcLvb/Permalinks?node-id=215-1917&t=z7tevkUV6nrS3uhE-0 [@amshakal](https://github.com/amshakal) could you double check if these design for pills are up to date?
> 
> For user mentions, we used to show an avatar but later before release it was decided to scrap the avatars entirely and just keep them simple, containing only text, maybe that's what we want to do also for room pills and message pills?

@americanrefugee if you can also double check since Amsha is not available, these designs are quite old and don't match what we currenlty have for users

**Comment by Velin92** [comment]
Okay these are likely the designs we want to use for rooms and messages:
https://www.figma.com/design/Ni6Ii8YKtmXCKYNE90cC67/Timeline-(new)?t=nS9KuQNz1fwSYTTG-0

But let's wait confirmation from @amshakal

**Comment by americanrefugee** [comment]
Important: These should also be aligned with [room alias permalinks](https://www.figma.com/design/7ZJzm6BfnZFpjk9MnCfFH3/ER-124%3A-Join-Room-by-Its-Alias?node-id=1-3).

**Comment by Velin92** [comment]
so far I have tested it on EW all the following cases:

- if a permalink to an event using the room ID can't resolve the room it shows a pill with "Message in Room"
- if a permalink to an event using room alias can't resolve the room it shows a pill with "Message in Room"
- If a permalink to a room ID can't resolve the room it shows a pill with the raw room id displayed
- If a permalink to a room alias can't resolve the room it shows a pill with the room alias displayed

Do we want to replicate the same behaviour of EW?
Or we should avoid leaking the raw room id and the room alias for these last two cases?

**Comment by mxandreas** [comment]
> Do we want to replicate the same behaviour of EW?

I do not immediately see any significant and simple improvements to what EW does. Thus, propose to just replicate what it does for sake of consistency.
