### ISSUE TITLE
[Story] Permalink: external links

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-meta#2347]
### Description

As a user clicking on a matrix/element link from an external applications (Email/Browser/etc.), I want Element X to be opened at the correct target so that I can see more detail on the data behind the link.

This apply to matrix.to link, such as `https://matrix.to/#/#element-x-android:matrix.org`, as well as element link, such as `https://app.element.io/#/room/#element-x-android:matrix.org` for instance, but is also applicable to event, and user links.

This should not be a lot of work, as soon as (internal) permalink navigation has been implemented.

_Note_: the application can intercept the link even if there is no current session. In this case, the user should be redirected to the login screen, and follow the regular FTUE workflow. Ideally at the end the permalink can be handled so that the user finally see the target. But it is acceptable that once logged in the user has to go back and click again on the link.

### Acceptance criteria

- TBD

### Size estimate

M

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2648
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2638
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
- [ ] https://github.com/element-hq/sre-internal/issues/3083
- [ ] https://github.com/element-hq/element-web/pull/27439
```

**Comment by bmarty** [comment]
Closing since all tasks are handled.
