### ISSUE TITLE
[Story] Public Room search NSFW filtering

### ISSUE THREAD

**Issue by Velin92** [vector-im/element-meta#2353]
### Description

* As a user I want the possibility of turning on and off such a filter (will be on by default, and this might be a stretch goal)
* As a user I want the results of the public room search to not contain any NSFW content if the filter is on
* As a user I also want the search to not get started if the search term contain any blocked/filtered term considered NSFW

### Acceptance criteria

- TBD

### Size estimate

S

### Dependencies

- None

### Out of scope

- Turning OFF the filter.

### Open questions

```[tasklist]
### Questions
- [ ] What keywords should we filter?
- [ ] Should the keywords belong to different languages too? Should these other languages keywords only be used on specific locales or on all of them?
- [ ] Maybe the community could manage the keywords, and add them
- [ ] Do we also want to PREVENT completely the search if one of these keywords is search? or just filter out the rooms that contain any of these?
- [ ] Should we filter rooms based on name, topic or both?
- [ ] Could we use parental controls API to check if the filter can toggled? (Maybe we won't have it toggleable for the first iteration)
- [ ] Is this all really worth it? Public room search could be an internal feature only not available publicly
```

### Subtasks

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3214
```

```[tasklist]
### Other
```

**Comment by Velin92** [comment]
We are also exploring the possibility of having the room search being not a public feature, but an internal feature only.

**Comment by Velin92** [comment]
We don't do any filtering since the public search will not be available publicly
