### ISSUE TITLE
[Story] Copy permalink for Event

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-meta#2355]
### Description

As a user I want to be able to get a reference to a message (Event), also known as permalink so that I can post it to any room.

Element Web use the "Share" action to reveal the permalink of a message, but on the current mobile application, "Share" action allow to share the text to any other application.

### Acceptance criteria

- The bottom sheet of a message have a new "Permalink" action, that copy the permalink of the selected event to the clipboard, and a UI feedback is shown to the user to validate that the link has been copied.
- The permalink is a valid matrix.to URL.

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2650
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/2640
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3259
```

```[tasklist]
### Other
```
