### ISSUE TITLE
[Story] Experiment: Hide grey dots as default

### ISSUE THREAD

**Issue by VolkerJunginger** [vector-im/element-meta#2358]
### Description

Implementation
- Hide the grey dot in the room list by default 

Ad a new setting (toggle) in "notification-settings -> additional  settings" 
- Text: Show a badge for all rooms with unread messages". 
- The setting is off by default
- When the setting is active show grey dots again

Ad posthog tracking to the setting
- Event: Interaction
- Property: ShowAllUnreadRooms

**Stretch goal: AB-Test**
- Make this an AB-Test.

Group A: UserID is an odd-number; Default is off
Group B: Default is on

Tracking:
Ad a property for UsergroupA or UsergroupB to the Interaction Event and to the Screen-Event (for the baseline ( comuting visitors)

### Acceptance criteria

- TBD

### Leads

* Tech: <GitHub id>
* Design: <GitHub id>

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2583
```

```[tasklist]
### iOS
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by manuroe** [comment]
We could[ PostHog Feature Flags](https://posthog.com/docs/feature-flags) on the default settings to check what users prefer. It is available on our posthog instance.

**Comment by jmartinesp** [comment]
> We could[ PostHog Feature Flags](https://posthog.com/docs/feature-flags) on the default settings to check what users prefer. It is available on our posthog instance.

Will those work even if the user didn't opt-in for analytics? The code seems to suggest it does, but I'm not 100% sure.

Also, if we use those the users won't be able to change the enabled/disabled state unless we wrap the Posthog FF provider with some local based one and make the local one take precedence. AFAIK our Android code is not really prepared for that.

**Comment by VolkerJunginger** [comment]
We will not do this. Follow up ticket soon.
