### ISSUE TITLE
[Story] EX: PiP Support

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2386]
### Description

* As a user in a call
* I want to be able to enable PiP so that I can interact with EX or any app on my device while staying in the call
* So that I can efficiently work

### Acceptance criteria
In addition to the ones from the epic:
- The current speaker is PiPed
- Screen share or self is never PiPed
- Displayname are not part of the PiP

### Leads

* Tech: @pixlwave 
* Design: @americanrefugee 

### Size estimate

None

### Dependencies

- None

### Out of scope

- We do not need to manage audio. This is about "Picture"
- Android devices that does not natively support PiP 

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/pull/3159
- [ ] https://github.com/element-hq/element-x-android/issues/3326
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/pull/3174
- [ ] https://github.com/element-hq/element-x-ios/pull/3181
- [ ] https://github.com/element-hq/element-x-ios/pull/3190
```

```[tasklist]
### VoIP
- [x] Do not display displayname in PiP mode -> It is no more required as iOS can now display it natively
- [x] Do not present screen-share in PiP tile -> During testing we decided having viz on ongoing screen-share might be helpful.
- [x] iOS: Inform the app when the call is running to manage unknown error (like no network to load the widget). We need it for widget and webapp cases
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion
