### ISSUE TITLE
[Story] Suggestion for room alias

### ISSUE THREAD

**Issue by bmarty** [vector-im/element-meta#2430]
### Description

* As a user
* I want to easily insert link to other room in a message
* by typing `#` and some character and have a list of room suggestions

Could be something like:

<img width="273" alt="image" src="https://github.com/element-hq/element-meta/assets/3940906/c6f0a235-1875-48ff-898f-91ba4136513e">

### Acceptance criteria

- TBD

### Leads

* Tech: <GitHub id>
* Design: <GitHub id>

### Size estimate

M

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2907
```

```[tasklist]
### iOS
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by bmarty** [comment]
Note: this has been implemented on Android under a disabled feature flag in https://github.com/element-hq/element-x-android/pull/3322
