### ISSUE TITLE
Unable To Decrypt meta issue

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#245]
This is the meta issue relating to all "Unable to Decrypt" problems, a.k.a "Waiting for this message, this may take a while", aka "UISI" [1].

There are many potential causes of this issue; a detailed list is below. Many of the causes are fixed in modern clients, but there are still a number outstanding.

**If you receive an "unable to decrypt" message**: we need your help to resolve the problem! The information below describes how to send us the logs we need to understand what went wrong in your particular case.

 * [1]: A decryption failure normally manifests when the recipient doesn't receive the keys for a particular encryption session; hence the acronym UISI: "Unknown inbound session ID". Nowadays the acronym UTD (unable to decrypt) is generally preferred.

## Needed information to resolve a reported issue

Reports from users are hugely helpful in identifying and prioritising the causes of Unable to Decrypt errors.

In order to properly debug an Unable To Decrypt error, we need logs from the receiver of the message (the one seeing the issue) **and those from the sender**. We generally can't debug issues without logs from both sides. Instructions on sending problem reports (aka "rageshakes") from within various clients are below.

In your problem report, please use the word "decrypt" or "UTD", and **identify which event you can't read**. Either include the event ID, or something like `message from @dave:example.com at 10:10`. For example, you might write `UTD $173031096849423vSpOu:matrix.org`.

**If you'd like us to feed back to you on why you can't decrypt a message, open a *new* issue in the Github project for your client, and mention that issue in your problem report as well.**

On the sender side, the description is less important: just write "Bob can't decrypt me" or something.

**Sending a rageshake from Element Web:**
- Click on your avatar in top left part of the screen.
- Select "All Settings".
- Select "Help & About".
- Fill in the description as above.
- Then click on the `Send logs` button.

(Protip: although the dialog tells you you need to create a github issue, that is only necessary if you want us to feed back to you about what went wrong.)

Alternatively:

- From the composer in any room, type `/rageshake <description>`, where `<description>` is as above.
- A dialog box opens. Click on the `Send logs` button.

**Sending a rageshake from Element X:**
- Click on your avatar in the top left part of the screen.
- Select "Report a problem".
- Enter a description, as above.
- Ensure that "Allow logs" is enabled.
- Click "Send".

**How to send a rageshake from (classic) Element Android:**

- Tap on the top right button on the home screen.
- Select `Report Bug`.

**How to send a rageshake from (classic) element iOS:**

- Open the top left drawer.
- Select the `Feedback` button at the bottom.

----

## Causes of Unable to Decrypt errors

We categorize the main sources of UISI errors as follow:

#### Sender Side

- [x] ~~The sender failed to send the keys. There’s no consistent retry logic on network error, so key sending is fragile. https://github.com/element-hq/element-meta/issues/673. Test: [TestClientRetriesSendToDevice](https://github.com/matrix-org/complement-crypto/blob/main/tests/to_device_test.go#L19)~~
- [x] ~~https://github.com/element-hq/element-web/issues/20962~~
- [x] ~~The keys may be sent slowly:~~
  - [x] ~~https://github.com/element-hq/element-web/issues/24680 Test: [complement-crypto#34](https://github.com/matrix-org/complement-crypto/issues/34)~~
  - [x] ~~https://github.com/element-hq/element-web/issues/24681~~
- [x] ~~Sharing historical room keys on invite is slow and should prioritise recent messages https://github.com/vector-im/element-web/issues/23778~~
- [x] ~~https://github.com/vector-im/element-web/issues/24138~~
- [x] ~~https://github.com/vector-im/element-web/issues/23792~~
- [x] ~~https://github.com/matrix-org/matrix-rust-sdk/issues/3127~~
- [ ] https://github.com/element-hq/element-ios/issues/7751
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/1415
- [ ] https://github.com/element-hq/element-web/issues/31842
- [ ] https://github.com/element-hq/element-web/issues/27285
- [ ] https://github.com/element-hq/element-web/issues/27334
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3354
- [x] https://github.com/element-hq/element-meta/issues/2425
- [ ] Delayed membership responses in /sync cause UTDs:
  - [x] https://github.com/matrix-org/matrix-rust-sdk/issues/3622
  - [ ] https://github.com/matrix-org/matrix-js-sdk/issues/4291
- [ ] https://github.com/element-hq/element-android/issues/8873
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/3959
- [x] https://github.com/element-hq/element-ios/issues/7844
- [x] https://github.com/element-hq/element-call/issues/2907
- [ ] https://github.com/element-hq/element-android/issues/9009
- [ ] https://github.com/element-hq/element-android/issues/9030
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/5061
- [ ] https://github.com/element-hq/element-meta/issues/2450
- [x] https://github.com/element-hq/synapse/issues/19478

#### Receiver Side

- [x] ~~https://github.com/vector-im/element-meta/issues/762 Test: [complement-crypto#37](https://github.com/matrix-org/complement-crypto/issues/37)~~
  - [x] ~~https://github.com/element-hq/element-web/issues/23113~~
- [x] ~~https://github.com/vector-im/element-android/issues/5905 (No test since no specific testcase is known - closed because Rust is sufficiently different)~~
- [x] ~~https://github.com/vector-im/element-web/issues/24450~~
- [x] ~~https://github.com/vector-im/element-web/issues/24682 Test: [complement-crypto#38](https://github.com/matrix-org/complement-crypto/issues/38)~~
- [x] ~~https://github.com/element-hq/element-x-android/issues/2520~~
- [ ] Broken olm: Olm sessions sometimes get out of sync, resulting in undecryptable messages. 
  - [x] ~~https://github.com/vector-im/element-ios/issues/7479 (Cannot reproduce, so no test)~~
  - [x] ~https://github.com/vector-im/element-ios/issues/7480~
  - [x] ~~https://github.com/vector-im/element-web/issues/25723 Test: [complement-crypto#35](https://github.com/matrix-org/complement-crypto/issues/35)~~
  - [x] ~~Element X iOS: https://github.com/matrix-org/matrix-rust-sdk/issues/3110~~
  - [x] https://github.com/element-hq/element-meta/issues/2356
  - [ ] https://github.com/element-hq/element-meta/issues/2310
- [x] https://github.com/vector-im/element-web/issues/14174
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/3768
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/3993
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/4189
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/4196
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/4444
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/4445
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/5474
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/5447
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/5703
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/5798
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/6133
- [ ] https://github.com/element-hq/element-meta/issues/2421
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3427
- [ ] https://github.com/element-hq/element-x-android/issues/3471
- [ ] https://github.com/element-hq/element-web/issues/28016
- [ ] https://github.com/element-hq/element-web/issues/28060
- [ ] https://github.com/element-hq/element-web/issues/28312
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/4429
- [ ] https://github.com/element-hq/element-x-ios/issues/4371
- [ ] https://github.com/element-hq/element-web/issues/32822

##### Messages you should not expect to be able to decrypt, but where the UI could be clearer about it

- [x] ~Some room history \(pre-invite for example\), should never be decryptable by you. This kind of history should probably be hidden or displayed differently.~
- [x] https://github.com/element-hq/element-meta/issues/2313: New devices cannot decrypt existing history until they have access to key backup. Now (April 2025) mitigated on EX and EW with clearer messaging, but classic clients still give confusing messaging.
- [ ] https://github.com/element-hq/element-web/issues/27577
- [ ] https://github.com/element-hq/element-meta/issues/2610

### Server Issues

- [x] ~To-device messages can take a long time to get sent over federation~
  - [x] ~https://github.com/matrix-org/synapse/issues/15161~
  - [x] ~https://github.com/element-hq/synapse/issues/16680~
  - [ ] https://github.com/element-hq/synapse/issues/8691
- [x] ~To-device messages may get lost on the server~
  - [x] ~https://github.com/matrix-org/synapse/issues/9533~
  - [x] ~https://github.com/matrix-org/synapse/issues/15335~
  - [x] ~https://github.com/matrix-org/synapse/issues/16681~
- [x] ~https://github.com/matrix-org/sliding-sync/pull/390~ 
- [x] ~https://github.com/element-hq/synapse/issues/17117~
- [ ] https://github.com/element-hq/element-meta/issues/2411: E2E Device lists can get out of sync with the devices actually present in a room, causing keys not to be sent. This can happen for various reasons: see the linked issue.
- [x] https://github.com/element-hq/element-meta/issues/2155
- [ ] https://github.com/element-hq/synapse/issues/16940
- [ ] https://github.com/element-hq/synapse/issues/17050
- [x] https://github.com/element-hq/synapse/issues/17035
- [ ] https://github.com/element-hq/synapse/issues/18143

### Key Backups
- [x] ~https://github.com/matrix-org/matrix-rust-sdk/issues/3197~
- [x] ~https://github.com/element-hq/element-meta/issues/2338~
- [x] ~https://github.com/famedly/matrix-dart-sdk/issues/1739~
- [ ] https://github.com/element-hq/element-meta/issues/2322 (only a problem on Element Classic nowadays I think?)
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3875
- [x] https://github.com/element-hq/element-meta/issues/2595
- [ ] https://github.com/element-hq/element-meta/issues/2596
- [ ] https://github.com/element-hq/element-web/issues/29872
- [ ] https://github.com/element-hq/element-meta/issues/2891
- [ ] https://github.com/element-hq/element-meta/issues/2642

### Protocol Issues

- [x] ~A client has been offline for too long and the senders have run out of one time keys. This will be addressed by the proposal to maintain fallback keys.~
- [x] https://github.com/matrix-org/matrix-spec/issues/1209
- [ ] https://github.com/matrix-org/matrix-spec/issues/1123
- [ ] https://github.com/matrix-org/matrix-spec/issues/1124
- [ ] https://github.com/matrix-org/matrix-spec/issues/1659
- [ ] https://github.com/element-hq/element-meta/issues/2154
- [ ] https://github.com/element-hq/element-meta/issues/2268
- [ ] https://github.com/element-hq/element-meta/issues/2374
- [ ] https://github.com/vector-im/element-meta/issues/646

**Comment by BillCarsonFr** [comment]
Interesting related blog post https://blog.neko.dev/posts/unable-to-decrypt-matrix.html

**Comment by jittygitty** [comment]
@BillCarsonFr Wow what a great write-up you found at https://blog.neko.dev/posts/unable-to-decrypt-matrix.html

Please correct me if I'm wrong, but having looked at that, it seems that just about all of those errors could be resolved via wizard/options provided to the user by the client which could try to resend encryption key with help of server or to even create a new one for the channel/room. I don't see any 'technical' issue/blocker other than currently missing functionality client-side to prompt user for permission to, with the help of in-between server, do what's necessary to fix room encryption/decryption. 

If there's a 'security' issue with properly re-identifying the correct user, for example to re-provide keys to the other user while they've gone offline so they can pick them up from server when they are online again, can't we have a simple "challenge/response" ie question/answer to "pick-up" the keys? (I'm trying to avoid creation of a "new" room/channel and instead fix one already created but giving errors of unable to decrypt. The sender's device has not sent us the keys for this message.)

It seems the reason certain steps aren't by default taken to automatically fix such issues, is that it could be a security risk in certain situations. But if the "creator" of a room gives needed permission, it seems in a sense trivial to resolve such decryption/key errors etc. Or am I wrong and missed something? 

And to the author of:
https://blog.neko.dev/posts/unable-to-decrypt-matrix.html
Many thanks!

**Comment by BillCarsonFr** [comment]
> Please correct me if I'm wrong, but having looked at that, it seems that just about all of those errors could be resolved via wizard/options provided to the user by the client which could try to resend encryption key

FTR, there used to be such UI, but it was prone to social attack and annoying in the UI.
It's something explored, but it's a bit hard to have a `fix all encryption problems` button. We are trying to go to the bottom of the root cause for distribution failure by moving to the rust sdk

**Comment by jittygitty** [comment]
@BillCarsonFr Ah ok guess I'm relatively new so didn't know of the older UI. Personally, I'd be ok with the "social attack" risks and UI annoyance versus the embarrassment of inviting users to my new chat and getting decryption errors.

My concern was that it may be impossible to fix the root for all cases of decryption issues, especially if some are due to security measures which may need to be over-ridden by user consent in order to fix, which brings us back to that UI annoyance.

But regardless, it's great to hear the underlying sdk is being improved to hopefully eliminate or greatly reduce these issues. I had heard of rust in conduit (I run go-dendrite) but didn't know Kotlin SDK is being all redone in rust, is that right?

Anyway, thanks again to everyone working on this! (I look forward to some beta-testing with the new sdk when its ready for that.)

**Comment by anon8675309** [comment]
The link to send debug logs does not appear on Element Web on my server. Did this UI change, or is there some option that an admin needs to enable to get that to show up?

**Comment by t3chguy** [comment]
@anon8675309 your config.json must have the URL to send debug logs to, like the example https://github.com/vector-im/element-web/blob/develop/config.sample.json#L25

**Comment by anon8675309** [comment]
Can you confirm that this is still the case?  I have the bug_report_endpoint_url entry from the sample and the link to send debug logs does not appear. If it's working as expected for you, I'll set up a new server and open a new ticket with the minimal steps to reproduce. (I searched for a report of this issue and didn't find anything, but I'll do so again before opening a new issue).

**Comment by hieronymousch** [comment]
Was able to send feedback from Element desktop... and have this issue with one single user on my home server, both users on the same server. Upgraded the room to version 10 and got the error again after not even 10 messages

**Comment by Ezwen** [comment]
Hi there, I have been encountering this problem a lot recently. I've already sent logs from element-web and element-android as the person who received encrypted messages that cannot be decrypted, but I could not yet send logs as somehow sending such problematic messages.

**Question**: when this situation happens in a matrix room, where a given user ends up only sending messages that cannot be decrypted by other room members, is there any (even intricate) known workaround? The only "workaround" I used so far was to upgrade the room to a newer room version, which solves the issue by creating a new room, but I can't really call this a proper solution… and right now I have this problem on a room that is already using version 10…

**Comment by lousando** [comment]
@Ezwen I've found that asking sender of messages to run `/discardsession` usually fixes any messages moving forward. Though it does not solve the messages with the encryption issue.

**Comment by zetaomegagon** [comment]
@BillCarsonFr just so that I'm on the same page: is there a lack of sender / receiver logs to review?

**Comment by theelous3** [comment]
> Will be fixed with Element R

For the uninitiated, could you please link to something explaining what this is? It's ungoogleable as R is an element on the periodic table, and exists in matrixes sometimes :)

**Comment by RayBB** [comment]
I agree with @theelous3 that adding context on Element R would be helpful.
From my quick search it seems it's probably short for Element Rust which is Element using the matrix-rust-sdk.
Related links:
- [Epic | Element R](https://github.com/vector-im/element-meta/issues/760)
- Some related issued under [label:A-Element-R](https://github.com/vector-im/element-web/labels/A-Element-R)
- [The matrix-rust-sdk One SDK to rule them all](https://archive.fosdem.org/2022/schedule/event/matrix_rust_sdk/) (2022 video)

Anyway, good job team on getting this rolling :)

**Comment by yennor** [comment]
is there any ETA?
I'm living in an area with really bad cellphone coverage, we're getting UDT messages as soon as somebody leaves the village (well, the ones which didn't switch back to whatsapp)

**Comment by lousando** [comment]
@yennor Not an ETA, but perhaps a short-term remedy. I've found that installing the newer [Element Android v1.6.3](https://github.com/vector-im/element-android/releases/tag/v1.6.3) version that's based on the Rust SDK has greatly helped in my rooms.

You'll likely need the "vector-gplay-rustCrypto-arm64-v8a-release.apk" file.

**Comment by yennor** [comment]
@lousando thanks, I'll give it a try and hope for the best.
What about the element-desktop version? can't find anything about rust there.

**Comment by lousando** [comment]
> @lousando thanks, I'll give it a try and hope for the best.
> What about the element-desktop version? can't find anything about rust there.

Yeah I'm not entirely sure if the desktop app has been swapped out to use the Rust SDK. I usually only keep up with the Android repo as there is usually where the unencrypted problem begins for myself and my recipients.

**Comment by ninchuka** [comment]
element web/desktop hasnt been changed to use the rust sdk for encryption yet, its a labs option (not one of the beta's) which has to be enabled in the config.md not just in the labs menu

**Comment by kwinz** [comment]
Every friend group or company that evaluted Element/Matrix that I've been a part of has run into this issue and has eventually given up on Matrix with this app. It's completely unrealistic that a non technical person could use it at the rate which the basic functionality of reading a message breaks and how hard it is currently for users to recover from a broken session in an encrypted group chat with multiple people. You're spending more time on tech support than actually communicating.
I can't understate how important it is that this issue finally gets fixed after multiple years.

**Comment by penyuan** [comment]
Agree with @kwinz's comment above. I also can't stress how critical this UX problem is. I can't count the number of people I've encouraged to try Element/Matrix that was turned off by this baffling problem. There are group chats that work fine for a few weeks/months, but suddenly one (or a few) person(s)'s messages would show up as "Unable to decrypt" for everyone else.

This is an incredibly big problem, and I've heard from many people across the world that this is **THE REASON** they gave up on Element/Matrix.

**Comment by fuomag9** [comment]
> Agree with @kwinz's comment above. I also can't stress how critical this UX problem is. I can't count the number of people I've encouraged to try Element/Matrix that was turned off by this baffling problem. There are group chats that work fine for a few weeks/months, but suddenly one (or a few) person(s)'s messages would show up as "Unable to decrypt" for everyone else.
> 
> This is an incredibly big problem, and I've heard from many people across the world that this is **THE REASON** they gave up on Element/Matrix.

I concur, if I have to explain a friend why their messages behave like this they'll just go back to whatsapp and consider me annoying

**Comment by kegsay** [comment]
We're actively working on this, despite the lack of activity on this particular issue.

In particular, within the last few months we have a [dedicated test suite](https://github.com/matrix-org/complement-crypto) now to identify these sorts of failure modes, which will ensure that clients using the rust SDK FFI bindings (e.g Element X) or JS SDK with rust crypto (e.g Element Web) work correctly going forwards. We're also working through the causes we've identified and fixing them with regression tests where appropriate.

This is going to take some more time I'm afraid, and we all understand how frustrating it is when things break. In the mean time, if you do happen to be using Element X and/or Element-Web and happen to see a message which is undecryptable, please send a rageshake: I actively review unable to decrypt bug reports when they come in on those particular clients.

**Comment by foresto** [comment]
> if you do happen to be using Element X and/or Element-Web [...] I actively review unable to decrypt bug reports when they come in on those particular clients.

@kegsay Does this include Element-Desktop?

**Comment by kegsay** [comment]
Currently this does _not_ include Element Desktop as rust crypto isn't enabled by default (yet). We expect this will change on a timescale of weeks not months. We've been discussing remaining blockers [literally yesterday](https://github.com/element-hq/element-desktop/issues/1313#issuecomment-1959737600). I'll edit this issue when it's enabled by default on Element-Desktop.

2024-03-18: Element Desktop still doesn't have rust crypto enabled by default yet, but I will update this issue when it is.
2024-04-11: We are beginning to roll out to Element Desktop incrementally.

**Comment by BillCarsonFr** [comment]
Created a new issue that could cause UTDs https://github.com/element-hq/element-meta/issues/2374

**Comment by richvdh** [comment]
> 2024-03-18: Element Desktop still doesn't have rust crypto enabled by default yet, but I will update this issue when it is.
> 2024-04-11: We are beginning to roll out to Element Desktop incrementally.

Element Desktop received Rust crypto for *new* sessions [back in February](https://github.com/matrix-org/matrix-react-sdk/pull/12203), for what it's worth. Rollout of migration for existing sessions is tracked at https://github.com/element-hq/element-web/issues/27001.

**Comment by richvdh** [comment]
Updates on recent progress here:

 * We found and fixed a [cause of broken Olm sessions](https://github.com/matrix-org/matrix-rust-sdk/issues/3110) on Element X iOS. You don't have to be using Element X iOS yourself to notice UTDs in this scenario: it causes problems on the sender and recipient side alike.
 * We found and fixed a [bug](https://github.com/element-hq/element-meta/issues/2338) which caused Element X to upload broken key backups.
 * We also found a [bug](https://github.com/famedly/matrix-dart-sdk/issues/1739) in the Dart SDK which caused clients based on that SDK to upload broken key backups. Thanks to @krille-chan and team for fixing it.
 * We rolled out an [update](https://github.com/element-hq/element-meta/issues/2313) to Element X and Element Web R which identifies events that were sent before you logged in, and shows the resultant UTD with a clearer error message.
 * We found and fixed a [bug](https://github.com/element-hq/synapse/issues/17117) which could cause Synapse to drop to-device messages (potentially containing message keys) during periods of high load.
 * We found and fixed a [bug](https://github.com/matrix-org/matrix-rust-sdk/issues/3211) in the Rust matrix-sdk-crypto (so affecting Element Web R and all mobile Element clients) which could cause it to fail to download key backups (thus preventing access to messages sent before you logged in).
 * We found and fixed a [bug](https://github.com/element-hq/synapse/issues/16928) in Synapse which could cause it to give incorrect membership state to clients, which would mean senders not sharing keys with all members of the room. (It is known, however, that there are more bugs in this area).

**Comment by penyuan** [comment]
> Updates on recent progress here:
> 
> ...

Just want to say a bit thank you to @richvdh for this progress update. ❤️ There is still **MUCH** that needs to be fixed in terms of bugs and UI/UX when it comes to encryption/decryption weirdness, and so many people I introduce to Element still get bounced off because of these problems. But at least getting these progress updates is helpful!

**Comment by kegsay** [comment]
Recently I've been giving updates for this on [This Week in Matrix](https://matrix.org/blog/2024/06/14/this-week-in-matrix-2024-06-14/#dept-of-encryption-closed-lock-with-key). If you fail to decrypt a message please:
 - send a bug report to us and mention:
     -  the event ID which failed to decrypt,
     - whether it was 1 or many events which failed to decrypt,
     - if many events, are they all from different people?
 - **ask the sender to also send a bug report mentioning the event ID**

We often need both sides of the conversation to fix the issue.

It would also be helpful for us if you can opt-in to analytics, as that feeds into our graphs which plot UTDs in aggregate. The general trend of the past few months has thankfully been fewer UTDs across clients that opt-in, but there is more work to be done here.

**Comment by yennor** [comment]
I usually got that kind of problem when me or the peer beeing in an area with bad mobile phone connection. With bad I mean really bad. You can get disconnected from the network for several minutes all the time, randomly get connected again for a few seconds, or beeing connected, but almost no data gets through.
I haven't been there (rural area of Colombia) since last year and won't for a few months. So So I can't tell if the situation improved with the new clients.
But maybe for your test-suite, simulate random tcp package drops (very high percentage) with high RTT (Several seconds, sometimes I measured up to 20 seconds. around 5-8 seconds is normal). And sent a few thousand messages there and back.

**Comment by jittygitty** [comment]
Does https://github.com/matrix-org/matrix-js-sdk/pull/454  already "implement" solution for: https://github.com/element-hq/element-meta/issues/647   ?
And if so how would my friend request keys from me (on Desktop Element) on a new fresh install of his?

Are we able now to send decryption keys to whomever we wish?

**Comment by t3chguy** [comment]
@jittygitty yes but Rust Crypto does not support that and that is what Element uses, so the js-sdk PR is unrelated

**Comment by jittygitty** [comment]
@t3chguy That's good news, so I guess if I wanted to make use of this feature, I would have to install the "Web" version client of element chat on my webserver? (I currently run Dendrite already, but with mobile and Desktop clients only.)

Or is there another client app that uses js-sdk? (Element Desktop does not use it?) Or will rust crypto gain it soon? 

I use another account on 'matrix.org' using desktop+mobile, for that acct. we can simply login at chat.element.io and if I'm logged in via my other devices, I can send keys to my web chat.element.io and resend to friend who lost his? thx

**Comment by t3chguy** [comment]
Element Desktop = Element Web + Electron. Element Web only supports Rust Crypto at this time. As for other matrix-js-sdk consumers I suggest finding a place discussing Matrix rather than Element specifically.

**Comment by jittygitty** [comment]
Apologies, indeed, seems I'm confused as to what matrix SDK is used by what "client", and I had not noticed the https://github.com/matrix-org/matrix-js-sdk/pull/454 was outside of element-hq repositories. So, I guess you are saying that likely none of the clients under https://github.com/element-hq are able to leverage that matrix-js-sdk pull 454?

Is there a place I can find all such pertinent information on the various clients available? If anyone can point me in the right direction with a link would be appreciated. Otherwise, I'll try some search engine lookups to dig for such info. thx

**Comment by mpeter50** [comment]
It seems [Cinny](https://github.com/cinnyapp/cinny/blob/60e022035f3bbfc09b2b5aee52f83e2aadf054e7/package.json#L59) uses the matrix-js-sdk, and maybe there are more, but I havent found another client that does.
Then, its an other question if Cinny makes use of this feature of the SDK. You could ask about that in Cinny's support room.

**Comment by richvdh** [comment]
Another round-up of recent updates. (Most of these have already been reported in TWIM, but I think it's handy to have a record here too.)

 * We found and fixed a [cause of broken Olm sessions](https://github.com/element-hq/element-ios/issues/7790) on Element iOS. As with the previous fix to EX iOS: you don't have to be using Element iOS yourself to notice UTDs in this scenario: it causes problems on the sender and recipient side alike.
 * We also have more fixes to both Element X iOS ([#2944](https://github.com/element-hq/element-x-ios/pull/2944)) and Element X Android ([#3050](https://github.com/element-hq/element-x-android/pull/3050)) which could cause broken Olm Sessions.
 * We found and fixed a [bug](https://github.com/matrix-org/matrix-rust-sdk/issues/3529) in matrix-rust-sdk affecting Element X.
 * We added a [workaround](https://github.com/matrix-org/sliding-sync/pull/449) to the sliding-sync proxy which would guard against messages being lost after the database was dropped, potentially causing UTDs for Element X clients.
 * We rolled out a [change](https://github.com/element-hq/element-meta/issues/2317) to Synapse and all Element clients, which will identify messages sent before you joined a room, and let you know you shouldn't expect to decrypt them.

A reminder that we're still at war with this issue, and it's incredibly helpful for people to send debug logs when they come across UTD errors.

That said, our analytics show that we are starting to make progress here:

![image](https://github.com/element-hq/element-meta/assets/1389908/9df5fd8d-ccc5-47ec-8b32-bb7f6f34172d)

**Comment by Xiretza** [comment]
Could somebody please expand this "UISI" acronym? I feel like I'm going mad trying to find out what it means, but only ever finding more uses, and zero explanations.

**Comment by jivanpal** [comment]
@Xiretza UISI stands for Unknown Inbound Session ID.

**Comment by penyuan** [comment]
It seems that the problems discussed in this thread are at least partly (if not mostly?) solved in Element X. 

My question is: For those of us still on the old Element, what are the specific migration steps to Element X? Would we have to log in "from scratch" in Element X and go through the confusing and convoluted authentication steps again? And what if my old Element app and new Element X app are on the same device?

**Comment by masterflitzer** [comment]
wdym with confusing auth steps? it's as straight forward as can be:  
download element x, enter email & password, confirm emojis or security key, done

i have both on my phone, because imo element x is not 100% ready yet

**Comment by richvdh** [comment]
> My question is: For those of us still on the old Element, what are the specific migration steps to Element X?

This is off-topic for this issue.

**Comment by richvdh** [comment]
I realised we're overdue for an update of recent work done in this area.

First, some graphs of UTD rates, according to our metrics:


![image](https://github.com/user-attachments/assets/b92305a8-494f-4666-a87e-50d508408abb)
(blue=android, purple=ios, green=web/desktop)
![image](https://github.com/user-attachments/assets/b12af445-4924-4c03-818b-4e2990ceddc1)
![image](https://github.com/user-attachments/assets/03c67707-b986-4b65-8438-0b87eda63d9f)

We changed how the metrics were calculated back in August, to allow breakdown between EX and classic mobile clients. As you can see, there was a big drop back in June, and rates have been relatively static at 1-5% of users (depending on client) since then.

Focus recently has been on analysing reports to see where the most important areas for fixes are. https://github.com/element-hq/element-meta/issues/2356 is the most frequent root cause, so we're going to prioritise a fix for that.

Meanwhile we did fix a few problems:
 * A [bug in Element X Android](https://github.com/matrix-org/matrix-rust-sdk/pull/3992) which could cause broken Olm sessions.
 * A [bug in Element X](https://github.com/matrix-org/matrix-rust-sdk/issues/4196) which meant it didn't update replies when the original message was decrypted.

There are a few new causes in the list above, but I won't enumerate them here, as they are still under investigation and haven't been seen in many cases.

**Comment by ToddCrimson** [comment]
Hello, just checking in if this has a clear RCA yet? 
Saw this pop on our side yesterday :( :(

**Comment by androclus** [comment]
BTW, if it is any help, I did give my friends problems (the infamous "_\*\*Unable to decrypt: The sender's device has not sent us the keys for this message.\*\*_" error message, as in [Issue element-hq/element-web#19748](https://github.com/element-hq/element-web/issues/19748) ) on their end.

Two things I did:
1) I made a new Linux laptop the lazy way (I copied my home directory over verbatim from my desktop, including ~/.config/Element ), and then ran both at the same time.

2) I also installed Element on a second Android phone (the correct way). I don't know if this caused it, either.

At that point, I had at least 4 Elements running. Then the problems seemed to start when I turned on the laptop and used its Element (in a coffee shop) and later in the day shut it down, came home, and started up the desktop copy (which had not been running when I was at the coffee shop).

In the previous day's I'd been noticing some lags between the phones, too.

If I have to, I'll remove Element from one of the phones, but after I signed out from the laptop's Element, then recursively removed its ~/.config/Element directory and restarted (thus creating a completely unique Element session -- as I should have in the first place of course -- things seem better now.

This experience is problably of no help, but I post it in case it does provide any clues.

**Comment by jivanpal** [comment]
@androclus You've effectively duplicated the desktop's session, which won't play well with the ratcheting mechanism. I'd recommend that you log out of both the desktop and laptop sessions and log in again. Don't copy keys/sessions between devices like this.

**Comment by richvdh** [comment]
> Hello, just checking in if this has a clear RCA yet?

I recommend re-reading the description at the top. At the last count, there are *eighty-six* different causes, many of which have been fixed.

>  Saw this pop on our side yesterday :( :(

Great! I assume you sent logs from within the application (as, again, the description requests), so that we can debug it?

**Comment by ToddCrimson** [comment]
Yep all were uploaded. And yes I did read and re-read again as you asked.

**Comment by pizdjuk** [comment]
I got this problem and no idea how to solve it. Even deleting the user and opening a new room did not help. In the new room I still cant read any message. Even cant do the verification. Actually the conversation with one of my contacts rendered completely impossible.

The steps that was before:

1. make a room with a new contact
2. delete like ~6 of obsoleted sessions of my account
3. make some new sessions
4. the bug appeared

**Comment by richvdh** [comment]
@pizdjuk please read the description of the issue; it explains about how to submit a useful report.

**Comment by pizdjuk** [comment]
> [@pizdjuk](https://github.com/pizdjuk) please read the description of the issue; it explains about how to submit a useful report.

Done. But we still can not chat. Every one of us deleted the room, and the contact of each other. Then created new room, same problem. My side can not decrypt messages. No idea what to do without getting new account.

**Comment by richvdh** [comment]
I've locked this to stop people posting "me too" comments without reading the description. Once more, for the record: if you want to discuss this, open a *new* issue in the issue tracker for your client, and submit debug logs from within your client, mentioning the issue number.

**Comment by richvdh** [comment]
Added https://github.com/element-hq/element-ios/issues/7904 as a cause of UTDs from the sender side

**Comment by richvdh** [comment]
And now https://github.com/element-hq/element-android/issues/9009 as well.

**Comment by richvdh** [comment]
Added https://github.com/element-hq/element-meta/issues/2891

**Comment by richvdh** [comment]
Thanks to folks who have sent debug logs from their clients when they see UTD errors; the reports are very useful.

I've been through about 20 sets of logs in the last few days and all but a couple of them appear to be problems on the sender side. So this is just a reminder that, if you can get the sender to submit debug logs as well, then we have a much better chance of figuring out what went wrong ;)
