### ISSUE TITLE
[Story] EX: Incoming device verification request

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2464]
### Description

* As a user
* I want to use EX to verify a new login that happened on another matrix client.
* So that I can verify any new login using EX instead of depending on another matrix client like EW to do so

Design: https://www.figma.com/design/pDlJZGBsri47FNTXMnEdXB/Compound-Android-Templates?node-id=819-22988&t=bTS0BUh3clntn0mX-4

### Leads

* Tech: @stefanceriu 
* Design: <GitHub id>

### Time sheeting
ER-49 EX: (Incoming) Device Verification by Emoji

### Acceptance criteria

- EX detects and displays incoming verification request
- The user can successfully verify the new login using EX

### Size estimate

None

### Dependencies

- None

### Out of scope

- QR code login. Displaying a QR code on EX will happen later.

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3120
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/1227
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3595
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/4153
```

```[tasklist]
### Other
- [x] Everything in [Incoming Device Verification Requests Testing Session](https://docs.google.com/document/d/1j_d5UZAvq448uSnhidDq55gfeqxrKrrrPb-7yF9l9kM/edit?tab=t.0#heading=h.7cdh2sxmo0ny)
- [ ] https://github.com/element-hq/element-web/issues/28520
- [ ] https://github.com/element-hq/element-web/issues/29438
```

**Comment by alanjsebas** [comment]
Any ETA for how long this might take to implement, no intention to rush anyone I kinda screwed it up because I uninstalled the main element app on Android, and after an update to Element on Windows...the Ex is the only one with device verification and access to past messages.

I expected at least the Windows one to retain verification and messages before but now its all gone.

**Comment by stefanceriu** [comment]
> Any ETA for how long this might take to implement, no intention to rush anyone I kinda screwed it up because I uninstalled the main element app on Android, and after an update to Element on Windows...the Ex is the only one with device verification and access to past messages.
> 
> I expected at least the Windows one to retain verification and messages before but now its all gone.

Hi, it shouldn't take particularly long but I can't speak to exact timings. Meanwhile you might want to have a look at setting up chat backup and a recovery key, which you can then use to verify other devices and retrieve your keys.

**Comment by manuroe** [comment]
Everything in [Incoming Device Verification Requests Testing Session](https://docs.google.com/document/d/1j_d5UZAvq448uSnhidDq55gfeqxrKrrrPb-7yF9l9kM/edit?tab=t.0#heading=h.7cdh2sxmo0ny) is cleared.
We can claim the feature beautifully done and tested 🎉 

It was already available in [EXA 0.7.3](https://github.com/element-hq/element-x-android/releases/tag/v0.7.3) and [EXI 1.9.5](https://github.com/element-hq/element-x-ios/releases/tag/1.9.5). It is fully done in [EXA 0.7.4](https://github.com/element-hq/element-x-android/releases/tag/v0.7.4) and [EXI 1.9.6](https://github.com/element-hq/element-x-ios/releases/tag/1.9.6) with all the little improvements we wanted to apply.
