### ISSUE TITLE
[Story] EX: Decorate untrusted messages with a shield

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2489]
### Description

* As a user in an end-to-end encrypted room
* I want to be informed when a message cannot be trusted
* So that I can take proper actions

Designs are linked below:

### Acceptance criteria

Check the related epic, A shield must be displayed on a message when:
- `The authenticity of this encrypted message can't be guaranteed on this device`. (when key imported from backup, from file..) [Figma](https://www.figma.com/design/Ni6Ii8YKtmXCKYNE90cC67/Timeline-(new)?node-id=1157-16670&m=dev)
- `Encrypted by a device not verified by its owner.` (the sender has not verified his device) [Figma](https://www.figma.com/design/Ni6Ii8YKtmXCKYNE90cC67/Timeline-(new)?node-id=1159-5717&m=dev)
- `Encrypted by an unknown or deleted device.` (the device has been deleted OR has not yet been downloaded) [Figma](https://www.figma.com/design/Ni6Ii8YKtmXCKYNE90cC67/Timeline-(new)?node-id=1159-4930&m=dev)
- `Sent In Clear` When a message is sent in clear in a e2ee room (typically a bot) [Figma](https://www.figma.com/design/Ni6Ii8YKtmXCKYNE90cC67/Timeline-(new)?node-id=1159-6491&m=dev)

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
- [ ] @amshakal We need to think about what we will do for VoiceOver here. Users should know there's an authenticity issue, but we don't want them to get fedup of hearing it when scrolling through messages from their backup.
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3261
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3108
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3667
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/3783
```

```[tasklist]
### Other
```
