### ISSUE TITLE
[Story] EX: Display message shield explanation

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2490]
### Description

* As a user
* I want to understand why a security shield is displayed on message
* So that I can take even proper actions

There are 2 different ways we will show the explanation:
- Tap the icon to display the explanation: [Figma](https://www.figma.com/design/Ni6Ii8YKtmXCKYNE90cC67/Timeline-(new)?node-id=1157-16429&m=dev)
- Long press the message to display the context menu (same icons as [#2489](https://github.com/element-hq/element-meta/issues/2489)): [Figma](https://www.figma.com/design/Ni6Ii8YKtmXCKYNE90cC67/Timeline-(new)?node-id=1157-16607&m=dev)

### Acceptance criteria

- User can get an explanation on shields the app can display (the list is in the acceptance criteria of https://github.com/element-hq/element-meta/issues/2489)

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
- [x] @BillCarsonFr The "Sent in clear" message seems a bit brief and not necessarily understandable to an average user (I took it from the original issue). Is there a different string we are meant to show the user in this instance?
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3262
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3109
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```
