### ISSUE TITLE
[Story] Require acknowledgement to send to a verified user if their identity changed

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-meta#2500]
### Description

* As a user
* I want to be informed when a user I previously verified has reset their identity
* So that I know that our conversations aren't being intercepted.

Figma: [iOS](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Reset-Crypto-Identity-(temp)?node-id=7-28521&m=dev)/[Android](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Reset-Crypto-Identity-(temp)?node-id=17-47163&m=dev)

### Acceptance criteria

- Sending a message to a user that was verified but has changed their identity fails.
- An alert is shown when interacting with the failed message.
- The verification can be withdrawn to allow the message to send.

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3459
- [ ] https://github.com/element-hq/element-x-android/issues/3460
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3159
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3837
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3839
```

```[tasklist]
### Crypto
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3793
```

**Comment by richvdh** [comment]
I believe this issue only tracks the work for Element X. Have opened https://github.com/element-hq/element-web/issues/27943 to add it to element-web.

**Comment by manuroe** [comment]
thanks @pixlwave  and @ganfra. It is now available on Android and iOS.
