### ISSUE TITLE
[Story] Require acknowledgement to send to a verified user if a device is unverified

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-meta#2501]
### Description

* As a user
* I want to be informed when a verified user has an unverified device on their account
* So that I know that our conversations aren't being intercepted.

Figma: [iOS](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Reset-Crypto-Identity-(temp)?node-id=13-4450&m=dev)/[Android](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Reset-Crypto-Identity-(temp)?node-id=19-30152&m=dev)

### Acceptance criteria

- Sending a message to a verified user that has an unverified device on their account fails.
- An alert is shown when interacting with the failed message.
- The user can opt to not worry about that particular unverified device and send messages to this user anyway.

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3301
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3160
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3837
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3838
```

```[tasklist]
### Crypto
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/3792
```

**Comment by richvdh** [comment]
I believe this issue only tracks the work for Element X. Have opened https://github.com/element-hq/element-web/issues/27943 to add it to element-web.

**Comment by manuroe** [comment]
Everythins is done here 🥳
