### ISSUE TITLE
[Story] Minimal solution for an option to hide media content 

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2540]
In order to help the T&S team, we are going to quickly add this option in the developer options of the nightly builds of apps. This work addresses the first request raised in https://github.com/element-hq/element-meta/issues/2518.
The whole feature would need more product thinking and research before landing in the main builds. We do not want to simply add yet another settings in the app. If we want to limit bandwidth usage, we should first stop sending images in full res in EX for example (we are about to fix this issue before end of the year).

* As a T&S team member using the nightly app
* I want to be able switch off the display by default of media content 
* So that I reduce my risk of viewing harmful imagery and other media

### Acceptance criteria

- Thumbnails of images and videos are not displayed in the timeline

### Leads

* Tech: @pixlwave 
* Design: @amshakal 

### Documentation
* PRD: https://docs.google.com/document/d/1tj-OslshBZkfrWwZW_AK2unz6WphtOvoIRlu3ZlmYtk/edit#heading=h.mlraim6vvpz6
*  https://element-io.atlassian.net/jira/polaris/projects/ER/ideas/view/5045500?selectedIssue=ER-113
* https://github.com/element-hq/element-meta/issues/2518

### Size estimate

None

### Dependencies

- None

### Out of scope

- Thumbnails in notification. From a T&S perspective, they should not have notifications enabled in such rooms

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3386
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3228
```

```[tasklist]
### Other
```

### Android
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

### iOS
- [x] Design sign-off on completion
- [x] QA sign-off on completion
- [x] Product sign-off on completion

**Comment by manuroe** [comment]
@jimmackenzie this feature is now available on nighlly buids of the apps. You can find the toggle button in the dev settings.
Let's us know if it works as expected for you.

**Comment by manuroe** [comment]
I did a 30min QA session on both apps. The feature works as expected. Thanks @bmarty and @pixlwave !
I am closing this story.

cc @mxandreas
