### ISSUE TITLE
[Story] Adjust message history disclaimer on EX key reset

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2542]
### Description

We have gotten feedback that while users are migrating to EX, but haven't got any existing & verified devices and also have forgotten their recovery key, are hesitating to do the identity reset because we have the following statement in there:

_You will lose your existing message history._

<img width="501" alt="Screenshot 2024-09-27 at 13 53 58" src="https://github.com/user-attachments/assets/d50c54d7-750e-4420-bd77-3f1cef4560b6">

This statement was intentional and is still valid - because: while we're not going to explicitly delete their history on their other existing devices, we also have no knowledge on what is exactly on those devices and the average user has also no idea what has a specific client downloaded / cached in the device or not. Thus, overall we have to account for the worst case scenario and be straightforward in our statements.

However, after a cautious debate how to prevent users from also making the conclusions in the other direction (like we were to delete what's already on their existing devices), it was agreed to adjust the wording of the statement as follows:

**_You will lose your existing message history unless it is stored on another device._**

The updated designs are here: [iOS](https://www.figma.com/design/jvZ7TIyd7V9Vn8sIDB9vMd/Compound-iOS-Templates?node-id=1088-14204&t=6CUwuYRNMGgrmn1H-4) and [Android](https://www.figma.com/design/pDlJZGBsri47FNTXMnEdXB/Compound-Android-Templates?node-id=620-20188&t=Ag1Y3sK1akxbKOMk-4).

Since this is a subtle difference, and directed towards existing power-users, I propose not to change any translations but only the English text.

My understanding is that EW is out of scope here, but correct me if I am wrong.

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3573
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3355
```

```[tasklist]
### Rust
```

```[tasklist]
### MAS
- [ ] https://github.com/element-hq/matrix-authentication-service/issues/3261
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by americanrefugee** [comment]
@mxandreas Updates made to [iOS](https://www.figma.com/design/jvZ7TIyd7V9Vn8sIDB9vMd/Compound-iOS-Templates?node-id=1088-14204&t=6CUwuYRNMGgrmn1H-4) and [Android](https://www.figma.com/design/pDlJZGBsri47FNTXMnEdXB/Compound-Android-Templates?node-id=620-20188&t=Ag1Y3sK1akxbKOMk-4)

**Comment by americanrefugee** [comment]
Are any changes needed for the [Settings version of "reset identity"](https://www.figma.com/design/qTWRfItpO3RdCjnTKPu4mL/Settings?node-id=1671-31271&t=iQxdiKHeJyiF1AXV-4)?

**Comment by mxandreas** [comment]
> Are any changes needed for the [Settings version of "reset identity"](https://www.figma.com/design/qTWRfItpO3RdCjnTKPu4mL/Settings?node-id=1671-31271&t=iQxdiKHeJyiF1AXV-4)?

I think not because we are fine-tuning for the experience of migrating to EX, specifically. Just in case @pmaier1 .

**Comment by pmaier1** [comment]
> Are any changes needed for the [Settings version of "reset identity"](https://www.figma.com/design/qTWRfItpO3RdCjnTKPu4mL/Settings?node-id=1671-31271&t=iQxdiKHeJyiF1AXV-4)?

No. This part anyway needs more thinking. It will likely not use the same primitives as the identity reset during sign-in and has a different use case ("I think I have been compromised and want to change my secrets therefore"). 

Regarding the suggested wording, I'm fine with it.

**Comment by mxandreas** [comment]
@pmaier1 Are you creating a subtask/ticket to do the update in MAS?

**Comment by pmaier1** [comment]
https://github.com/element-hq/matrix-authentication-service/issues/3261

**Comment by bmarty** [comment]
String updated on Localazy: https://localazy.com/p/element/source-language/_a7281790744829274158#versions
Technically there is nothing else to do, the string will be synced during the next Localazy sync (which occurs in Monday mornings).
