### ISSUE TITLE
[Story] Banner for unverified user identity change

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2544]
### Description

* As a user
* I want to be informed when an unverified user has changed their identity keys
* So that I can make a conscious decision before posting a message in a room

We are to implement the temporary flow version from [figma](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=6-1105&node-type=canvas&t=MRHBrINRtC1poCU3-0). The Final version will happen with invisible crypto.

### Acceptance criteria

- The banner is displayed close to the composer and does not affect the timeline interactions (srolling, URL navigation)
- It is displayed when the user opens the room
- It stays until the user tapped ok
- It pops up in realtime once SDK/Crypto detects the change 
- It is displayed once per identity change. SDK/Crypto stores the user acknownledgment
- A single identity change is shown at a time as a "FIFO". If the user acknowledges one and it there are more, the app must display the banner for the next unverified user identity change
- Tech one: the banner component should be reusable. We are going to use it with invisible crypto on such [screen](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=224-47957&node-type=frame&t=MRHBrINRtC1poCU3-0)

### API

The API is being implemented in https://github.com/element-hq/element-meta/issues/2526 - see branch https://github.com/matrix-org/matrix-rust-sdk/tree/andybalaam/room-identity-stream until it is merged.

Summary:

```
Call this method in matrix_sdk_ffi::room::Room:

    pub fn subscribe_to_identity_status_changes(
        &self,
        listener: Box<dyn IdentityStatusChangeListener>,
    ) -> Arc<TaskHandle>

Passing in one of these:

pub trait IdentityStatusChangeListener: Sync + Send {
    fn call(&self, identity_status_change: Vec<IdentityStatusChange>);
}
```

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-meta/issues/2524
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-meta/issues/2525
```

```[tasklist]
### Rust
- [ ] https://github.com/element-hq/element-meta/issues/2526
```

```[tasklist]
### Other
- [x] URL for the "Learn more" link: https://element.io/help#encryption18
```

**Comment by richvdh** [comment]
I think this is a duplicate of https://github.com/element-hq/element-meta/issues/2492 ?

**Comment by andybalaam** [comment]
> I think this is a duplicate of #2492 ?

No, 2492 is about _verified_ and this is about _unverified_ identities.

**Comment by richvdh** [comment]
> No, 2492 is about _verified_ and this is about _unverified_ identities.

Argh, yes, sorry.

**Comment by richvdh** [comment]
Useful links:
 * Part of https://github.com/element-hq/element-meta/issues/2491
 * Element-Web equivalent: https://github.com/element-hq/element-meta/issues/2513

**Comment by manuroe** [comment]
Checked with @BillCarsonFr . We can close this task.
