### ISSUE TITLE
[Story] Improve user guidance during QR code login

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2558]
### Description

Currently the scanning the QR code with EX and showing the QR code on EW device for login are only available on the nightly builds. The reason for that is that MAS (which is a prerequisite for the QR code login) is not yet available in most homeservers.

However, it is assumed that deploying MAS on various homeservers will span across a long period of time (and some homeservers may not ever get it), it is desired to make it more clear for the users that this function depends on something their homeserver does not (yet) have.

In iterations with @amshakal @americanrefugee we landed on the following:
* On EX intro screen, add a subtle hint: "Only available if your account provider supports it"
* On EW,
  * Always show the _Avatar_ > _Link new device_ menu item, and if not supported, then instead of showing the QR code, show that it is not supported (designs below).
  * In the _Settings_ > _Sessions_ show always the _Link new device_ section but disable the _Show QR code_ button when not supported and add a text that it is not supported (designs below).

This would allow us to release the QR code login in the publish/production versions. 

### Leads

* Tech: @manuroe 
* Design: @amshakal 

### Size estimate

S

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3632
- [ ] https://github.com/element-hq/element-x-android/pull/3646
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3385
- [ ] https://github.com/element-hq/element-x-ios/pull/3392
```

```[tasklist]
### Web
- [x] https://github.com/element-hq/matrix-react-sdk/pull/147
- [x] Make the "Link new device" available in production release: Available since Oct, 22nd in https://github.com/element-hq/element-web/releases/tag/v1.11.82
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by pmaier1** [comment]
Makes sense to me (apart from the fact that only a tiny fraction of users out there use a homeserver that actually supports QR code login :man_shrugging:).

**Comment by mxandreas** [comment]
@americanrefugee Has done the design updates for both EX and EW side:
* [iOS](https://www.figma.com/design/jvZ7TIyd7V9Vn8sIDB9vMd/Compound-iOS-Templates?node-id=1-3839&t=szCZVx9v5SNMhkXd-4)
* [Android](https://www.figma.com/design/pDlJZGBsri47FNTXMnEdXB/Compound-Android-Templates?node-id=41-10347&t=sOWqqbMWIr3wJpMn-4)
* [Web](https://www.figma.com/design/4wV2hrQvuQrDBiZW70DfqX/Compound-Web-Templates?node-id=44-27449&t=Vh2uAUIAnzSYbmpk-4)

![image](https://github.com/user-attachments/assets/6d685a67-0b5b-4993-a3c6-c5527ffebf8f)

**Comment by bmarty** [comment]
I have added the string `screen_qr_code_login_initial_state_subtitle` to localazy (@element-hq/element-x-ios-reviewers)

**Comment by mxandreas** [comment]
For visibility. It was confirmed that the desired changes on EW take more effort (and can't be released as part of the security release) due to the fact that we can't simply un-lab all the functionality (and need to do it just for the QR code parts).

Since it is now known that this is overall feasible (just delayed by a week), I proposed we continue with the release of EX as planned (e.g. showing the QR code login button), given we have a warning/hint that it needs to be supported by the account provider.

cc @daniellekirkwood @manuroe @t3chguy @pmaier1

**Comment by manuroe** [comment]
Changes in EW are available in prod since yesterday. We can close this work.
Thanks all!
