### ISSUE TITLE
Invisible Crypto: User Identity notices are displayed in unencrypted rooms

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#2560]
Follow-up on https://github.com/element-hq/element-meta/issues/2491

Currently the TOFU identity change notice is displayed if you are in a non encrypted room

<img width="346" alt="image" src="https://github.com/user-attachments/assets/1f791540-66be-426e-8b22-70d0c83764ad">

=> We might want to only show that in e2ee rooms.

(Definitly should not do it in clear room for verified identity changes)
```[tasklist]
### Tasks
- [x] Done on Android: https://github.com/element-hq/element-x-android/pull/3630
- [x] Web will be done as part of: https://github.com/element-hq/element-meta/issues/2513
- [ ] https://github.com/element-hq/element-x-ios/issues/3409
```

**Comment by andybalaam** [comment]
Android: https://github.com/element-hq/element-x-android/pull/3630

Web: we will do this as part of https://github.com/element-hq/element-meta/issues/2513

iOS: @mxandreas will make a ticket

**Comment by mxandreas** [comment]
Created a ticket for iOS, cc @manuroe .

**Comment by pixlwave** [comment]
How come this is a client-side issue and not an SDK issue? I would expect this [callback](https://github.com/matrix-org/matrix-rust-sdk/blob/2eca7271ea6a1c8ca263296375c4c7d7b0e3f794/bindings/matrix-sdk-ffi/src/room.rs#L600-L608) to never be used when the room is unencrypted.

**Comment by andybalaam** [comment]
> How come this is a client-side issue and not an SDK issue? I would expect this [callback](https://github.com/matrix-org/matrix-rust-sdk/blob/2eca7271ea6a1c8ca263296375c4c7d7b0e3f794/bindings/matrix-sdk-ffi/src/room.rs#L600-L608) to never be used when the room is unencrypted.

So would you expect calling `subscribe_to_identity_status_changes` to do nothing in an unencrypted room? That would seem quite surprising to me...

I would have thought it would be more sensible not to call it in an unencrypted room?

**Comment by pixlwave** [comment]
Ah I see what you mean. We don't have any logic around what we do/don't subscribe to, my understanding of it being a client issue was to still subscribe to it and filter out any updates based upon the encryption state of the room. Doing what you suggested makes wayyy more sense to me though!

(It wouldn't handle the possibility of encryption being enabled by someone after opening the room, but I'm happy to ignore that if you aren't bothered about this edge case?).

**Comment by pixlwave** [comment]
PR here: https://github.com/element-hq/element-x-ios/pull/3414

**Comment by andybalaam** [comment]
> (It wouldn't handle the possibility of encryption being enabled by someone after opening the room, but I'm happy to ignore that if you aren't bothered about this edge case?).

Will it self-heal if you switch away to a different room and back? If so it seems pretty minor, but we should log it as a known issue.

**Comment by pixlwave** [comment]
Exactly, yes. We create one of the `RoomProxy` objects each time you open a room and dispose of it when you pop back out of that room flow.

> we should log it as a known issue.

In an issue on EXI, or do you have a better place to track this on the crypto side?

**Comment by andybalaam** [comment]
> In an issue on EXI, or do you have a better place to track this on the crypto side?

I would think EXI, and EXA if a similar problem exists there. cc @bmarty

**Comment by pixlwave** [comment]
Done here: https://github.com/element-hq/element-x-ios/issues/3417

**Comment by andybalaam** [comment]
Awesome, thank you!

**Comment by manuroe** [comment]
thanks @pixlwave! I removed you as assignee to make clear that we do not work anymore on this item.
