### ISSUE TITLE
[Story] Adjust EX device verification & key reset UI/copy

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2564]
### Description

These proposed changes are following a long debate on how to find a better balance getting user their EX device verified in case they do not have any other devices or a recovery key; and not setting false expectations in terms of which messages the user can still access after the reset. Apart from minor fine-tuning suggestions, these changes are not up for a debate right now - the risk that users may too lightly do the reset and then not have access anymore the messages they hoped for, has been accepted (cc @ara4n ).

1) [Android](https://www.figma.com/design/pDlJZGBsri47FNTXMnEdXB/Compound-Android-Templates?node-id=343-14433&t=ptyvIdXmePTZVV7N-4) & [iOS](https://www.figma.com/design/jvZ7TIyd7V9Vn8sIDB9vMd/Compound-iOS-Templates?node-id=585-18531&t=CilWTIavp7udm1Ew-4): On the device verification initial screen - style the buttons differently so that the user understand that the 2 verifications are alternatives of each other, and then the 3rd option (Can't confrim) is an alternative to these.

2) [Android](https://www.figma.com/design/pDlJZGBsri47FNTXMnEdXB/Compound-Android-Templates?node-id=343-14435&t=ptyvIdXmePTZVV7N-4) & [iOS](https://www.figma.com/design/jvZ7TIyd7V9Vn8sIDB9vMd/Compound-iOS-Templates?node-id=1-3720&node-type=frame&t=CilWTIavp7udm1Ew-11) & [MAS](https://www.figma.com/design/jvZ7TIyd7V9Vn8sIDB9vMd/Compound-iOS-Templates?node-id=585-10949&t=CilWTIavp7udm1Ew-4): On the key reset disclaimer screen - decorate the warnings with just the information, and slightly change the wording so that it tells that the messages only stored on the server are not accessible.

3) iOS special: please remove the "Create new recovery key" option from the [Enter recovery key](https://www.figma.com/design/jvZ7TIyd7V9Vn8sIDB9vMd/Compound-iOS-Templates?node-id=1-3828&t=CilWTIavp7udm1Ew-4) screen. It is clear by now that this button is not needed on this screen in any of the flows.

![image](https://github.com/user-attachments/assets/157f16d4-9a14-4001-98c9-764c1468755e)

### Leads

* Tech: @manuroe 
* Design: @americanrefugee 

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3639
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3388
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [x] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [x] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by mxandreas** [comment]
@pmaier1 Please either create a new ticket for MAS or update the [one](https://github.com/element-hq/matrix-authentication-service/issues/3261) that you created during previous iteration.

**Comment by pmaier1** [comment]
> @pmaier1 Please either create a new ticket for MAS or update the https://github.com/element-hq/matrix-authentication-service/issues/3261 that you created during previous iteration.

Of course, let me do this for you, sir. 

> You will lose any message history that is stored only on the server

Now you're doing exactly what I wanted to avoid. IMO, a normal user does not know that the server stores history and message keys. That's why I put it the other way around initially ("that is not stored on **another device**").

**Comment by manuroe** [comment]
Tested ok on EXA 0.7.0 and EXI 1.9.0.
Thanks @bmarty and @pixlwave!
