### ISSUE TITLE
Trust & Decoration | Missing mxId in the Banner for unverified user identity change (displayName+avatar is not enough)

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#2565]
Follow up of https://github.com/element-hq/element-meta/issues/2544

The current design only shows the user display name
<img width="319" alt="image" src="https://github.com/user-attachments/assets/7e2407cf-679c-4009-b21b-e2ed7ef6dc1e">

If several users are using the same display name and no avatar it would be impossible to know which one it is talking about. Also a user could change it's display name and avatar to masqarade another user.

Show the MXID in bold and parentheses after the display name. In case display name is missing, omit the parentheses.

![image](https://github.com/user-attachments/assets/fc898a10-4a7a-4770-8d00-d4f4d244a373)

Designs:
* [Android](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=340-33999&t=3Z8gSwpEOZNmY8Cp-4)
* [iOS](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=340-11002&t=3Z8gSwpEOZNmY8Cp-4)
* [Web](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=340-29155&t=3Z8gSwpEOZNmY8Cp-4)

```[tasklist]
### Tasks
- [ ] https://github.com/element-hq/element-x-ios/issues/3410
- [ ] https://github.com/element-hq/element-x-android/issues/3678
- [x] Web is done as part of: https://github.com/element-hq/element-meta/issues/2513
```

**Comment by BillCarsonFr** [comment]
Also we need to udpate the copy of `appears to have changed`.
It has changed for sure, might not be just now though; it was just detected now.

**Comment by BillCarsonFr** [comment]
Clarification: It appears that this is the `disambiguatedDisplayName` that is used here. But anyhow we want also the mxid here.

**Comment by mxandreas** [comment]
@americanrefugee Could you please update the designs accordingly? I think you can then do it also for the verified identity change case if we are doing it anyway.

@BillCarsonFr Besides the example you listed - do you know if there is already some sort of de facto standard here? It would be trivial to just add the MXID in partentheses but would be nice to make sure it is identical in all cases.

> disambiguatedDisplayName

Also, if this does not include the MXID then how does it make the display name unambiguous?

**Comment by bmarty** [comment]
@mxandreas `disambiguatedDisplayName` may contain the mxId if the room have multiple users with the same display name.

If you read code, this is the Kotlin implementation: https://github.com/element-hq/element-x-android/blob/develop/libraries/matrix/api/src/main/kotlin/io/element/android/libraries/matrix/api/room/RoomMember.kt#L43

```kotlin
    /**
     * Disambiguated display name for the RoomMember.
     * If the display name is null, the user ID is returned.
     * If the display name is ambiguous, the user ID is appended in parentheses.
     * Otherwise, the display name is returned.
     */
    val disambiguatedDisplayName: String = when {
        displayName == null -> userId.value // will be "alice:server.org"
        isNameAmbiguous -> "$displayName ($userId)" // will be "Alice (alice:server.org)"
        else -> displayName // will be "Alice"
    }
```

But it is definitely possible to always include the mxId. We will need to decide how it will render if the user does not have a display name.

Maybe something like:
```kotlin
    val displayNameWithMxId: String = when {
        displayName == null -> userId.value // will be "alice:server.org"
        else -> "$displayName ($userId)" // will be "Alice (alice:server.org)"
    }
```

**Comment by mxandreas** [comment]
Thanks for the clarifications! To me it seems the safest and most straightforward option to always include MXID in this scenario.

**Comment by bmarty** [comment]
> Clarification: It appears that this is the `disambiguatedDisplayName` that is used here. But anyhow we want also the mxid here.

@BillCarsonFr Can you change the issue title please?

**Comment by BillCarsonFr** [comment]
> > Clarification: It appears that this is the `disambiguatedDisplayName` that is used here. But anyhow we want also the mxid here.
> 
> @BillCarsonFr Can you change the issue title please?

Done

**Comment by mxandreas** [comment]
We had a short sync and the designs are updated accordingly:
* [iOS](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=340-11002&node-type=frame&t=Ov3x5YgqF7Wzio9i-11)
* [Android](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=340-33999&node-type=frame&t=Ov3x5YgqF7Wzio9i-11)
* [Web](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=340-29154&node-type=frame&t=Ov3x5YgqF7Wzio9i-11)

Android sample:
![image](https://github.com/user-attachments/assets/a344671b-6da3-4d92-8d1d-1466f3078a89)

**Comment by bmarty** [comment]
What happen if the user does not have a display name? We repeat the user id like this?

alice:domain.org's (**alice:domain.org**) identity appears to have changed

It's fine to me, but please confirm.

Also please be aware that translation may look differently, for instance in French this will be something like:

L'identité de Alice (**alice:domain.org**) semble avoir changé.

Tech note: since there is a new template (for the userId) we will need to delete all the existing translations.

**Comment by mxandreas** [comment]
> What happen if the user does not have a display name? We repeat the user id like this?
> alice:domain.org's (alice:domain.org) identity appears to have changed

If that is an approach that we're already using somewhere, then I think this is preferred. @americanrefugee WDYT?

**Comment by ara4n** [comment]
the idiomatic thing to do if the user has no displayname is to just show the matrix id (in the alternative font).

**Comment by americanrefugee** [comment]
If the user doesn't have a display name, maybe just show the Matrix ID in bold (no parentheses)? Like this:

**(username@element.io)**'s verified identity has changed.

**Comment by mxandreas** [comment]
> maybe just show the Matrix ID in bold

Generally this an approach that apps use in such cases - when something is missing they omit this in a graceful manner. However, I wonder if in this case it is better to "maintain the structure" (e.g. always have 2 fields - like Benoit suggested) to reduce the potential ways how one can trick somebody with this.

Having said that, it looks safe to start with just showing the MXID in bold (without parentheses) when display name is missing. We can improve later, unless anyone can immediately name any easy attacks.

**Comment by bmarty** [comment]
Just a small tech note, we will need 2 different Localazy entries to manage all the cases here:

`<displayName>'s (<userIdInBold>) identity appears to have changed`

when a display name is available, and 

`<userIdInBold>'s identity appears to have changed`

when there is no display name.

Not a big deal, but we take the risk that the strings are not translated (or even updated) the same way.

**Comment by andybalaam** [comment]
@mxandreas will create tasks for the 3 platforms.

**Comment by mxandreas** [comment]
Created tasks for iOS, Android - linked above. For Web - mentioned it in https://github.com/element-hq/element-meta/issues/2565 as it is still in progress.

cc: @manuroe @andybalaam

**Comment by manuroe** [comment]
@BillCarsonFr for info, all the work is done on the EX side. Thanks @bmarty and @pixlwave ! There is no more EX team members assigned to this issue.

**Comment by mxandreas** [comment]
Closing this as iOS and Android are done, and for Web there is a separate issue for tracking this which has made it to the review.
