### ISSUE TITLE
[Story] U-04: Show a banner & disable composer when Bob's verified-identity has changed

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2570]
#### Show banner
* As Alice
* I want to see when the verified-identity of one of the room members has changed
* So that I would know that ASAP and would not be confused why messages fail to send or sending is blocked.

#### Disable composer
* As a user
* I want the typing in composer be disabled when the verified-identity of one of the room members has changed
* So that it would be clear at once that I need to take action before I can actually send messages again

#### Local notification on Mobile
* As a user on a mobile app
* When I am using a share extension (outside of the app) to send image/photo/.. to a room
* But someone's verified-identity in that room has changed
* Then I want to be notified with a local push notification
* So that it know that sending the message failed because of the verification-violation

#### Withdraw verification
* As a user
* I want to be able to withdraw verification when a verified-identity has changed
* So that I can continue sending messages when immediate re-verification is not possible.

#### Verify again via profile
* As Alice
* I want to navigate quickly to Bob's profile when his verified-identity has changed
* So that I can verify Bob again quickly

Designs:
* [iOS](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=895-9077&t=wA9gdldm7gs1xXoo-4)
* [Android](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=224-33098&t=wA9gdldm7gs1xXoo-4)
* [Web](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=220-47274&t=wA9gdldm7gs1xXoo-4)

### Acceptance criteria

- TBD

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
- [ ] https://github.com/element-hq/element-meta/issues/2719
```

### Subtasks

```[tasklist]
### Android
- [x] Show banner at the composer: https://github.com/element-hq/element-x-android/pull/4126
- [x] Show button to withdraw verification in the banner: https://github.com/element-hq/element-x-android/pull/4126
- [x] Disable composer when the banner is shown: https://github.com/element-hq/element-x-android/pull/4126
- [ ] Add button to go to user profile to verify again.
- [ ] Show local push notification when sending outside of the app.
```

```[tasklist]
### iOS
- [x] Show banner at the composer: https://github.com/element-hq/element-x-ios/pull/3679
- [x] Show button to withdraw verification in the banner:  https://github.com/element-hq/element-x-ios/pull/3679
- [x] Disable composer when the banner is shown: https://github.com/element-hq/element-x-ios/pull/3679
- [ ] Add button to go to user profile to verify again.
- [ ] Show local push notification when sending outside of the app.
```

```[tasklist]
### Rust
```

```[tasklist]
### Web
- [x] Show banner at the composer: https://github.com/element-hq/element-web/pull/29067
- [x] Show button to withdraw verification in the banner: https://github.com/element-hq/element-web/pull/29067
- [ ] Disable composer when the banner is shown: https://github.com/element-hq/element-web/issues/29226
- [ ] Add button to go to user profile to verify again.
- [ ] Bug: Bob's avatar in the banner is not fully visible when limited space is available
- [ ] The red shield with tooltip "Someone is using an unknown session" should *only* be shown when the "exclude inscure devices" FF is turned OFF
```
