### ISSUE TITLE
[Story] U-08B: Room info & People list show that Bob's verified-identity has changed

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2571]
### Description

As Alice
When I go to the room info
Then I want to see if any of the people who I have verified before, have change their identity
So that I am aware of potential malicious parties in this room

As Alice
When I open the people list of a room
Then I can see which of the room members' identity has changed
So that I know how to resolve the issue (who I need to re-verify)

**Designs**
* Room info [iOS](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=224-62765&t=u3djDFGxksLmI0Qt-4) | [Android](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=224-33134&t=u3djDFGxksLmI0Qt-4) | [Web](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=220-47327&t=u3djDFGxksLmI0Qt-4)
* People list [iOS](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=1259-18874&t=u3djDFGxksLmI0Qt-4) | [Android](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=224-33796&t=u3djDFGxksLmI0Qt-4) | [Web](https://www.figma.com/design/0oUTCbYhROEDprSp7bdWhx/Identity-Changes?node-id=220-47328&t=u3djDFGxksLmI0Qt-4)

### Acceptance criteria

- TBD

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] Todo
```

```[tasklist]
### iOS
- [x] Show that Bob's verified-identity has changed in the people list
- [x] Room info (on the People button of non-DM) shows that someone's verified-identity has changed
- [x] Room info (on the Profile button of DM) shows that Bob's verified identity has changed
```

```[tasklist]
### Rust
```

```[tasklist]
### Web
- [x] Show that Bob's verified-identity has changed in the people list
- [ ] Room info (on the People button) shows that someone's verified-identity has changed
- [ ] The tooltip on Bob in the people list should say "Verified identity has changed" instead of "This user has not verified all of their sessions"
- [ ] *Only* show the red "Not trusted" pill in room info when a verified-identity is using an insecure device, and Alice has not turned ON the "exclude insecure devices"
```
