### ISSUE TITLE
[Story] Create a new room (with ask to join & redesign)

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2575]
### Description

**Background**
In order to fit in the option to create a room with the knock join rule, the design of the room creation modal has been revisited to ensure it is optimized for the most common use cases (not to overwhelm users with a lot of choices to think about), and the UX becomes also more consistent between EX and EW.

The main differences that will remain between EX and EW:
* EW continues to allow the creation of a room in the context of a space, hence it will allow a (private) room to be created with the _accessible to space members_ aka _restricted_ join rule. 
* EW keeps the _Block anyone not part of element.io from ever joining this room._ toggle in the _Advanced_ section.

The following 2 tables show how the user controls are mapped to the room configuration, note it does not include obvious 1:1 mappings (e.g. room name or topic).

**EX:**
![image](https://github.com/user-attachments/assets/3548ffcf-7b67-4284-bd5f-56c8bd55d946)

**EW:**
![image](https://github.com/user-attachments/assets/a130da20-97d3-4665-a3c1-bbd464e02019)

It is worth explicitly noting that on EW the E2EE is no longer shown - it defaults to either OFF or ON, depending on room's visibility.

**Conditions**
* When the user is switching between the Private and Public visibility, the subsequent choices are reset to default.
  * E.g. effectively, when user selects Public as visibility, Anyone is always selected as access; and room address is auto-filled (from scratch) using current room name.

**Public room & addresses**
* Alias (in APIs and technical specifications) is a synonym to address (used on UI).
* To control if the room appears in the directory when browsing (e.g. the property _Visibility in room directory_ in the tables above):
  * during room creation, the `visibility` property of the [room creation](https://spec.matrix.org/v1.12/client-server-api/#post_matrixclientv3createroom) API can be used;
  * after creation visibility can be changed using [this API](https://spec.matrix.org/unstable/client-server-api/#put_matrixclientv3directorylistroomroomid).
* A (technical) pre-requisite for the above is that the room has at least one alias:
  * during room creation, the `room_alias_name` of room creation API can be used;
  * for managing aliases later, there are 2 steps with following APIs:
    * create an (local to homeserver) alias with [this API](https://spec.matrix.org/v1.11/client-server-api/#put_matrixclientv3directoryroomroomalias), e.g. `PUT https://beta.ems.host/_matrix/client/v3/directory/room/%23laagri-b%3Abeta.matrix.org`
    * publish the alias through the `m.room.canonical_alias` state event, e.g.  `PUT https://beta.ems.host/_matrix/client/v3/rooms/!vQBVkoHQCPajfjlWBi%3Abeta.matrix.org/state/m.room.canonical_alias/ {"alt_aliases":[],"alias":"#laagri-b:beta.matrix.org"}` 

**Designs:**
- Public room: [iOS](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3286-40352&node-type=frame&t=0b4qFZZxUeviNRKD-11) | [Android](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3317-36051&node-type=frame&t=0b4qFZZxUeviNRKD-11) | [Web](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3286-39638&node-type=frame&t=0b4qFZZxUeviNRKD-11)
- Private room: [iOS](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3270-61279&node-type=frame&t=0b4qFZZxUeviNRKD-11) | [Android](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3273-35405&node-type=frame&t=0b4qFZZxUeviNRKD-11) | [Web](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3270-37463&t=0b4qFZZxUeviNRKD-4)
- Private room (in the context of a space): [Web](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3279-38337&t=0b4qFZZxUeviNRKD-4)

### Acceptance criteria

- The configuration of the created room follows the mapping above.
- When creating a room in the context of a space on EW, the _Private_ visibility is selected by default and the _Accessible to space members_ is selected by default (to keep current behavior).

### Size estimate

None

### Dependencies

- None

### Out of scope

- There is a separate story for auto-filling the room address.

### Open questions

```[tasklist]
### Questions
- [ ] Confirm that EW respect this well-known configuration to enforce E2EE to OFF (always)? If yes, we should keep that logic when creating the room and also apply it in EX. https://web-docs.element.dev/Element Web/e2ee.html#disabling-encryption-by-default
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3689
- [x] Auto-decapitalize letters in the room address - otherwise user is confused, why the room address (with a capital in it) is invalid.
- [x] Remove the placeholder text in room topic, and show it below the text box as indicated in designs.
- [ ] https://github.com/element-hq/element-x-android/issues/3965
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3419
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/4145
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/4151
```

```[tasklist]
### Other
```

**Comment by jmartinesp** [comment]
I've added a couple of PRs that changed the room creation stage in Rust so we can:

- Add a custom join rule (knocking).
- Set a canonical room alias.

Besides that, the existing API already allows you to customise visibility, the preset used for creating the room, and whether E2EE is enabled. I'm not sure if we're missing anything else.

**Comment by mxandreas** [comment]
As a result of the discussion with @gaelledel and @ganfra we have decided to change the permissions for `invite` and `kick` from `admin` to `moderator` when you create a Ask to join room. That means that the only effective difference compared to what we have right now, is that for `invite` you need to be a `moderator`. For `kick`, you already needed to be a `moderator`.

**Comment by mxandreas** [comment]
Made the following update:

**Conditions**
* When the user is switching between the Private and Public visibility, the subsequent choices are reset to default.
  * E.g. effectively, when user selects Public as visibility, Anyone is always selected as access; and room address is auto-filled (from scratch) using current room name.

**Comment by mxandreas** [comment]
This is to confirm the technical side of room publishing, and the address/alias that is required for that. I am pointing this out because this was not implemented in EX before and the topic is not trivial.

* The visibility / publishing of the room in the homeserver's public room directory is done with [this API](https://spec.matrix.org/unstable/client-server-api/#put_matrixclientv3directorylistroomroomid.) 
* The room address/alias (which is a pre-requisite for the above) must be both:
  * A "local address" which is managed with [this API](https://spec.matrix.org/v1.11/client-server-api/#put_matrixclientv3directoryroomroomalias) 
  * A "published address" which is a accomplished with the `m.room.canonical_alias` room event.

cc @ganfra
