### ISSUE TITLE
[Story] Request to join a room

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2577]
### Description

* As a user
* I want to see when access to a public room requires requesting access
* So that I can request access when I am interested in joining the room

The user either has a link to the room or finds the room in the public room directory; and can request access directly in the room directory listing or from the preview of the room (details in the designs).

Side note: if a user receives a link to a room with _private_ visibility and _knock_ or _knock_restricted_ as a join rule, the join rule is not known (spec. limitation). Hence, the user is presented with a generic preview that has an optimistic option to join instead (already the behavior today), which will simply fail in case user needs an invite to this room or needs to knock.

Designs:
* Via room directory: [iOS](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3156-23080&t=0b4qFZZxUeviNRKD-4) | [Android](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3156-57084&node-type=frame&t=0b4qFZZxUeviNRKD-11) | [Web](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3128-40221&t=0b4qFZZxUeviNRKD-4)
* Via a link: [iOS](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3157-59106&node-type=frame&t=0b4qFZZxUeviNRKD-11) | [Android](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3157-60016&node-type=frame&t=0b4qFZZxUeviNRKD-11) | [Web](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3157-28833&node-type=frame&t=0b4qFZZxUeviNRKD-11)

### Acceptance criteria

- User can request access to any room that:
  - The user has no current membership with (e.g. not knocking, not banned, not invited)
  - The room's join rule is either _knock_ or _knock_restricted_

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3690
- [x] Show how many characters are remaining have been entered and how many are allowed. This was an update made to the designs after testing session.
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3420
- [x] Show how many characters are remaining have been entered and how many are allowed. This was an update made to the designs after testing session.
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/4080
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/4150
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/4152
```
