### ISSUE TITLE
[Story] Cancel a request to join

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2578]
### Description

* As a user who has requested access to a room
* I want to cancel my request to join this room
* So that the room admins would not need to manage requests that are no longer relevant (because I changed my mind or requested access to a wrong room for another reason).

The pending requests (for the requester) are shown in their room list, the cancellation is done from the room preview.

**Designs:**
* [iOS](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3156-77999&node-type=frame&t=0b4qFZZxUeviNRKD-11) | [Android](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3157-28434&node-type=frame&t=0b4qFZZxUeviNRKD-11) | [Web](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3156-78202&node-type=frame&t=0b4qFZZxUeviNRKD-11)

### Acceptance criteria

- A user can see all rooms they have requested access to until their request gets declined or accepted.
- A user can cancel their request to join a room until their request gets declined or accepted.

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Known issues
- Bug: cancelling a request to join does not work when the room is on another homeserver (compared to the users account)

### Open questions

```[tasklist]
### Questions
- [x] What is the expected behaviour when room's visibility is changed to private - is the requester able to see their pending request and also cancel it? --> Moved to the epic level
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3691
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3421
```

```[tasklist]
### Rust
- [ ] https://github.com/matrix-org/matrix-rust-sdk/pull/4152
```

```[tasklist]
### Other
```
