### ISSUE TITLE
[Story] Accepting & declining requests to join

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2580]
### Description

**Accepting an individual request**

* As an admin who is managing access to a room
* I want to accept a request from a person who eligible to join
* So that they can join the room

**Accepting all requests**

* As an admin who is managing access to a room
* I want to accept all the pending requests at once when they look eligible
* So that managing large amounts of requests is less effort for me

**Declining an individual request**

* As an admin who is managing access to a room
* I want to decline a request from a person who is not eligible to join
* So that they would not be able to join

**Declining an individual request & banning the person**

* As an admin who is managing access to a room
* I want to stop a person requesting access to a room
* So that I do not constantly have to deal with their (spamming) requests

**Conditions:**

* The admin here is a user with _invite_ or _kick_ permissions on the room;
  * Should the room permissions have been adjusted so that the admin has only _invite_ - the admin is only able to Accept but not Decline (the Decline button is not shown).
  * Likewise if the admin has only _kick_ - the admin is only able to Decline (the Accept button is not shown).
  * Also, the Decline & ban button is only shown if the admin has both _kick_ & _ban_ permissions on the room.
* Should the request be cancelled by the requester just before its accepted or declined (e.g. technically accept/decline fails because of this), this is hidden from the user - e.g. no need to tell the user that “technically” it failed.

**Designs:**
* Room: [iOS](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3162-29609&node-type=frame&t=WLgLSGkvTbo4vMsz-11) | [Android](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3162-29636&node-type=frame&t=WLgLSGkvTbo4vMsz-11) | [Web](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3130-76206&node-type=frame&t=WLgLSGkvTbo4vMsz-11)
* Room side panel: [iOS](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3173-31349&node-type=frame&t=WLgLSGkvTbo4vMsz-11) | [Android](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3177-33987&node-type=frame&t=WLgLSGkvTbo4vMsz-11) | [Web](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3130-73069&node-type=frame&t=WLgLSGkvTbo4vMsz-11)

### Acceptance criteria

* When a request is successfully accepted, the requester receives an invite to join the room.
* When a request is successfully declined, the pending request disappears for the requester.
* When a request is successfully declined & user is banned, the user can no longer request access to the room.
* TBC: should the above work also when meanwhile room's join rule has changed.

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
- [x] If one is changing the room’s join rules (especially to public or restricted), would accepting (e.g. an invite is sent) or declining still work “gracefully”.
- [x] How to also ban the user when declining their request - just needs designs.
- [x] How to remember if admin/moderator has seen (and postponed the decision) a request. Largely a technical question but we may have solution which is local vs. works across clients.
```

### Subtasks

```[tasklist]
### Android
```

```[tasklist]
### iOS
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
- [ ] https://github.com/element-hq/synapse/issues/17929
```

**Comment by mxandreas** [comment]
@ganfra @gaelledel We had a discussion with @Velin92 and @jmartinesp that we should also have an option to ban the user when their request is being declined. I am afraid that this is going to cause friction if we do not have it. Fortunately, this is easy to do from engineering side, so the only thing is to see how to fit this into the designs, e.g. perhaps just have 3rd option "Decline & ban" in the [confirmation modal](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3176-29845&t=l9fMKSscjcQK4aUI-4).

**Comment by mxandreas** [comment]
@ganfra @gaelledel We had a discussion with @Velin92 and @jmartinesp how to remember if the admin/moderator has seen a request in the room (in the banner) and has dismissed/postponed it. We have to remember it, to make sure that the banner does not come up multiple times for the same request.

It is largely a technical question, however, depending on the solution, the behavior may differ for the user a bit:
* We remember it locally in the app - meaning that if the admin/moderator has other apps, they are still seeing the banner in there.
* We remember it globally in the account data - meaning that if the admin/moderator dismisses a request in one app, it will not show up in the others.

If there is no major difference in effort then the global solution is preferred.

**Comment by mxandreas** [comment]
Concluded that we will have the option to Decline & Ban - Gaelle is adding the designs now.

**Comment by manuroe** [comment]
We are aware of https://github.com/element-hq/element-x-android/issues/3790 but it is not a knocking related issue
