### ISSUE TITLE
[Story] Check room's address for invalid symbols and availability

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2585]
### Description

* As a user creating a public room or changing an existing room to be public
* I want to know if the room address is valid (does not have any invalid symbols) and available when I am editing it
* So that I can correct my mistakes instantly; or be happy that the address I desire is available.

Checking the address for both invalid symbols and availability is done "in live" as the user is editing the address.

Since this a functionality that already exists in EW, the algorithm for checking for invalid symbols and other constraints is [borrowed from EW](https://github.com/matrix-org/matrix-react-sdk/blob/b67a2303f912a8cab5caf089f3ea710850aa252c/src/components/views/elements/RoomAliasField.tsx#L162) which currently prevents using the following symbols:
* `:`, `,` and `#`
* anything that would need to be [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding) in a URI.

(Note that Matrix [spec](https://spec.matrix.org/v1.11/appendices/#common-namespaced-identifier-grammar) on identifiers unfortunately does not specify any specific rules for the local part of room alias.)

Same goes for checking if the room address is available - the approach for this can be borrowed from EW and adjusted as necessary.

Note that these checks would need to be applied both at room creation and when changing room settings later.

**Designs:**
* Room address is not available: [iOS](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3944-34958&t=vtLZIBc7pV5PLt2E-4) [Android](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3944-36293&t=vtLZIBc7pV5PLt2E-4) [Web](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3969-93772&t=vtLZIBc7pV5PLt2E-4)
* Room address is not valid: [iOS](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3944-35495&t=vtLZIBc7pV5PLt2E-4) [Android](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3953-36474&t=vtLZIBc7pV5PLt2E-4) [Web](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=3969-94459&t=vtLZIBc7pV5PLt2E-4)

### Acceptance criteria

- When user types a symbol that is not allowed they get a hint that there are invalid symbols.
- When user corrects their mistakes and the address is valid, the hint for invalid symbols disappers.
- When user enters an address that is valid but not available they get a hint that the address is already in use.
- TBC: When user enters an address that is valid and available they get a confirmation that the address is available (applicable to EW only).

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
- [x] The Matrix spec. does not specify much for the room alias (its local part), thus what is currently on EW is expected to be its own "best practice". We should use this as a reference.
- [x] If we can check availability of the room address "live" on EX - Ganfra to confirm.
- [x] If to keep a "green confirmation" when the room is available on EW (decided not introduce on EX) - Gaelle to confirm. --> how it is working is fine
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3866
```

```[tasklist]
### iOS
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```

**Comment by mxandreas** [comment]
It seems the Matrix spec does not define a clear grammar for the local part (#local_part:homeserver.com) of the room alias, and thus what's implemented on EW, seems to be its own best practice. As there is no good reason to change it, and we want the clients to be in sync - @florianduros could you please point out the code in EW which validates the room alias, so we can use this as a reference when implementing in EX and also use to describe to user on UI what is allowed and what is not.

**Comment by mxandreas** [comment]
@jmartinesp Has found the corresponding [code](https://github.com/matrix-org/matrix-react-sdk/blob/b67a2303f912a8cab5caf089f3ea710850aa252c/src/components/views/elements/RoomAliasField.tsx#L162) in EW, this prevents using:
* `:`, `,` and `#`
* anything that would need to be [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding) in a URI.

We will stick to this implementation as a change is currently not justified, and not directly related to the scope. The tips on the UI for the end user may be slightly more restrictive for the purpose of keeping it understandable for them.

**Comment by jmartinesp** [comment]
FWIW this is already handled in Rust in the Ruma crate. Maybe instead of adding custom logic per-client we should create a shared `fn is_valid_room_alias(raw: String) -> bool` in Rust that tries to create an alias from a raw string, and returns true if it can be created?

**Comment by mxandreas** [comment]
A note that for checking the availability of the address, EW is using [this API](https://spec.matrix.org/v1.11/client-server-api/#get_matrixclientv3directoryroomroomalias), e.g. making a GET request to:
```
https://beta.ems.host/_matrix/client/v3/directory/room/%23xy%3Abeta.matrix.org
```

**Comment by mxandreas** [comment]
Updated the description to confirm that we check the availability as well as invalid symbols "live" as user is editing the address.

**Comment by mxandreas** [comment]
Agreed that we do not introduce the "green confirmation" that address is available on EX. To be decided if we keep it on EW where it already exists.
