### ISSUE TITLE
[Story] Differentiate between room previews depending on join rules

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2586]
#### Background

In order knocking to work, the join rules of the room need to be accessible to a user that is not yet member of the room. This was a challenge because even for rooms which were published in the room directory (and thus the information was available in principle), there was no proper API for getting the info & join rules by room alias or ID (the publicRooms API was not designed for that purpose). This led to getting MSC3266 into production (provides the necessary roomSummary API) and thus also revisiting the different scenarios the user may encounter.

For the context, the diagram below depicts all the different scenarios and room previews.
![image](https://github.com/user-attachments/assets/d53408ec-52d5-4f7d-977a-6a465eedfda9)

The overall goal is to minimize the chance that the user is presented with misleading information or actions when they get a link to a room or find it in the room directory.

#### Scope

In the **scope of this story, there are 3 previews** in which either the join rules are not known and/or the user may not be be able to join the room:
 1. **RP-06**: The room info & join rules are available but the join rule is `invite`. This means that the user can not join the room without an invite. The user are shown the room information, but are informed that they need an invite; and there is no button to join.
 2. **RP-07**:  The room info & join rules available but the join rule is `restricted`. This means that the user is able to join only **if** they are member of a space (that is authorized for joining this room). However, the latter this is not straightforward to be checked in advance - thus user is shown the room information and a join button but they are warned that joining requires membership of a space, thus might fail.
 3. **RP-08**: The room info & join rules are not available. This scenario should be much less likely with MSC3266 implemented, but can still happen. The user is informed that information about this room is not available and joining it may require an invite or being part of a space.

In the case of RP-07 and RP-08, joining is expected to fail. In that case the user is expected to receive a meaningful non-technical message about that. The same non-technical message can be used whenever the joining the room is logically denied (e.g. it does not fail because of a technical/network errors but the user does not have the right to join the room).

**Designs:**
* RP-06: [iOS](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=4766-44300&t=ZHTufDa6EuwfhOkk-4) | [Android](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=4797-42582&t=ZHTufDa6EuwfhOkk-4) | Web
* RP-07: [iOS](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=4951-76620&t=ZHTufDa6EuwfhOkk-4) | [Android](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=4967-43816&t=ZHTufDa6EuwfhOkk-4) | Web
* RP-08: [iOS](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=4951-76735&t=ZHTufDa6EuwfhOkk-4) | [Android](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=4967-43856&t=ZHTufDa6EuwfhOkk-4) | Web
* Joining denied: [iOS](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=4951-76857&t=imTLdbowOq7ENu8q-4) | [Android](https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=5153-58419&t=ZHTufDa6EuwfhOkk-4) | Web

### Acceptance criteria

- The user is shown the correct preview and they understand what to expect.

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/4141
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3677
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
- [x] Design of the room preview - RP-06 scenario.
- [x] Design of the room preview - RP-07 scenario.
- [x] Design of the room preview - RP-08 scenario.
- [x] Design of the error message when joining fails in RP-07 and RP-08.
```

**Comment by mxandreas** [comment]
@gaelledel We need a few designs for this story - have look at the "Other" task list in the issue for details.

**Comment by gaelledel** [comment]
You can find all room previews in Figma for EX. Web will follow https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=4766-43955&t=g2HrRvguv9eR0eDz-4

**Comment by morguldir** [comment]
Can i also suggest a room not being joinable due to the room version not being supported by the server? (some room versions also require client support but that's probably rarer)

Checking if the room version supports knocking might also be a good idea, but i don't know if that's something that will happen often

Optimistic knocking might also be worth adding? I think nheko and element web does that, although it does seem harder to get right
