### ISSUE TITLE
[Story] EX: UX Redesign of Settings > Encryption

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2590]
### Description

The UX of setting up a recovery (key) and turning OFF/ON the server-side key storage has been revisited with the main purpose is to allow the end users to make a much better sense of it.

The designs have been revisited cross-platform, both EW and EX, and it is desired that the implementation of those are not too far apart; **this story only applies to EX** as the starting point for EW and EX is different. EW needs to do structural changes to Settings while EX only needs to change the copy and minor visual aspects.

The scope is the Settings > Encryption (currently Chat backup) menu which has 3 scenarios from user perspective:
* Setting up the recovery: [iOS](https://www.figma.com/design/qTWRfItpO3RdCjnTKPu4mL/Settings?node-id=1658-57590&node-type=instance&t=mqpyPMK4kAT0kSdR-11) | [Android](https://www.figma.com/design/qTWRfItpO3RdCjnTKPu4mL/Settings?node-id=1658-57591&node-type=instance&t=mqpyPMK4kAT0kSdR-11)
* Changing the recovery key: [iOS](https://www.figma.com/design/qTWRfItpO3RdCjnTKPu4mL/Settings?node-id=1669-29581&node-type=instance&t=mqpyPMK4kAT0kSdR-11) | [Android](https://www.figma.com/design/qTWRfItpO3RdCjnTKPu4mL/Settings?node-id=1669-29875&node-type=instance&t=mqpyPMK4kAT0kSdR-11)
* Turning the key storage OFF: [iOS](https://www.figma.com/design/qTWRfItpO3RdCjnTKPu4mL/Settings?node-id=1671-30687&node-type=frame&t=mqpyPMK4kAT0kSdR-11) | [Android](https://www.figma.com/design/qTWRfItpO3RdCjnTKPu4mL/Settings?node-id=1671-30701&node-type=frame&t=mqpyPMK4kAT0kSdR-11)

The sub-menu End-to-End Encryption with the functions to Export / Import Keys and Reset end-to-end encryption is currently not in scope.

### Acceptance criteria

- UI corresponds to the linked design.

### Leads

* Tech:  @pixlwave 
* Design: <GitHub id>

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/3737
- [ ] https://github.com/element-hq/element-x-android/issues/3738
- [ ] https://github.com/element-hq/element-x-android/issues/3739
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3446
- [ ] https://github.com/element-hq/element-x-ios/issues/3447
- [ ] https://github.com/element-hq/element-x-ios/issues/3448
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
- [x] The help page needs to be updated accordingly: https://element.io/help#encryption
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by mxandreas** [comment]
cc @manuroe

**Comment by bmarty** [comment]
@mxandreas done on Android with https://github.com/element-hq/element-x-android/pull/3750, can you please check the video there and confirm that it matches what you are expecting?

@americanrefugee please let me know if I missed anything. Thanks!

**Comment by americanrefugee** [comment]
LGTM @bmarty

**Comment by americanrefugee** [comment]
I noticed one thing:
After generating/saving the recovery key and clicking "Done", the user should see [this confirmation page](https://www.figma.com/design/qTWRfItpO3RdCjnTKPu4mL/Settings?node-id=1658-57357&t=GkLIQCvuN1TlUG2w-4).

**Comment by americanrefugee** [comment]
Sorry, one more thing:

After setting up the recovery key, the [Settings menu item](https://www.figma.com/design/qTWRfItpO3RdCjnTKPu4mL/Settings?node-id=1658-57439&t=GkLIQCvuN1TlUG2w-4) should simply say "Change recovery key" without any additional help text.

At least that's what was designed. @mxandreas do you agree?

**Comment by mxandreas** [comment]
> At least that's what was designed. @mxandreas do you agree?

So, the additional help text should only be removed "for a moment" after the setup. If you come back later to the Encryption settings, then the help text should be there again?

I do not mind that, but I am curious what is the reasoning for this? It is not obvious for me.

**Comment by bmarty** [comment]
> I noticed one thing: After generating/saving the recovery key and clicking "Done", the user should see [this confirmation page](https://www.figma.com/design/qTWRfItpO3RdCjnTKPu4mL/Settings?node-id=1658-57357&t=GkLIQCvuN1TlUG2w-4).

@americanrefugee the dialog is displayed if the user does not click on the button to copy the key. See below:

https://github.com/user-attachments/assets/1916def5-ab19-4afe-8dfc-b94cdf3b7102

Do you want this dialog to always be displayed?

**Comment by americanrefugee** [comment]
> So, the additional help text should only be removed "for a moment" after the setup. If you come back later to the Encryption settings, then the help text should be there again?
> 
> I do not mind that, but I am curious what is the reasoning for this? It is not obvious for me.

On second thought, I guess it doesn't make sense to remove the help text. I shall add it back in the design.

> the dialog is displayed if the user does not click on the button to copy the key.

Ah, I forgot about that nuance. Let's keep it as you've implemented it. Sorry for the runaround!

**Comment by pixlwave** [comment]
The changes are now available on the latest iOS Nightly (744).

**Comment by manuroe** [comment]
> The help page needs to be updated accordingly: https://element.io/help#encryption

The web page received an update.
<img width="465" alt="image" src="https://github.com/user-attachments/assets/6b8d195e-b7b0-44f8-9cb2-683188d76783" />

I am ticking this very last taks and close this epic. Thanks everyone!
