### ISSUE TITLE
[Story] Regression on: Stopping ongoing (CallKit) ringing if the other devices takes the call

### ISSUE THREAD

**Issue by fkwp** [vector-im/element-meta#2599]
### Description

We have a regression on stopping ongoing call ringing if the other devices meanwhile takes the call:
* Using Element X 1.9.3 (134) on iPad 
* If the app is in foreground ringing stops
* During Lockscreen or if the app is in background ringing/CallKit does NOT stop

(same was reported for Element X on Android)

### Acceptance criteria

- Call ringing stops of the call is meanwhile picked up by another device of that user

### Leads

Being discussed here: https://matrix.to/#/!yuFzMhMqKzNFvoLqcJ:one.ems.host/$-5uGJAL-TIJwvkNOVzKgYgaFrviOHC9VPgQ0CPrTbVc?via=matrix.org&via=element.io&via=robin.town

https://github.com/element-hq/element-x-ios/pull/3442 included https://github.com/matrix-org/matrix-rust-sdk/blob/bb55493a47fafb5f45c0e337cb076252d101702a/crates/matrix-sdk-ui/src/room_list_service/mod.rs#L90 which was the necessary fix to get m.call.member state synced into the App. 

Now I am wondering if we need something similar for the push notification workers.

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/pull/3842
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/pull/3487
- [ ] https://github.com/element-hq/element-x-ios/pull/3488
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```

### Android
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

### iOS
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

**Comment by fkwp** [comment]
https://developer.apple.com/forums//thread/767949?answerId=812951022#812951022

**Comment by fkwp** [comment]
Tested on Android 0.7.4 nightly (40007040, 11:12AM) which still keeps ringing if:

- the caller hangs up the call
- the call is taken by another device of the callee
