### ISSUE TITLE
Device Dehydration: Cache Dehydration Key

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#2603]
Currently, the dehydration key is only kept in memory, which means that when the client gets restarted, it will no longer have the dehydration key, and will not be able to create new dehydrated devices. We need to cache it in the crypto store so that the SDK can fetch it on statup

```[tasklist]
### Tasks
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/4186
- [ ] https://github.com/matrix-org/matrix-rust-sdk-crypto-wasm/issues/160
- [ ] https://github.com/matrix-org/matrix-js-sdk/issues/4483
- [ ] https://github.com/matrix-org/matrix-js-sdk/issues/4484
- [ ] https://github.com/element-hq/element-web/issues/29031
```

**Comment by uhoreg** [comment]
Done!
