### ISSUE TITLE
[Story] Add a caption when sending a media file

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-meta#2617]
### Description

* As a user
* I want to be able to include a caption when sending some media
* So that I can add context to the media in the same message.

### Acceptance criteria

- A composer is shown at the bottom of the media preview screen.
- Its caption is optional: when nothing is entered, no caption will be added to the media.
- Entering formatting using markdown should work as it does in the regular composer.

### Size estimate

None

### Dependencies

- None

### Out of scope

- As EX doesn't (yet) support sending multiple pieces of media, we don't need to consider what would happen in this instance.
- We don't need to use the RTE to create formatted captions.

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/2573
- [ ] https://github.com/element-hq/element-x-android/issues/3884
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3508
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```
