### ISSUE TITLE
[Story] Show to a user that they are banned from the room

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2653]
### Description
* When I am opening a preview of a room that I am banned from
* I want to see that I am banned from this room
* So that I know I am banned from this room and the reason for it

This is a product debt only on EX, EW is handling this case already correctly.

### Acceptance criteria

- When a user opens a room they are banned from, they will see that they are banned.

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/issues/4142
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/issues/3678
```

```[tasklist]
### Rust
- [x] Allow sending down membership sender data and optional reason
```

```[tasklist]
### Other
- [x] Design of the banned room preview.
```

**Comment by mxandreas** [comment]
@gaelledel We need design here for the room preview when user is banned.

**Comment by gaelledel** [comment]
Done for iOS and Android. Web will follow soon.  https://www.figma.com/design/7TqjqdMBaPpm3IavKsMYu6/Ask-to-join-(Knocking)?node-id=4766-41746&t=T301BxViGICZkegl-4

**Comment by hanadi92** [comment]
@mxandreas I think the rust sdk has the membership reason already implemented through ffi here https://github.com/matrix-org/matrix-rust-sdk/pull/4529
