### ISSUE TITLE
[Prep] EX: Stop receiving the app badge count from the homeserver

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2654]
### Description

Implement https://github.com/matrix-org/matrix-spec-proposals/pull/4076 so that the backend do not control anymore the app badge count.

It is also useful to stop having unread update pushes on Android because they are useless, could be considered as push spams and may be a reason why push gateway blocks some pushes (which means no notifications for the end user)

# Acceptance criteria
- The app badge count on EXI is not more updated by the homeserver
- EXA does not receive anymore unread update pushes that are useless on Android

# Size estimate
S

# Dependencies    
- None

# Out of scope
- 

# Subtasks

### Android
- https://github.com/element-hq/element-x-android/issues/5316

### iOS
- https://github.com/element-hq/element-x-ios/issues/3572

### SDK
- [ ] Ruma implementation of `disable_badge_count`: https://github.com/ruma/ruma/pull/2214
- [ ] https://github.com/matrix-org/matrix-rust-sdk/issues/4951

### MSC
- [ ] https://github.com/matrix-org/matrix-spec-proposals/pull/4076

### Synapse
- [x] https://github.com/element-hq/synapse/pull/17975
- [ ] https://github.com/element-hq/synapse/pull/18930

### Other
- [ ] Enable MSC4076 in beta.matrix.org for end to end testing
- [ ] Done in ESS and m.org, ie make MSC4076 enabled

**Comment by manuroe** [comment]
EDIT: I updated this prep story to include Android in order to reduce push bandwidth and reduce the risk of push requests being ignored by the push gateways.

**Comment by manuroe** [comment]
@jmartinesp will do the implementation client side: Ruma --> SDK --> EXA.

**Comment by manuroe** [comment]
With https://github.com/element-hq/synapse/pull/18930, we should be able to use MSC4076 end to end. It will be enabled first on beta.matrix.org.

**Comment by manuroe** [comment]
After an internal discussion, we decided to manage the configuration at the Sygnal instance configuration level. It means https://github.com/matrix-org/matrix-spec-proposals/pull/4076 is no more involved in the plan. We close this tech story in favour of https://github.com/element-hq/element-meta/issues/3014.
