### ISSUE TITLE
EX apps adopt Calendar Versioning

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-meta#2664]
EX apps are going to adopt [CalVer](https://calver.org/). We do this to align EXA and EXI versions, which are currently 0.7.5 and 1.9.9. Talking about 25.01 versions of EX apps will be simpler.
Support will be easier. It will be quicker to scan GH issues or bug reports.

Our implementaion is:

**YY.0M.patch**

`patch` resets every month. It is not necessarly the same on both platform. We could have hotfix releases on one but not the other.
YY.0M corresponds to the planned release date. We will set it manually

Nightly will use `patch+1`.

# Subtasks
```[tasklist]
### Questions
- [x] Is `YY.0M` for the day of the build or the day of the release on the stores? --> Release on the store
```

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-x-android/pull/4187
- [ ] https://github.com/element-hq/element-x-android/pull/4192
- [x] 25.02.0 is published
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-x-ios/pull/3705
- [ ] https://github.com/element-hq/element-x-ios/pull/3721
- [x] 25.02.0 is published
```

**Comment by t3chguy** [comment]
> Talking about 25.01 versions of EX apps will be simpler.
Support will be easier. It will be quicker to scan GH issues or bug reports.
>Our implementaion is:
>YY.MM.patch

These statements are inconsistent

`MM` would be `1` not `01` - could you clarify which you are going with?

![Image](https://github.com/user-attachments/assets/57c9418f-65f1-410c-b1fa-1bdcc3668071)

I would suggest the former to maintain compatibility with semver parsers.

> YY.MM corresponds to the planned release date. We will set it manually

Makes sense, it is a pain that it has to be set manually, this is one thing that semver has better, we can just bump using rules based on the changes going into the release (breaking or not)

> Nightly will use patch+1.

This seems confusing, so would the 2nd release of the month have a conflicting version with a release build?

We've decided to switch Element Web & Desktop over to calver based on the reasons listed here and the main thing we disagree with is the Nightly version we will be using.

For us we have gone with `YY.MM.90D-nightly.patch` the `9` prefix in the micro segment is to ensure Nightly versions are always a higher number than release versions to make it abundantly obvious something is a nightly even if the modifier got lost. We may need to drop the dot between `nightly` and the patch variable for NuGet compatibility.

**Comment by manuroe** [comment]
Oops. Thanks for raising the problem. We are **YY.0M** to follow ESS versioning. I udpated the ticket.


> > Nightly will use patch+1.
> 
> This seems confusing, so would the 2nd release of the month have a conflicting version with a release build?

Yes. We are limited on 3 digits on iOS. Collisions are inevitable. We do have a build number. The OS does not make it easily visible for end users but we use it to differentiate the nightlies. It appears in the rageshakes for example.

**Comment by bmarty** [comment]
EXA does not upgrade version for the nightly build (yet?). It was the case before we migrate to calver. It means that after release 25.02.0, the next nightly builds will have version 25.02.0.

It's possible to restore the previous behavior and let the nightly builds use 25.02.1, even if the next release could be 25.03.0 (or any higher version).

We do not have the constraint to increase the value for each build.

**Comment by manuroe** [comment]
Just checked Play Store. The android calendar version is publicly available.
We can happily close this work

Long live CalVer!
