### ISSUE TITLE
[Story] Guide new Element *classic* users with MAS HS to use EX

### ISSUE THREAD

**Issue by mxandreas** [vector-im/element-meta#2674]
### Description

Around February 2025 matrix.org is about to be migrated to MAS. This means that creating new accounts will no longer be possible with Element *classic* mobile apps, as it does not have support for that. Support is also not going to be added as the *classic* apps will be soon sunset.

At this moment, when trying to create an account with Element *classic* app on a HS that has MAS, a confusing error is shown.

The goal is to guide users whose homeserver has got MAS, to use EX and tell that the *classic* app will soon be sunset. There is no change or impact to users whose HS does not have MAS.

The designs are available [here](https://www.figma.com/design/xdV4PuI3DlzA1EiBvbrggz/Login-Flow-v2?node-id=7014-3378&t=zkHrXo6lb8WaM1ng-4).

![image](https://github.com/user-attachments/assets/e8bd0ba0-97c4-4c0d-9ac2-827afc42cd4a)

##### When the warning must be displayed

The warning "You can no longer create an account..." must be displayed when the login flow type is `m.login.sso` and the boolean `org.matrix.msc3824.delegated_oidc_compatibility` exist and is set to `true`. See more details here: https://github.com/matrix-org/matrix-spec-proposals/blob/hughns/sso-redirect-action/proposals/3824-oidc-aware-clients.md#homeserver-indicates-that-an-mloginsso-flow-is-for-compatibility

On Element Android, this boolean already exists so there were no change to do to get the info.

##### Feature flag

In order to let fork handle the migration smoothly, we will use a build config for this feature.

I have draft a config for Android:
```kotlin
sealed interface SunsetConfig {
    /**
     * Sunsetting the application is disabled.
     */
    data object Disabled : SunsetConfig

    /**
     * Sunsetting the application is enabled and can be configured by implementing this class.
     */
    data class Enabled(
            /**
             * The URL target to learn more.
             */
            val learnMoreLink: String,

            /**
             * The replacement application ID.
             * Example: for Element application, the replacement application ID is the id of Element X: "Element X".
             */
            val replacementApplicationName: String,

            /**
             * The replacement application ID.
             * Example: for Element App, the replacement application ID is the id of Element X: "io.element.android.x".
             */
            val replacementApplicationId: String,
    ) : SunsetConfig
}
```

and an implementation for Element Android:

```kotlin
    /**
     * Sunsetting the application.
     * Fork maintainers can use this to inform users about their new application if any. Note that you probably also want
     * to replace the resource `replacement_app_icon` too.
     */
    val sunsetConfig: SunsetConfig = SunsetConfig.Enabled(
            // TODO: update this URL.
            learnMoreLink = "https://element.io/",
            replacementApplicationName = "Element X",
            replacementApplicationId = "io.element.android.x",
    )
```

@mxandreas we will need the url for the learn more action before releasing the application.

### Acceptance criteria

- TBD

### Size estimate

None

### Dependencies

- None

### Out of scope

- Nothing

### Open questions

```[tasklist]
### Questions
```

### Subtasks

```[tasklist]
### Android
- [ ] https://github.com/element-hq/element-android/issues/8981
- [x] EA 1.6.28 is available on the store
```

```[tasklist]
### iOS
- [ ] https://github.com/element-hq/element-ios/issues/7889
- [x] EI 1.11.23 is available on the store
```

```[tasklist]
### Rust
```

```[tasklist]
### Other
```

**Comment by manuroe** [comment]
Both classic apps are not publicly available 🥳
