### ISSUE TITLE
Threads P0: Web

### ISSUE THREAD

**Issue by novocaine** [vector-im/element-meta#3]
View [MSC3440 Threading via m.thread relation](https://github.com/matrix-org/matrix-doc/pull/3440)

View [🧵 Threads board](https://github.com/orgs/vector-im/projects/17)

# Must Haves

- [x] **Start a Thread by replying to a message in Timeline**
  - Using the Message action bar, choose a message from the Timeline to start a Thread by sending a response (that does not show in the Timeline)
  - _Design_ https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1150%3A202551
  - https://github.com/vector-im/element-web/issues/19388
- [x] **Respond to a Thread**
  - See a Thread, and send a message in response (that does not show in the Timeline)
  - _Design_ https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1150%3A202552
  - _Issue_
- [x] **See/Read previous responses in a Thread in the right order (Thread history)**
  - When I click to read a Thread, I should be able to see previous responses in the correct order
  - Messages in Threads mustn't be dropped due to gaps in the client's local Timeline
    - Backend support for retrieving messages in a Thread
    - Client hooked up to the backend API
    - https://github.com/vector-im/element-web/issues/19225
    - https://github.com/vector-im/element-web/issues/19762
- [x] **See/Read all Threads in a Room**
  - If I'm in a Room, I need to be able to scroll up through the Timeline and click to read a Thread
  - See all the Threads in a room in the Thread list view
  - _Design_ https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1150%3A202555
  - https://github.com/vector-im/element-web/issues/18957
  - https://github.com/vector-im/element-web/issues/19541
  - https://github.com/matrix-org/synapse/issues/11086
- [x] **See/Read all Threads I have responded to in a room**
  - Be able to see Threads I have responded to in a Room in the Room Threads list view
  - _Design_ https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1150%3A202557
  - _Issue_
    - Requires Backend API
    - vector-im/element-web#18957
    - vector-im/element-web#19396
    - Requires https://github.com/matrix-org/synapse/issues/11086
- [x] **See Thread Summary from Timeline**
  - From the Timeline I should be able to see a summary of the Thread
  - _Design_ https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1150%3A202552
  - https://github.com/vector-im/element-web/issues/18958
  - https://github.com/vector-im/element-web/issues/18531
  - https://github.com/vector-im/element-web/issues/18986
  - https://github.com/vector-im/element-web/issues/19588
- [x] **Send a link to a Thread**
  - Share a Thread message, in the same way I can Share a Room message including a Matrix.to link
  - _Design_ https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1150%3A202553
  - https://github.com/vector-im/element-web/issues/18954
- [x] **Search results from Threads**
  - When I search for a message, return results from a Thread
  -  _Design_ (pending)
  - https://github.com/vector-im/element-web/issues/19196
  - [x] Unencrypted Rooms: Driven by backend search results
  - [x] Encrypted Rooms: 
  - https://github.com/vector-im/element-web/issues/19197
- [x] **See Threads as Reply if don’t have Threads** 
  - If a client/bridge does not have Threads enabled, Thread responses show as Replies in the Timeline
  - _Issue_ vector-im/element-web#19389
  - _Issue_ vector-im/element-android#4246
  - _Issue_ vector-im/element-ios#5007
  - _Issue_ vector-im/hydrogen-web#552
  - [ ] Reach out to Nheko maintainers about this?
  - [ ] Reach out to Fluffy Chat maintainers about this?
- [x] **Find a Thread through Mentions** 
  - _Design_ https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1216%3A234786
  - _Issue_ https://github.com/vector-im/element-web/issues/19126
  - [x] ~~Including when user is not in a Room~~ 
    - This is not possible today and so it not needed for Threads
- [x] **Message action bar for events in Thread**
  - _Design_ https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1150%3A202553
  - _Issue_
  - [x] Remove Reply in Thread from Message options
  - [x] Add "View in Room" option to Root Thread event 
    - https://github.com/vector-im/element-web/issues/18955
  - [x] Allow Reply from Thread response, in Thread view
    - https://github.com/vector-im/element-web/issues/19206
    - https://github.com/vector-im/element-web/issues/19161
- [x] **Be aware of new activity on a Thread**
  - New activity on a Thread is visible to me from the Timeline and from the Thread view
  - _Design_ https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1216%3A234786
  - _Issue_ https://github.com/matrix-org/synapse/issues/11085
  - https://github.com/vector-im/element-web/issues/19126
- [x] **Room Notification count for Thread events**
  - https://github.com/vector-im/element-web/issues/19126
- [x] **Participation info must be shared across all clients**
  - _Issue_
- [x] **Create Thread deleted state UI for when root message removed**
  - _Design_ https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1150%3A202558
  - https://github.com/vector-im/element-web/issues/18956
- [x] **Up arrow key to edit event when Thread view is open**
  - https://github.com/vector-im/element-web/issues/18981
- [ ] **Create Automated tests for Threads P0**
  - https://github.com/vector-im/element-web/issues/19199
  - Add relevant tests to ensure good stability
- [x] **P0 smoke testing** @kittykat
  - https://github.com/vector-im/element-web/issues/19690
- [x] **P0 acceptance testing** @kittykat
  - https://github.com/vector-im/element-web/issues/19691
- [ ] **P0 user testing** @kittykat
  - https://github.com/vector-im/element-web/issues/19692
- [x] **Launch plan TBD** @daniellekirkwood 
  - https://github.com/vector-im/element-web/issues/19270

- [x] [New - January 2022] Labs flag (threads was already behind a labs flag and therefore no issue is needed for this)
- [ ] [New - January 2022] Disable Threads State Event for Rooms with Bridges https://github.com/vector-im/internal-planning/issues/193

# Backend issues
- [x] https://github.com/matrix-org/synapse/issues/11085
- [x] https://github.com/matrix-org/synapse/issues/11086
- [x] https://github.com/matrix-org/synapse/issues/11087

# Misc

- [x] https://github.com/vector-im/element-web/issues/19127
- [x] https://github.com/vector-im/element-web/issues/18720
- [x] https://github.com/vector-im/element-web/issues/19542
- [x] https://github.com/vector-im/element-web/issues/19616
- [x] https://github.com/vector-im/element-web/issues/19612
- [x] https://github.com/vector-im/element-web/issues/19587
- [x] https://github.com/vector-im/element-web/issues/19580
- [ ] https://github.com/vector-im/element-web/issues/19762
- [x] https://github.com/vector-im/element-meta/issues/59
- [x] https://github.com/vector-im/element-web/issues/20603

**Comment by telmich** [comment]
I was looking for an option in element-web to opt-in users automatically into threading, without going to the labs menu - is this already an option? (Did not find it, that's why I am asking here)

**Comment by t3chguy** [comment]
@telmich you can tweak default values via config.json e.g https://develop.element.io/config.json does with `feature_spotlight` - See https://github.com/vector-im/element-web/blob/develop/docs/labs.md for full list
