### ISSUE TITLE
Implement Posthog for Analytics tracking in Mobile

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#57]
_This issue is WIP_

In Q4 of FY21 we need to implement Posthog tracking for analytics on mobile so that we have more detail and data regarding the use of our products. 

[The web issue is here](https://github.com/vector-im/element-meta/issues/10)

## Mobile considerations
- Users should be asked to provide consent on each device.
  - When consent is granted on one device... wip, lorem ipsum
  - When consent is denied or removed on one device... wip, lorem ipsum
- Consent must be granted for each user on each device they log in to

## Product & Design
- Requesting access for analytics tracking should appear as early as possible in the user's signup/signin experience. It is important that we ask during log in as well as sign up as some users may have created their accounts elsewhere.

### Product Tasks
- [ ] What Product questions do we have for clients? (Driver: Danielle)

### Design Tasks
- [x] https://github.com/vector-im/element-meta/issues/41

We're looking for 2 solutions;
- [x] A quick solve that unblocks engineering and provides baseline of opt-in rate for future learning. See [here](https://docs.google.com/document/d/1OGJX54wrsMZ4GB_-LT7bdpmwaDpIqxJI1aAzE3NJJc4/edit?usp=sharing)
- [x] A understanding of where this question is best placed during the onboarding flow & log in flow

## iOS 
iOS currently has Matomo tracking. 
- When ready, new users will be requested to grant consent for Posthog tracking
- Current users will be requested to grant consent for Posthog tracking

### iOS Tasks
- [x] https://github.com/vector-im/element-ios/issues/5035

## Android
- Current users will be requested to grant consent for Posthog tracking

### Android Tasks
- [x] https://github.com/vector-im/element-android/issues/4399

**Comment by daniellekirkwood** [comment]
Requirements: 
- For all consent forms we must provide equal Agree and Disagree buttons
- Change wording from 'personal data' to 'account data'
- Provide a link to the cookie policy: https://element.io/cookie-policy

**Comment by daniellekirkwood** [comment]
There's documentation [here](https://docs.google.com/document/d/1OGJX54wrsMZ4GB_-LT7bdpmwaDpIqxJI1aAzE3NJJc4/edit?userstoinvite=benoitm@element.io&actionButton=1#heading=h.nw8q00hprez9)

### TL;DR
**Approvers**
Denise, James, and Amsha should be additional approvers to the PR.

**Designs**
[Figma file](https://www.figma.com/file/nt8rhrQ9arytjKUl5omfYj/%23157-Analytics-prompt?node-id=137%3A14965)	
- There are 2 variations; one for users who previously said no & one for users who previously said yes
- There are screens for each platform (iOS & Android)

**When to ask:**
For existing users: 
- Who previously said no: Once, on app open after upgrade to newest version
- Who previously said yes: Once, on app open after upgrade to newest version

For new users:
- Utilise the “previously said no” screen for now
- Short-term: First time the user hits home screen
- Long-term: Is a part of the FTU flow (not a part of this issue)
