### ISSUE TITLE
Queue and retry to-device msgs, so E2EE works in bad networks or with unreliable HS

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#673]
Queue the to-device messages. We should make sure that we retry to-device messages. New implementation on web saves them in a queue to persistent storage to be sent when they can be.

These issues must be resolved for this issue to be considered done:

```[tasklist]
### Tasks
- [ ] vector-im/element-web/issues/12851
- [ ] matrix-org/matrix-js-sdk/pull/2549
- [ ] vector-im/element-android/issues/6689
- [ ] matrix-org/matrix-ios-sdk/issues/1538
```

**Comment by dkasak** [comment]
Should be noted that https://github.com/matrix-org/matrix-js-sdk/pull/2549 only retries room key (Megolm session) sending; other to-device messages are still not retried. This is tracked in https://github.com/matrix-org/matrix-js-sdk/issues/1866.

**Comment by jdauphant** [comment]
@giomfo maybe we can push this ticket to solve part of our keys sharing problems.

**Comment by pmaier1** [comment]
According to @BillCarsonFr, this will be solved for other platforms once we have Element R integrated which will happen soon. 
The web-specific part (https://github.com/vector-im/element-meta/issues/673#issuecomment-1273260166) will also be fixed by integrating the rust SDK.

**Comment by pmaier1** [comment]
@BillCarsonFr Can you close this and the related tasks if they are solved by Element R? Thanks!
