### ISSUE TITLE
Threads P0: Android

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#7]
- View [MSC3440 Threading via m.thread relation](https://github.com/matrix-org/matrix-doc/pull/3440)
- View 🧵 [Threads project board](https://github.com/orgs/vector-im/projects/17)

# Android Must Haves

- [x] https://github.com/vector-im/element-android/issues/4328
  - Using the Message action bar, choose a message from the Timeline to start a Thread by sending a response (that does not show in the Timeline)
  - [Design: Ready - Long press on message](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1304%3A244131)

- [x] https://github.com/vector-im/element-android/issues/4329
  - See a Thread, and send a message in response (that does not show in the Timeline)
  - [Design: Ready](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1304%3A244141)
  - https://github.com/vector-im/element-android/issues/4474

- [x] **See/Read previous responses in a Thread in the right order (Thread history)**
  - When I click to read a Thread, I should be able to see previous responses in the correct order
  - *This is acceptance criteria and does not need a design*
  - https://github.com/vector-im/element-android/issues/4331

- [x] **See/Read all Threads in a Room & Thread List view**
  - If I'm in a Room, I need to be able to scroll up through the Timeline and click to read a Thread
  - From the Timeline, I can use the Thread icon to view the Thread List view
  - [Design](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1304%3A244141)
  - [Another design...](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1304%3A244161)
  - https://github.com/vector-im/element-android/issues/4384

- [x] **See Thread Summary from Timeline**
  - From the Timeline I should be able to see a summary of the Thread
  - [Design](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1304%3A244141)
  - https://github.com/vector-im/element-android/issues/4385

- [x] **Send a link to a Thread**
  - Share a Thread message, in the same way I can Share a Room message including a Matrix.to link
  - [Design](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1430%3A237753)
  - https://github.com/vector-im/element-android/issues/4386

- [x] **Search results from Threads**
  - When I search for a message, return results from a Thread
  - [Design](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2858%3A290566)
  - Unencrypted Rooms & Encrypted Rooms 
  - https://github.com/vector-im/element-android/issues/4387

- [x] **Find a Thread through mentions - Notifications & Badges**
  - [Android Design: Unread Threads, no mentions](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1587%3A244184)
  - [Android Design: Unread Threads, with mentions](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1587%3A244197)
  - [Android Design: & unreads more than 99](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1587%3A244731)
  - https://github.com/vector-im/element-android/issues/4388
  - _Push notifications on Threads - TBD_

- [x] **Message action bar for events in Thread**
  - _Design_ https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1433%3A238070
  - [x] Add "View in Room" option to Root Thread event 
  - Do not allow user to create a Thread from a Thread
  - https://github.com/vector-im/element-android/issues/4389

- [x] **Be aware of new activity on a Thread**
  - New activity on a Thread is visible to me from the Timeline and from the Thread view
  - Handled by Notifications and Thread Summary updates https://github.com/vector-im/element-android/issues/4388

- [x]  **Room Notification count for Thread events**
  - *Design* https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1587%3A244184
  - The badge on the room list should increment when there are unread Threads in the room. 
   - Handled by Notifications and Thread Summary updates https://github.com/vector-im/element-android/issues/4388

- [x] **See/Read all Threads I have responded to in a room** (Filter)
  - Be able to see Threads I have responded to in a Room in the Room Threads list view
  - [Design](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1304%3A244182)
  - [_Issue_](https://github.com/vector-im/element-android/issues/4683)
  - Requires Backend API

- [x] **Create Thread deleted state UI for when root message removed**
  - [Design](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=1304%3A244192)
  - vector-im/element-ios#5473

- [x] Thread visibility when invited to a room & no permissions to view thread https://github.com/vector-im/element-android/issues/4681

- [ ] **Create Automated tests for Threads P0**
  - _Design_ (n/a)
  - _Issue_

- [ ] **Launch plan TBD** @daniellekirkwood 
  - https://github.com/vector-im/element-web/issues/19270

- [ ] **P0 smoke testing** 
  - https://github.com/vector-im/element-android/issues/4448
  - https://github.com/vector-im/element-android/issues/4449
- [ ] **P0 acceptance testing** 
  - https://github.com/vector-im/element-android/issues/4450
- [ ] **P0 user testing** 
  - https://github.com/vector-im/element-android/issues/4451

- [x] **See Threads as Reply if don’t have Threads** 
  - If a client/bridge does not have Threads enabled, Thread responses show as Replies in the Timeline
  - https://github.com/vector-im/element-android/issues/4246

- [x] **Disable/Enable thread feature** from build configuration while some customers may not want to have threads
    - https://github.com/vector-im/element-android/issues/4434
    
 - [ ] https://github.com/vector-im/element-meta/issues/59

- [x] [New - January 2022] https://github.com/vector-im/element-android/issues/4916
- [ ] [New - January 2022] https://github.com/vector-im/element-android/issues/4977
- [x] https://github.com/vector-im/element-android/issues/4972

**Comment by daniellekirkwood** [comment]
Handle Threads before launching Threads: https://github.com/vector-im/element-android/issues/4246

**Comment by daniellekirkwood** [comment]
Discussion in Element yesterday; Adding a floating Thread Panel that expands on swipe up will add days of engineering effort. For MVP we will use the full screen version, and revisit that decision if we have time before launch.

👀 @janogarcia & @ariskotsomitopoulos
