### ISSUE TITLE
Notifications: Get your updates

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#711]
This issue has been updated due to the change in org and shift in priorities. It's still WIP while we figure out details

As part of the Get Your Updates cycle in the Delight team (Q4 FY22) we are left with a few outstanding action items.

More information on the history of Get Your Updates can be found in the [Delight team roadmap](https://docs.google.com/spreadsheets/d/1SAcCgnHoze9Flqx-XXkC0B8iQyLnpylv2z4iidK0v-8/edit?usp=sharing), and this [quick history doc](https://docs.google.com/document/d/1bpz4Q1TABJL2vYKDSytRRdOEwgLgoJbZUyRkb40lihM/edit?usp=sharing). More information and a better write up is WIP (@daniellekirkwood)

As the Delight team combines with the Web team, the following work should transition to the new [web backlog](https://github.com/orgs/vector-im/projects/67/views/1):

## User facing improvements
**1. [Update default settings](https://github.com/vector-im/element-meta/issues/887)**
Users expect that defaults make sense and customisation is available when they need it. 
- [ ] https://github.com/vector-im/element-web/issues/24014
- [ ] @daniellekirkwood to drive the conclusion of outstanding questions for defaults and update here. 
---

 **2. [Simplify settings](https://github.com/vector-im/element-meta/issues/888)**
If the defaults set by Element don't work for a user, we need to provide a simple and easy to understand interface where user's can update their notifications settings to match their working style
- [ ] Make copy and visual changes to the Quick Notifications options in a room
- [ ] Update the copy and visuals for the Account Settings: Notifications page
- [ ] Update the copy and visuals for the Room Settings: Notifications page
---

**3. [Remove unintentional pings](https://github.com/vector-im/element-meta/issues/886)**
Users should only get pings when that is intended by the user. This includes improving the sender's environment as well as the receiver's.
- [MSC3952](https://github.com/matrix-org/matrix-spec-proposals/pull/3952)
- Design is still in progress , we need to discuss this and nail down tasks to be created given the draft designs.
- More tasks to be added soon...
---

**4. [Improve the visuals](https://github.com/vector-im/element-meta/issues/889) & room cell decorations**
- [x] https://github.com/vector-im/element-web/issues/24344
- [ ]  Update the room list cells to match the new designs 
- [ ] @daniellekirkwood to find and link the issue about spoilers in the preview
- [ ] @daniellekirkwood to find and link the issue about prepending threads messages in the preview
- [x] https://github.com/vector-im/element-web/issues/23920
- [ ] https://github.com/vector-im/element-android/issues/7727
- [ ] https://github.com/vector-im/element-ios/issues/7139

## Stretch goals
**[Introduce smart banners and PON links](https://github.com/vector-im/element-meta/issues/890)**
Design still WIP; Using the new crypto banner at a room level, show users 'point of need' information if their behaviour matches criteria. In all cases when the banner is dismissed from that room it does not show again.
- [ ] When a user is typing/sends a message in a DM that's on mute
- [ ] When a user is typing/sends a message in a room marked Favourite that's on mute
- [ ] When a user has a low priority room on All Messages (M&K)
- [ ] When a user has a large room on All Messages (M&K)
---

**Marking a room as read/unread**
- [x] https://github.com/vector-im/element-web/issues/24053
- [ ] Mark room as read on Web 
  - ([more info here](https://github.com/vector-im/element-meta/issues/891))
 ---

**Introduce better sending etiquettes**
Design still WIP; The problem of overwhelming notifications can be resolved by better settings and defaults on the receivers side but giving the sender more information may also help. 
- [ ] When the user types "@room" into the composer, add content that explains the consequences of their actions (like slack)

## Chronic Issues
This cycle seeks to solve the following Chronic Issues: 
- [Users expect to be told when they have missed notifications](https://github.com/vector-im/element-meta/issues/615)
- [Users expect DMs and mentions to notify them by default - but not random chats in group rooms. Public chats notify by default, encouraging you to mute the app.](https://github.com/vector-im/element-meta/issues/614)
