### ISSUE TITLE
Message Bubbles

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#72]
We're delivering Message Bubbles for a customer and for users.

### Milestone 1 (Build & Labs flags)
_Implement Bubbles across all 3 platforms_
- [x] Web
- [ ] iOS: https://github.com/vector-im/element-ios/issues/5395
- [x] Android: https://github.com/vector-im/element-android/issues/4974

_Rounds of Testing [(Sheet here)](https://docs.google.com/spreadsheets/d/1uCccAjxA5dhbVXQmq9b_bbqOJF0kSkLLuCFu8SLdQ-Y/edit#gid=1213169053) completed and passed_
- [x] https://github.com/vector-im/element-web/issues/20327
- [x] https://github.com/vector-im/element-android/issues/4800
- [x] https://github.com/vector-im/element-ios/issues/5330
- [x] https://github.com/vector-im/element-web/issues/20328
- [x] https://github.com/vector-im/element-android/issues/4801
- [x] https://github.com/vector-im/element-ios/issues/5331
- [x] https://github.com/vector-im/element-web/issues/20329
- [x] https://github.com/vector-im/element-android/issues/4802
- [ ] https://github.com/vector-im/element-ios/issues/5332

_Deliver Bubbles for users and customers_
- [x] Deliver Bubbles in Settings for users: Web https://github.com/vector-im/element-web/issues/20244
- [x] Deliver Bubbles in Settings for users: Android https://github.com/vector-im/element-android/issues/4751
- [ ] Deliver Bubbles in Settings for users: iOS https://github.com/vector-im/element-ios/issues/5321

### Milestone 2 (Flexibility)
- [ ] Make Bubbles appearance flexible (E.G.: Only in DMs, per Space, etc.)
- [ ] Update Emote Bubble type

---

**Comment by daniellekirkwood** [comment]
### To Bubble, or not to Bubble:

| **Event/Message Type**                                       | **To Bubble, or not to Bubble?**        | Web                                                   | Android                                                  | iOS                                                  |
| ------------------------------------------------------------ | --------------------------------------- | ----------------------------------------------------- | -------------------------------------------------------- | ---------------------------------------------------- |
| **State events:** [List of state events](https://github.com/vector-im/element-meta/issues/72#issuecomment-995010131) | No state events in Bubbles.             | --                                                    | --                                                       | --                                                   |
| **Timeline events:**                                         | --                                      | --                                                    | --                                                       | --                                                   |
| Redaction                                                    | No                                      |                                                       |                                                          |                                                      |
| Sticker                                                      | No, not in a Bubble                     | https://github.com/vector-im/element-web/issues/20523 | https://github.com/vector-im/element-android/issues/4965 | https://github.com/vector-im/element-ios/issues/5388 |
| Call                                                         | No Bubble, centred                      | https://github.com/vector-im/element-web/issues/20324 |                                                          |                                                      |
| Poll                                                         | No Bubble, centred on Mobile <br> We had to make the call to temporarily have Polls in Bubbles on Mobile due to time constraints           | Done                                                  | https://github.com/vector-im/element-android/issues/4576 | https://github.com/vector-im/element-ios/issues/5210 |
| **Message:**                                                 | --                                      | --                                                    | --                                                       | --                                                   |
| Text                                                         | Yes, in a Bubble                        | Done                                                  | https://github.com/vector-im/element-android/issues/4574 | https://github.com/vector-im/element-ios/issues/5208 |
| Emote                                                        | No, not in a bubble                     | https://github.com/vector-im/element-web/issues/20617 | --                                                       | --                                                   |
| Notice                                                       | TBD                                     | Need to see this msg type for decision                |                                                          |                                                      |
| Image (media)                                                | No Bubble; Needs timestamp and gradient | https://github.com/vector-im/element-web/issues/20326 | https://github.com/vector-im/element-android/issues/4575 | https://github.com/vector-im/element-ios/issues/5209 |
| File (media)  | No Bubble                               | https://github.com/vector-im/element-web/issues/20326 | https://github.com/vector-im/element-android/issues/4575 | https://github.com/vector-im/element-ios/issues/5209 |
| Audio (media)  | No Bubble                               | https://github.com/vector-im/element-web/issues/20326 | https://github.com/vector-im/element-android/issues/4575 | https://github.com/vector-im/element-ios/issues/5209 |
| Location (media) | No Bubble                               | https://github.com/vector-im/element-web/issues/20323 | https://github.com/vector-im/element-android/issues/4575 | https://github.com/vector-im/element-ios/issues/5209 |
| Video (media)  | No Bubble   | https://github.com/vector-im/element-web/issues/20326 | https://github.com/vector-im/element-android/issues/4575 | https://github.com/vector-im/element-ios/issues/5209 |
| E2E Verification | TBD | Need to see this msg type for decision                |                                                          |                                                      |
| Replies | Yes , in a Bubble   | Done  | https://github.com/vector-im/element-android/issues/4583 | https://github.com/vector-im/element-ios/issues/5213 |
| Quotes | Yes, in a Bubble | Done | https://github.com/vector-im/element-android/issues/4580 | https://github.com/vector-im/element-ios/issues/5215 |
| URL previews | No Bubble  | Done   | https://github.com/vector-im/element-android/issues/4579 | https://github.com/vector-im/element-ios/issues/5212 |
| Code blocks | Yes, in a Bubble | Done  | https://github.com/vector-im/element-android/issues/4574 |                                                      |
| Thread Summary | No Bubble | https://github.com/vector-im/element-web/issues/20419 | https://github.com/vector-im/element-android/issues/4870 | https://github.com/vector-im/element-ios/issues/5348 |
| Thread Messages | Yes, in Thread panel timeline           | https://github.com/vector-im/element-web/issues/20419 | https://github.com/vector-im/element-android/issues/4870 | https://github.com/vector-im/element-ios/issues/5348 |
| Emoji Reaction   | Not in bubble                           | Done                                                  | https://github.com/vector-im/element-android/issues/4582 | https://github.com/vector-im/element-ios/issues/5214 |
| Read receipts  | Not in bubble | Done  | No bubbles change needed (see comment below) | No bubbles change needed (see comment below) |

**Comment by daniellekirkwood** [comment]
List of State Events:
Canonical Alias ([#matrix:matrix.org](https://matrix.to/#/#matrix:matrix.org)), Join Rules (public, private etc), Member (membership, displayname change etc), 3PID invite (invite to email address), Permissions (PL) change, Room Name, Room Topic, Room Avatar, Change pinned events (labs), Encryption enabled, History visibility, Guest access, Server ACLs, Tombstone, Manage widgets, Hidden/Unknown events (development mode)

**Comment by daniellekirkwood** [comment]
### Other improvements to make as a part of Bubbles work

**These do not Block the release of Bubbles**

|       Message type       | Web  | Android                                                      | iOS  |
| ------------- | ---- | ------------------------------------------------------------ | ---- |
| Reactions     |      | https://github.com/vector-im/element-android/issues/4674<br />https://github.com/vector-im/element-android/issues/3344 |   https://github.com/vector-im/element-ios/issues/5370   |
| Replies       |      | https://github.com/vector-im/element-android/issues/3703     |   Don't think any change is needed here  |
| Read receipts |    | No change for V1 </br> https://github.com/vector-im/element-android/issues/4915     |   No change for V1 </br> https://github.com/vector-im/element-ios/issues/5371   |
| Files         |      | https://github.com/vector-im/element-android/issues/4897     |   https://github.com/vector-im/element-ios/issues/5372   |

**Comment by daniellekirkwood** [comment]
Emote issue: https://github.com/vector-im/element-web/issues/20322

**Comment by daniellekirkwood** [comment]
Polls go in a bubble on Mobile as they take the whole width of the screen and without the bubble it is not clear who sent it the message...

**Comment by daniellekirkwood** [comment]
Emotes are staying in a Bubble on iOS due to how long it will take to move them out. They should be moved out of bubbles once the timeline has been refactored

**Comment by daniellekirkwood** [comment]
Bubbles are no longer in Labs on iOS so moving this issue to complete.
