### ISSUE TITLE
Element R Mobile

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#745]
- [x] [Element R iOS](https://github.com/vector-im/element-ios/issues/6587)
- [x] [Element R android](https://github.com/vector-im/element-android/issues/3644)
    - [x] https://github.com/vector-im/element-android/pull/7628
    - [x] https://github.com/vector-im/crypto-internal/issues/72

**Comment by MadLittleMods** [comment]
@BillCarsonFr Can we check off any of these boxes like iOS? Any more details to add?
