### ISSUE TITLE
Users should be able to read their existing history rapidly when logging in on a new device.

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#757]
Large key backups take forever to restore \(or fail entirely\); should restore incrementally instead

### Web
- [ ] https://github.com/vector-im/element-web/issues/19778
- [ ] https://github.com/vector-im/element-web/issues/23359
- [ ] https://github.com/vector-im/element-meta/issues/2176

### Rust
- [x] https://github.com/matrix-org/matrix-rust-sdk/issues/1267

IOS: Similar issue

Android:
Better but still some issues, incremental backup calls done after each syncs so can take some time if not a lot to sync. And it's not working that well for large gappy syncs, in this case the crypto service is catching up on a lot of to\_devices that will trigger upload of the newly received key and looks like it's blocking the backup from incrementally downloading keys

How to test:

- Login an existing account with a big key backup.
- Open e2ee rooms, history should decrypt quickly \(seconds\)

**Comment by richvdh** [comment]
requires a fix to https://github.com/element-hq/element-web/issues/27009 ?

**Comment by richvdh** [comment]
I don't know what's left to do here. We fetch keys on demand.
