### ISSUE TITLE
Epic | Element R

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#760]
Use the crypto rust sdk on all clients, and drop native implementations.

**Goals**
- Improve reliability
- Improve speed
- Improve time to develop new features by having more shared code

```[tasklist]
## Dev Tasks
- [ ] https://github.com/vector-im/element-meta/issues/745
- [ ] https://github.com/vector-im/element-web/issues/21972
```

```[tasklist]
## Rust crate feature parity
- [ ] https://github.com/vector-im/element-meta/issues/759
```
```[tasklist]
### Stretch goals
- [ ] Remove legacy code from EA
```

**Comment by richvdh** [comment]
Remaining Element R work is being tracked on our [taskboard](https://github.com/orgs/vector-im/projects/76/views/15)
