### ISSUE TITLE
Implement MSC3834 TOFU (user key pinning)

### ISSUE THREAD

**Issue by BillCarsonFr** [vector-im/element-meta#764]
Implement MSC3834 in ER and EX clients, as a solution to https://github.com/element-hq/element-meta/issues/1557

```[tasklist]
### Dev tasks
- [ ] https://github.com/matrix-org/matrix-spec-proposals/pull/3834
- [ ] #1112
- [ ] matrix-org/matrix-rust-sdk#1528
- [ ] Migrate existing account to support new TSK
- [ ] ER Android UI work
- [ ] ER iOS UI work
- [ ] EX UI support
- [ ] Web UI support
```

**Comment by pmaier1** [comment]
Targeted for EX but might come for free for ER. We should discuss implications and potential follow-up tasks once we start working on it.

**Comment by richvdh** [comment]
For clarity: this issue tracks an implementation of MSC3834.

We are currently working on a simpler implementation of TOFU, as part of the "Invisible crypto" project. Once that is complete, this issue will track the additional work needed to complete the implementation of MSC3834.
