### ISSUE TITLE
Standardise wording for threads in the labs setting

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#860]
We're calling them "threads", "threaded messaging" and "thread messages" across the three platforms. We should use "Threaded messages" in all cases

- [x] vector-im/element-ios/issues/7147
- [x] vector-im/element-android/issues/7748
- [x] vector-im/element-web/issues/23946

**Comment by daniellekirkwood** [comment]
Looks done, let's close @kittykat ?
