### ISSUE TITLE
Threads P0: iOS 

### ISSUE THREAD

**Issue by daniellekirkwood** [vector-im/element-meta#9]
- View [MSC3440 Threading via m.thread relation](https://github.com/matrix-org/matrix-doc/pull/3440)
- View 🧵 [Threads board](https://github.com/orgs/vector-im/projects/17)

# iOS Must Haves

- [x] https://github.com/vector-im/element-ios/issues/5068
  - Using the Message action bar, choose a message from the Timeline to start a Thread by sending a response (that does not show in the Timeline)
  - [Design: Starting a new thread. Case: Initiated by a short tap on a message.](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2265%3A256789)

- [x] https://github.com/vector-im/element-ios/issues/5069
  - See a Thread, and send a message in response (that does not show in the Timeline)
  - [Design: Viewing and replying to a thread](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2265%3A261854)

- [x] **See/Read previous responses in a Thread in the right order (Thread history)**
  - When I click to read a Thread, I should be able to see previous responses in the correct order
  - _This is acceptance criteria and does not need a design or an issue_

- [x] https://github.com/vector-im/element-ios/issues/5092
  - If I'm in a Room, I need to be able to scroll up through the Timeline and click to read a Thread
  - From the Timeline, I can use the Thread icon to view the Thread List view
  - [Design: Viewing the thread list](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2272%3A261926)

- [x] https://github.com/vector-im/element-ios/issues/5093
  - From the Timeline I should be able to see a summary of the Thread
  - [Design: Thread summary](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2275%3A256977)

- [x] https://github.com/vector-im/element-ios/issues/5094
  - Share a Thread message, in the same way I can Share a Room message including a Matrix.to link
  - [Design: Thread header actions](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2276%3A260811)

- [x] https://github.com/vector-im/element-ios/issues/5095
  - When I search for a message, return results from a Thread
  - Unencrypted Rooms & Encrypted Rooms solution
  - [Design: Search results](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2858%3A290566)

- [x] https://github.com/vector-im/element-ios/issues/5096
  - [Design: Unread threads, no mentions](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2272%3A263284)
  - [Design: Unread threads, with mentions](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2272%3A263285)
  - [Design: Maximum unread count and overflow](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2272%3A263286)
  - Push notifications on Threads - TBD

- [x] https://github.com/vector-im/element-ios/issues/5117
  - Add "View in Room" option to Root Thread event 
  - Do not allow user to create a Thread from a Thread
  - [Design: Thread message actions](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2276%3A260812)

- [x] **Be aware of new activity on a Thread**
  - New activity on a Thread is visible to me from the Timeline and from the Thread view
  - Handled by Notifications and Thread Summary updates

- [x] **Room Notification count for Thread events**
  - [Design: Viewing the thread notifications](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2272%3A263284)
  - Handled by Notifications and Thread Summary updates

- [x]  **(Filter)** https://github.com/vector-im/element-ios/issues/5092
  - [Design: Filtering the thread list](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2276%3A258217)
- [x]  **(Be able to see Threads I have responded to in a Room in the Room Threads list view)** https://github.com/vector-im/element-ios/issues/5092
  - [Design: Filtering the thread list](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2276%3A258217)

- [x] https://github.com/vector-im/element-ios/issues/5119
  - [Design: Deleting the root message](https://www.figma.com/file/T309ztx0sNyOOK6NKVLHsK/Threads?node-id=2272%3A266615)

- [ ] https://github.com/vector-im/element-ios/issues/5396
- [x] [New - January 2022] https://github.com/vector-im/element-ios/issues/5373
- [ ] [New - January 2022] Disable Threads State Event for Rooms with Bridges https://github.com/vector-im/element-ios/issues/5397

#### Testing 
- [ ] **Create Automated tests for Threads P0** - TBD
- [x] **P0 smoke testing** @kittykat
  - https://github.com/vector-im/element-ios/issues/5123
  - https://github.com/vector-im/element-ios/issues/5124
- [ ] **P0 acceptance testing** @kittykat
  - https://github.com/vector-im/element-ios/issues/5125
- [ ] **P0 user testing** @kittykat
  - https://github.com/vector-im/element-ios/issues/5126

#### Launching
- [x] https://github.com/vector-im/element-ios/issues/5007 (See Threads as Reply if don’t have Threads)
  - If a client/bridge does not have Threads enabled, Thread responses show as Replies in the Timeline
- [x] https://github.com/vector-im/element-ios/issues/5394
- [ ] https://github.com/vector-im/element-web/issues/19270

**Comment by daniellekirkwood** [comment]
Handle Threads before launching Threads: https://github.com/vector-im/element-ios/issues/5007

**Comment by daniellekirkwood** [comment]
Discussion in Element today; Adding a floating Thread Panel that expands on swipe up will add 3-4 days of engineering time. This action will be de-scoped for the MVP.

👀  @janogarcia & @ismailgulek
