### ISSUE TITLE
[Epic] Create and join rooms

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-meta#988]
## Open questions

```[tasklist]
### ❓
```

## Scope

```[tasklist]
### User stories
- [ ] https://github.com/vector-im/element-meta/issues/989
- [ ] https://github.com/vector-im/element-meta/issues/1055
- [ ] https://github.com/vector-im/element-meta/issues/991
- [ ] https://github.com/vector-im/element-meta/issues/993
- [ ] https://github.com/vector-im/element-meta/issues/994
- [ ] https://github.com/vector-im/element-meta/issues/992
- [ ] https://github.com/vector-im/element-meta/issues/1691
- [ ] https://github.com/vector-im/element-x-ios/issues/1016
- [ ] https://github.com/vector-im/element-x-android/issues/505
- [ ] https://github.com/vector-im/element-x-ios/issues/1040
- [ ] https://github.com/vector-im/element-x-android/issues/550
- [ ] https://github.com/vector-im/element-x-android/issues/590
- [ ] https://github.com/vector-im/element-x-ios/issues/1077
- [ ] https://github.com/vector-im/element-x-android/issues/616
- [ ] https://github.com/vector-im/element-x-android/issues/623
- [ ] https://github.com/vector-im/element-x-ios/issues/1169
```

## Out of scope

- Inviting users to matrix that do not have a matrix id.
- https://github.com/vector-im/element-meta/issues/990
- https://github.com/vector-im/element-meta/issues/1160
- https://github.com/vector-im/element-meta/issues/1780
- https://github.com/vector-im/element-meta/issues/1782

### Known SDK & backend issues

- https://github.com/matrix-org/matrix-rust-sdk/issues/2078
- https://github.com/matrix-org/matrix-rust-sdk/issues/2017
- https://github.com/matrix-org/matrix-rust-sdk/issues/1834
- https://gitlab.element.io/engineering/p2p-dendrite/sliding-sync/-/issues/72

## Sign-off

**Android**
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion
- [x] https://github.com/vector-im/element-x-android/issues/409

**iOS**
- [ ] Design sign-off on completion
- [ ] QA sign-off on completion
- [ ] Product sign-off on completion

## Internal references

[Technical lead](https://gitlab.matrix.org/new-vector/internal/-/wikis/Departments/Engineering/Engineering-Roles#project-technical-lead): @alfogrillo 

myhours project: Element X

**Comment by Johennes** [comment]
I'm closing this off as completed since all tasks are done and we've reviewed the implementations in the weekly. Any further issues reported from here on will be treated as either maintenance or new feature requests.

**Comment by wrenix** [comment]
Where is the solution to Join Rooms? (I am not able to Join per mxid  vor Matrix.to links)
